// Command genfacade creates the stable repository facade from sqlc output.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type method struct {
	name       string
	parameters []parameter
	results    []string
}

type parameter struct {
	name     string
	typeName string
}

func main() {
	files, err := filepath.Glob("../repository/*.go")
	if err != nil {
		panic(err)
	}
	methods, localTypes, err := parse(files)
	if err != nil {
		panic(err)
	}
	sort.Slice(methods, func(i, j int) bool { return methods[i].name < methods[j].name })

	var output bytes.Buffer
	output.WriteString("// Code generated by go generate; DO NOT EDIT.\n\npackage data\n\n")
	output.WriteString("import (\n\t\"context\"\n\t\"database/sql\"\n\t\"encoding/json\"\n\t\"time\"\n\n\t\"github.com/flatout-works/chetter/internal/repository\"\n\t\"github.com/flatout-works/chetter/internal/repositorypostgres\"\n)\n\n")
	output.WriteString("// Repository is the database-independent query surface used by services.\ntype Repository interface {\n\tDB() *sql.DB\n\tSearchTasks(context.Context, repository.SearchTasksParams) ([]repository.ChetterTask, error)\n\tListAuditLog(context.Context, repository.ListAuditLogParams) ([]repository.ListAuditLogRow, error)\n\tListTaskArtifacts(context.Context, repository.ListTaskArtifactsParams) ([]repository.ListTaskArtifactsRow, error)\n")
	for _, method := range methods {
		fmt.Fprintf(&output, "\t%s(%s) %s\n", method.name, parameters(method.parameters, localTypes), results(method.results, localTypes))
	}
	output.WriteString("}\n\n")
	for _, method := range methods {
		writeMethod(&output, method, localTypes)
	}

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("queries_gen.go", formatted, 0o644); err != nil {
		panic(err)
	}
}

func parse(files []string) ([]method, map[string]bool, error) {
	localTypes := make(map[string]bool)
	methodMap := make(map[string]method)
	for _, file := range files {
		parsed, err := parser.ParseFile(token.NewFileSet(), file, nil, 0)
		if err != nil {
			return nil, nil, err
		}
		for _, declaration := range parsed.Decls {
			if general, ok := declaration.(*ast.GenDecl); ok && general.Tok == token.TYPE {
				for _, spec := range general.Specs {
					localTypes[spec.(*ast.TypeSpec).Name.Name] = true
				}
			}
			function, ok := declaration.(*ast.FuncDecl)
			if !ok || function.Recv == nil || function.Name.Name == "WithTx" || function.Name.Name == "DB" || function.Name.Name == "SearchTasks" || function.Name.Name == "ListAuditLog" || function.Name.Name == "ListTaskArtifacts" {
				continue
			}
			if len(function.Recv.List) != 1 || expr(function.Recv.List[0].Type) != "*Queries" {
				continue
			}
			methodMap[function.Name.Name] = method{
				name:       function.Name.Name,
				parameters: fields(function.Type.Params),
				results:    resultFields(function.Type.Results),
			}
		}
	}
	methods := make([]method, 0, len(methodMap))
	for _, method := range methodMap {
		methods = append(methods, method)
	}
	return methods, localTypes, nil
}

func fields(list *ast.FieldList) []parameter {
	if list == nil {
		return nil
	}
	var values []parameter
	for _, field := range list.List {
		for _, name := range field.Names {
			values = append(values, parameter{name: name.Name, typeName: expr(field.Type)})
		}
	}
	return values
}

func resultFields(list *ast.FieldList) []string {
	if list == nil {
		return nil
	}
	var values []string
	for _, field := range list.List {
		values = append(values, expr(field.Type))
	}
	return values
}

func expr(node ast.Expr) string {
	var output bytes.Buffer
	if err := format.Node(&output, token.NewFileSet(), node); err != nil {
		panic(err)
	}
	return output.String()
}

func parameters(values []parameter, localTypes map[string]bool) string {
	output := make([]string, len(values))
	for i, value := range values {
		output[i] = value.name + " " + qualify(value.typeName, localTypes)
	}
	return strings.Join(output, ", ")
}

func results(values []string, localTypes map[string]bool) string {
	qualified := make([]string, len(values))
	for i, value := range values {
		qualified[i] = qualify(value, localTypes)
	}
	if len(qualified) == 1 {
		return qualified[0]
	}
	return "(" + strings.Join(qualified, ", ") + ")"
}

func qualify(value string, localTypes map[string]bool) string {
	for name := range localTypes {
		value = regexp.MustCompile(`\b`+regexp.QuoteMeta(name)+`\b`).ReplaceAllStringFunc(value, func(match string) string {
			if strings.Contains(value[:strings.Index(value, match)], ".") {
				return match
			}
			return "repository." + match
		})
	}
	return value
}

func writeMethod(output *bytes.Buffer, method method, localTypes map[string]bool) {
	fmt.Fprintf(output, "func (q *Queries) %s(%s) %s {\n", method.name, parameters(method.parameters, localTypes), results(method.results, localTypes))
	postgresArguments := make([]string, len(method.parameters))
	for i, parameter := range method.parameters {
		if i == 0 {
			postgresArguments[i] = parameter.name
		} else {
			postgresArguments[i] = "convert[" + postgresType(parameter.typeName, localTypes) + "](" + parameter.name + ")"
		}
	}
	if len(method.results) == 1 && method.results[0] == "error" {
		fmt.Fprintf(output, "\treturn q.postgres.%s(%s)\n}\n\n", method.name, strings.Join(postgresArguments, ", "))
		return
	}
	fmt.Fprintf(output, "\tvalue, err := q.postgres.%s(%s)\n\treturn convert[%s](value), err\n}\n\n", method.name, strings.Join(postgresArguments, ", "), qualify(method.results[0], localTypes))
}

func postgresType(value string, localTypes map[string]bool) string {
	if value == "[]sql.NullString" {
		return "[]string"
	}
	for name := range localTypes {
		value = regexp.MustCompile(`\b`+regexp.QuoteMeta(name)+`\b`).ReplaceAllString(value, "repositorypostgres."+name)
	}
	return value
}
