// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package repositorypostgres

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO chetter_audit_log (id, event_type, created_at, source_type, source_id, target_type, target_id, repo, github_event, github_action, github_delivery_id, parent_event_id, detail, search_text, payload, token_id, token_name)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
`

type InsertAuditLogParams struct {
	ID               string           `json:"id"`
	EventType        string           `json:"event_type"`
	CreatedAt        time.Time        `json:"created_at"`
	SourceType       sql.NullString   `json:"source_type"`
	SourceID         sql.NullString   `json:"source_id"`
	TargetType       sql.NullString   `json:"target_type"`
	TargetID         sql.NullString   `json:"target_id"`
	Repo             sql.NullString   `json:"repo"`
	GithubEvent      sql.NullString   `json:"github_event"`
	GithubAction     sql.NullString   `json:"github_action"`
	GithubDeliveryID sql.NullString   `json:"github_delivery_id"`
	ParentEventID    sql.NullString   `json:"parent_event_id"`
	Detail           sql.NullString   `json:"detail"`
	SearchText       sql.NullString   `json:"search_text"`
	Payload          *json.RawMessage `json:"payload"`
	TokenID          sql.NullString   `json:"token_id"`
	TokenName        sql.NullString   `json:"token_name"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.ID,
		arg.EventType,
		arg.CreatedAt,
		arg.SourceType,
		arg.SourceID,
		arg.TargetType,
		arg.TargetID,
		arg.Repo,
		arg.GithubEvent,
		arg.GithubAction,
		arg.GithubDeliveryID,
		arg.ParentEventID,
		arg.Detail,
		arg.SearchText,
		arg.Payload,
		arg.TokenID,
		arg.TokenName,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, event_type, created_at, source_type, source_id, target_type, target_id, repo, github_event, github_action, github_delivery_id, parent_event_id, detail, payload, token_id, token_name
FROM chetter_audit_log
WHERE (event_type = $1 OR $1 = '')
  AND (source_type = $2 OR $2 = '')
  AND (source_id = $3 OR $3 = '')
  AND (target_type = $4 OR $4 = '')
  AND (target_id = $5 OR $5 = '')
  AND (repo = $6 OR $6 = '')
  AND (created_at >= $7 OR $7 IS NULL)
ORDER BY created_at DESC
LIMIT $9 OFFSET $8
`

type ListAuditLogParams struct {
	EventTypeFilter  string         `json:"event_type_filter"`
	SourceTypeFilter sql.NullString `json:"source_type_filter"`
	SourceIDFilter   sql.NullString `json:"source_id_filter"`
	TargetTypeFilter sql.NullString `json:"target_type_filter"`
	TargetIDFilter   sql.NullString `json:"target_id_filter"`
	RepoFilter       sql.NullString `json:"repo_filter"`
	CreatedAfter     sql.NullTime   `json:"created_after"`
	PageOffset       int32          `json:"page_offset"`
	PageLimit        int32          `json:"page_limit"`
}

type ListAuditLogRow struct {
	ID               string           `json:"id"`
	EventType        string           `json:"event_type"`
	CreatedAt        time.Time        `json:"created_at"`
	SourceType       sql.NullString   `json:"source_type"`
	SourceID         sql.NullString   `json:"source_id"`
	TargetType       sql.NullString   `json:"target_type"`
	TargetID         sql.NullString   `json:"target_id"`
	Repo             sql.NullString   `json:"repo"`
	GithubEvent      sql.NullString   `json:"github_event"`
	GithubAction     sql.NullString   `json:"github_action"`
	GithubDeliveryID sql.NullString   `json:"github_delivery_id"`
	ParentEventID    sql.NullString   `json:"parent_event_id"`
	Detail           sql.NullString   `json:"detail"`
	Payload          *json.RawMessage `json:"payload"`
	TokenID          sql.NullString   `json:"token_id"`
	TokenName        sql.NullString   `json:"token_name"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]ListAuditLogRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLog,
		arg.EventTypeFilter,
		arg.SourceTypeFilter,
		arg.SourceIDFilter,
		arg.TargetTypeFilter,
		arg.TargetIDFilter,
		arg.RepoFilter,
		arg.CreatedAfter,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogRow{}
	for rows.Next() {
		var i ListAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.CreatedAt,
			&i.SourceType,
			&i.SourceID,
			&i.TargetType,
			&i.TargetID,
			&i.Repo,
			&i.GithubEvent,
			&i.GithubAction,
			&i.GithubDeliveryID,
			&i.ParentEventID,
			&i.Detail,
			&i.Payload,
			&i.TokenID,
			&i.TokenName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAuditLog = `-- name: SearchAuditLog :many
SELECT id, event_type, created_at, source_type, source_id, target_type, target_id, repo, github_event, github_action, github_delivery_id, parent_event_id, detail, payload, token_id, token_name
FROM chetter_audit_log
WHERE (event_type = $1 OR $1 = '')
  AND (source_type = $2 OR $2 = '')
  AND (source_id = $3 OR $3 = '')
  AND (target_type = $4 OR $4 = '')
  AND (target_id = $5 OR $5 = '')
  AND (repo = $6 OR $6 = '')
  AND (created_at >= $7 OR $7 IS NULL)
  AND search_text ILIKE '%' || $8 || '%'
ORDER BY created_at DESC
LIMIT $10 OFFSET $9
`

type SearchAuditLogParams struct {
	EventTypeFilter  string         `json:"event_type_filter"`
	SourceTypeFilter sql.NullString `json:"source_type_filter"`
	SourceIDFilter   sql.NullString `json:"source_id_filter"`
	TargetTypeFilter sql.NullString `json:"target_type_filter"`
	TargetIDFilter   sql.NullString `json:"target_id_filter"`
	RepoFilter       sql.NullString `json:"repo_filter"`
	CreatedAfter     sql.NullTime   `json:"created_after"`
	Search           sql.NullString `json:"search"`
	PageOffset       int32          `json:"page_offset"`
	PageLimit        int32          `json:"page_limit"`
}

type SearchAuditLogRow struct {
	ID               string           `json:"id"`
	EventType        string           `json:"event_type"`
	CreatedAt        time.Time        `json:"created_at"`
	SourceType       sql.NullString   `json:"source_type"`
	SourceID         sql.NullString   `json:"source_id"`
	TargetType       sql.NullString   `json:"target_type"`
	TargetID         sql.NullString   `json:"target_id"`
	Repo             sql.NullString   `json:"repo"`
	GithubEvent      sql.NullString   `json:"github_event"`
	GithubAction     sql.NullString   `json:"github_action"`
	GithubDeliveryID sql.NullString   `json:"github_delivery_id"`
	ParentEventID    sql.NullString   `json:"parent_event_id"`
	Detail           sql.NullString   `json:"detail"`
	Payload          *json.RawMessage `json:"payload"`
	TokenID          sql.NullString   `json:"token_id"`
	TokenName        sql.NullString   `json:"token_name"`
}

func (q *Queries) SearchAuditLog(ctx context.Context, arg SearchAuditLogParams) ([]SearchAuditLogRow, error) {
	rows, err := q.db.QueryContext(ctx, searchAuditLog,
		arg.EventTypeFilter,
		arg.SourceTypeFilter,
		arg.SourceIDFilter,
		arg.TargetTypeFilter,
		arg.TargetIDFilter,
		arg.RepoFilter,
		arg.CreatedAfter,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAuditLogRow{}
	for rows.Next() {
		var i SearchAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.CreatedAt,
			&i.SourceType,
			&i.SourceID,
			&i.TargetType,
			&i.TargetID,
			&i.Repo,
			&i.GithubEvent,
			&i.GithubAction,
			&i.GithubDeliveryID,
			&i.ParentEventID,
			&i.Detail,
			&i.Payload,
			&i.TokenID,
			&i.TokenName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
