// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: definitions.sql

package repositorypostgres

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const deactivateDefinitionsBySource = `-- name: DeactivateDefinitionsBySource :exec
UPDATE definitions SET active = false, updated_at = $1 WHERE source_id = $2 AND active = true
`

type DeactivateDefinitionsBySourceParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	SourceID  string    `json:"source_id"`
}

func (q *Queries) DeactivateDefinitionsBySource(ctx context.Context, arg DeactivateDefinitionsBySourceParams) error {
	_, err := q.db.ExecContext(ctx, deactivateDefinitionsBySource, arg.UpdatedAt, arg.SourceID)
	return err
}

const getDefinitionBySourceTypeName = `-- name: GetDefinitionBySourceTypeName :one
SELECT id, source_id, definition_type, name, scope, team_id, repo, path, source_commit, content_hash, content, metadata, active, created_at, updated_at FROM definitions
WHERE source_id = $1 AND definition_type = $2 AND name = $3 AND active = true
  AND ($4 = '' OR scope = $4)
ORDER BY CASE scope
    WHEN 'global' THEN 0
    WHEN 'team' THEN 1
    WHEN 'repo' THEN 2
    ELSE 3
END, updated_at DESC
LIMIT 1
`

type GetDefinitionBySourceTypeNameParams struct {
	SourceID       string      `json:"source_id"`
	DefinitionType string      `json:"definition_type"`
	Name           string      `json:"name"`
	ScopeFilter    interface{} `json:"scope_filter"`
}

func (q *Queries) GetDefinitionBySourceTypeName(ctx context.Context, arg GetDefinitionBySourceTypeNameParams) (Definition, error) {
	row := q.db.QueryRowContext(ctx, getDefinitionBySourceTypeName,
		arg.SourceID,
		arg.DefinitionType,
		arg.Name,
		arg.ScopeFilter,
	)
	var i Definition
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DefinitionType,
		&i.Name,
		&i.Scope,
		&i.TeamID,
		&i.Repo,
		&i.Path,
		&i.SourceCommit,
		&i.ContentHash,
		&i.Content,
		&i.Metadata,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefinitionSource = `-- name: GetDefinitionSource :one
SELECT id, name, scope, team_id, repo, repo_url, branch, path, enabled, created_at, updated_at, last_sync_at FROM definition_sources WHERE id = $1
`

func (q *Queries) GetDefinitionSource(ctx context.Context, id string) (DefinitionSource, error) {
	row := q.db.QueryRowContext(ctx, getDefinitionSource, id)
	var i DefinitionSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.TeamID,
		&i.Repo,
		&i.RepoUrl,
		&i.Branch,
		&i.Path,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSyncAt,
	)
	return i, err
}

const getDefinitionSourceByName = `-- name: GetDefinitionSourceByName :one
SELECT id, name, scope, team_id, repo, repo_url, branch, path, enabled, created_at, updated_at, last_sync_at FROM definition_sources WHERE name = $1
`

func (q *Queries) GetDefinitionSourceByName(ctx context.Context, name string) (DefinitionSource, error) {
	row := q.db.QueryRowContext(ctx, getDefinitionSourceByName, name)
	var i DefinitionSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.TeamID,
		&i.Repo,
		&i.RepoUrl,
		&i.Branch,
		&i.Path,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSyncAt,
	)
	return i, err
}

const insertDefinitionSyncRun = `-- name: InsertDefinitionSyncRun :exec
INSERT INTO definition_sync_runs (
    id, source_id, status, source_commit, definitions_count, error, started_at, ended_at, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertDefinitionSyncRunParams struct {
	ID               string         `json:"id"`
	SourceID         string         `json:"source_id"`
	Status           string         `json:"status"`
	SourceCommit     sql.NullString `json:"source_commit"`
	DefinitionsCount int32          `json:"definitions_count"`
	Error            sql.NullString `json:"error"`
	StartedAt        time.Time      `json:"started_at"`
	EndedAt          time.Time      `json:"ended_at"`
	CreatedAt        time.Time      `json:"created_at"`
}

func (q *Queries) InsertDefinitionSyncRun(ctx context.Context, arg InsertDefinitionSyncRunParams) error {
	_, err := q.db.ExecContext(ctx, insertDefinitionSyncRun,
		arg.ID,
		arg.SourceID,
		arg.Status,
		arg.SourceCommit,
		arg.DefinitionsCount,
		arg.Error,
		arg.StartedAt,
		arg.EndedAt,
		arg.CreatedAt,
	)
	return err
}

const listDefinitionSources = `-- name: ListDefinitionSources :many
SELECT id, name, scope, team_id, repo, repo_url, branch, path, enabled, created_at, updated_at, last_sync_at FROM definition_sources ORDER BY scope ASC, name ASC
`

func (q *Queries) ListDefinitionSources(ctx context.Context) ([]DefinitionSource, error) {
	rows, err := q.db.QueryContext(ctx, listDefinitionSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DefinitionSource{}
	for rows.Next() {
		var i DefinitionSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scope,
			&i.TeamID,
			&i.Repo,
			&i.RepoUrl,
			&i.Branch,
			&i.Path,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSyncAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDefinitionSyncRuns = `-- name: ListDefinitionSyncRuns :many
SELECT id, source_id, status, source_commit, definitions_count, error, started_at, ended_at, created_at FROM definition_sync_runs
WHERE ($1 = '' OR source_id = $1)
ORDER BY created_at DESC
LIMIT $2
`

type ListDefinitionSyncRunsParams struct {
	SourceIDFilter interface{} `json:"source_id_filter"`
	PageLimit      int32       `json:"page_limit"`
}

func (q *Queries) ListDefinitionSyncRuns(ctx context.Context, arg ListDefinitionSyncRunsParams) ([]DefinitionSyncRun, error) {
	rows, err := q.db.QueryContext(ctx, listDefinitionSyncRuns, arg.SourceIDFilter, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DefinitionSyncRun{}
	for rows.Next() {
		var i DefinitionSyncRun
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Status,
			&i.SourceCommit,
			&i.DefinitionsCount,
			&i.Error,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDefinitions = `-- name: ListDefinitions :many
SELECT id, source_id, definition_type, name, scope, team_id, repo, path, source_commit, content_hash, content, metadata, active, created_at, updated_at FROM definitions
WHERE ($1 = '' OR definition_type = $1)
  AND ($2 = '' OR source_id = $2)
  AND ($3 = '' OR name = $3)
  AND active = true
ORDER BY definition_type ASC, name ASC, scope ASC
`

type ListDefinitionsParams struct {
	DefinitionTypeFilter interface{} `json:"definition_type_filter"`
	SourceIDFilter       interface{} `json:"source_id_filter"`
	NameFilter           interface{} `json:"name_filter"`
}

func (q *Queries) ListDefinitions(ctx context.Context, arg ListDefinitionsParams) ([]Definition, error) {
	rows, err := q.db.QueryContext(ctx, listDefinitions, arg.DefinitionTypeFilter, arg.SourceIDFilter, arg.NameFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Definition{}
	for rows.Next() {
		var i Definition
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DefinitionType,
			&i.Name,
			&i.Scope,
			&i.TeamID,
			&i.Repo,
			&i.Path,
			&i.SourceCommit,
			&i.ContentHash,
			&i.Content,
			&i.Metadata,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDefinitionSourceSynced = `-- name: MarkDefinitionSourceSynced :exec
UPDATE definition_sources SET last_sync_at = $1, updated_at = $2 WHERE id = $3
`

type MarkDefinitionSourceSyncedParams struct {
	LastSyncAt sql.NullTime `json:"last_sync_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	ID         string       `json:"id"`
}

func (q *Queries) MarkDefinitionSourceSynced(ctx context.Context, arg MarkDefinitionSourceSyncedParams) error {
	_, err := q.db.ExecContext(ctx, markDefinitionSourceSynced, arg.LastSyncAt, arg.UpdatedAt, arg.ID)
	return err
}

const upsertDefinition = `-- name: UpsertDefinition :exec
INSERT INTO definitions (
    id, source_id, definition_type, name, scope, team_id, repo, path, source_commit,
    content_hash, content, metadata, active, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (source_id, definition_type, name, path) DO UPDATE SET
    scope = EXCLUDED.scope,
    team_id = EXCLUDED.team_id,
    repo = EXCLUDED.repo,
    source_commit = EXCLUDED.source_commit,
    content_hash = EXCLUDED.content_hash,
    content = EXCLUDED.content,
    metadata = EXCLUDED.metadata,
    active = EXCLUDED.active,
    updated_at = EXCLUDED.updated_at
`

type UpsertDefinitionParams struct {
	ID             string           `json:"id"`
	SourceID       string           `json:"source_id"`
	DefinitionType string           `json:"definition_type"`
	Name           string           `json:"name"`
	Scope          string           `json:"scope"`
	TeamID         sql.NullString   `json:"team_id"`
	Repo           sql.NullString   `json:"repo"`
	Path           string           `json:"path"`
	SourceCommit   string           `json:"source_commit"`
	ContentHash    string           `json:"content_hash"`
	Content        string           `json:"content"`
	Metadata       *json.RawMessage `json:"metadata"`
	Active         bool             `json:"active"`
	CreatedAt      time.Time        `json:"created_at"`
	UpdatedAt      time.Time        `json:"updated_at"`
}

func (q *Queries) UpsertDefinition(ctx context.Context, arg UpsertDefinitionParams) error {
	_, err := q.db.ExecContext(ctx, upsertDefinition,
		arg.ID,
		arg.SourceID,
		arg.DefinitionType,
		arg.Name,
		arg.Scope,
		arg.TeamID,
		arg.Repo,
		arg.Path,
		arg.SourceCommit,
		arg.ContentHash,
		arg.Content,
		arg.Metadata,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertDefinitionSource = `-- name: UpsertDefinitionSource :exec
INSERT INTO definition_sources (
    id, name, scope, team_id, repo, repo_url, branch, path, enabled, created_at, updated_at, last_sync_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (name) DO UPDATE SET
    scope = EXCLUDED.scope,
    team_id = EXCLUDED.team_id,
    repo = EXCLUDED.repo,
    repo_url = EXCLUDED.repo_url,
    branch = EXCLUDED.branch,
    path = EXCLUDED.path,
    enabled = EXCLUDED.enabled,
    updated_at = EXCLUDED.updated_at,
    last_sync_at = COALESCE(EXCLUDED.last_sync_at, definition_sources.last_sync_at)
`

type UpsertDefinitionSourceParams struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Scope      string         `json:"scope"`
	TeamID     sql.NullString `json:"team_id"`
	Repo       sql.NullString `json:"repo"`
	RepoUrl    string         `json:"repo_url"`
	Branch     string         `json:"branch"`
	Path       string         `json:"path"`
	Enabled    bool           `json:"enabled"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	LastSyncAt sql.NullTime   `json:"last_sync_at"`
}

func (q *Queries) UpsertDefinitionSource(ctx context.Context, arg UpsertDefinitionSourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertDefinitionSource,
		arg.ID,
		arg.Name,
		arg.Scope,
		arg.TeamID,
		arg.Repo,
		arg.RepoUrl,
		arg.Branch,
		arg.Path,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastSyncAt,
	)
	return err
}
