// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: execution_attempts.sql

package repositorypostgres

import (
	"context"
	"database/sql"
	"time"
)

const getClaimableExecutionAttemptForUpdate = `-- name: GetClaimableExecutionAttemptForUpdate :one
SELECT attempt.id AS execution_attempt_id, prompt.task_id, prompt.id AS user_prompt_id, task.id AS locked_task_id
FROM chetter_execution_attempts attempt
JOIN chetter_user_prompts prompt ON prompt.id = attempt.user_prompt_id
JOIN chetter_tasks task ON task.id = prompt.task_id
WHERE attempt.status = 'pending'
  AND task.status = 'pending'
  AND task.attempt < task.max_attempts
  AND (attempt.required_runner_id IS NULL OR attempt.required_runner_id = '' OR attempt.required_runner_id = $1)
ORDER BY attempt.created_at ASC
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type GetClaimableExecutionAttemptForUpdateRow struct {
	ExecutionAttemptID string `json:"execution_attempt_id"`
	TaskID             string `json:"task_id"`
	UserPromptID       string `json:"user_prompt_id"`
	LockedTaskID       string `json:"locked_task_id"`
}

func (q *Queries) GetClaimableExecutionAttemptForUpdate(ctx context.Context, runnerID sql.NullString) (GetClaimableExecutionAttemptForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getClaimableExecutionAttemptForUpdate, runnerID)
	var i GetClaimableExecutionAttemptForUpdateRow
	err := row.Scan(
		&i.ExecutionAttemptID,
		&i.TaskID,
		&i.UserPromptID,
		&i.LockedTaskID,
	)
	return i, err
}

const getExecutionAttemptByID = `-- name: GetExecutionAttemptByID :one
SELECT id, user_prompt_id, sequence, status, runner_id, required_runner_id, claimed_at, lease_expires_at, started_at, ended_at, workspace_path, container_name, harness_execution_id, summary, error, error_category, session_export, total_input_tokens, total_output_tokens, total_cache_read_tokens, total_cache_write_tokens, total_reasoning_tokens, cost_cents, created_at, updated_at FROM chetter_execution_attempts WHERE id = $1
`

func (q *Queries) GetExecutionAttemptByID(ctx context.Context, id string) (ChetterExecutionAttempt, error) {
	row := q.db.QueryRowContext(ctx, getExecutionAttemptByID, id)
	var i ChetterExecutionAttempt
	err := row.Scan(
		&i.ID,
		&i.UserPromptID,
		&i.Sequence,
		&i.Status,
		&i.RunnerID,
		&i.RequiredRunnerID,
		&i.ClaimedAt,
		&i.LeaseExpiresAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.WorkspacePath,
		&i.ContainerName,
		&i.HarnessExecutionID,
		&i.Summary,
		&i.Error,
		&i.ErrorCategory,
		&i.SessionExport,
		&i.TotalInputTokens,
		&i.TotalOutputTokens,
		&i.TotalCacheReadTokens,
		&i.TotalCacheWriteTokens,
		&i.TotalReasoningTokens,
		&i.CostCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextExecutionAttemptSequence = `-- name: GetNextExecutionAttemptSequence :one
SELECT COALESCE(MAX(sequence), 0) + 1
FROM chetter_execution_attempts
WHERE user_prompt_id = $1
`

func (q *Queries) GetNextExecutionAttemptSequence(ctx context.Context, userPromptID string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getNextExecutionAttemptSequence, userPromptID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertExecutionAttempt = `-- name: InsertExecutionAttempt :exec
INSERT INTO chetter_execution_attempts
    (id, user_prompt_id, sequence, status, runner_id, required_runner_id, claimed_at, lease_expires_at, started_at, created_at, updated_at)
VALUES ($1, $2, $3, 'running', $4, $5, $6, $7, $8, $9, $10)
`

type InsertExecutionAttemptParams struct {
	ID               string         `json:"id"`
	UserPromptID     string         `json:"user_prompt_id"`
	Sequence         int32          `json:"sequence"`
	RunnerID         sql.NullString `json:"runner_id"`
	RequiredRunnerID sql.NullString `json:"required_runner_id"`
	ClaimedAt        sql.NullTime   `json:"claimed_at"`
	LeaseExpiresAt   sql.NullTime   `json:"lease_expires_at"`
	StartedAt        sql.NullTime   `json:"started_at"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

func (q *Queries) InsertExecutionAttempt(ctx context.Context, arg InsertExecutionAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertExecutionAttempt,
		arg.ID,
		arg.UserPromptID,
		arg.Sequence,
		arg.RunnerID,
		arg.RequiredRunnerID,
		arg.ClaimedAt,
		arg.LeaseExpiresAt,
		arg.StartedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertPendingExecutionAttempt = `-- name: InsertPendingExecutionAttempt :exec
INSERT INTO chetter_execution_attempts
    (id, user_prompt_id, sequence, status, required_runner_id, created_at, updated_at)
VALUES ($1, $2, $3, 'pending', $4, $5, $6)
`

type InsertPendingExecutionAttemptParams struct {
	ID               string         `json:"id"`
	UserPromptID     string         `json:"user_prompt_id"`
	Sequence         int32          `json:"sequence"`
	RequiredRunnerID sql.NullString `json:"required_runner_id"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

func (q *Queries) InsertPendingExecutionAttempt(ctx context.Context, arg InsertPendingExecutionAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertPendingExecutionAttempt,
		arg.ID,
		arg.UserPromptID,
		arg.Sequence,
		arg.RequiredRunnerID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listExecutionAttemptsByPrompt = `-- name: ListExecutionAttemptsByPrompt :many
SELECT id, user_prompt_id, sequence, status, runner_id, required_runner_id, claimed_at, lease_expires_at, started_at, ended_at, workspace_path, container_name, harness_execution_id, summary, error, error_category, session_export, total_input_tokens, total_output_tokens, total_cache_read_tokens, total_cache_write_tokens, total_reasoning_tokens, cost_cents, created_at, updated_at FROM chetter_execution_attempts
WHERE user_prompt_id = $1
ORDER BY sequence ASC, created_at ASC
`

func (q *Queries) ListExecutionAttemptsByPrompt(ctx context.Context, userPromptID string) ([]ChetterExecutionAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listExecutionAttemptsByPrompt, userPromptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterExecutionAttempt{}
	for rows.Next() {
		var i ChetterExecutionAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserPromptID,
			&i.Sequence,
			&i.Status,
			&i.RunnerID,
			&i.RequiredRunnerID,
			&i.ClaimedAt,
			&i.LeaseExpiresAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.WorkspacePath,
			&i.ContainerName,
			&i.HarnessExecutionID,
			&i.Summary,
			&i.Error,
			&i.ErrorCategory,
			&i.SessionExport,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.TotalCacheReadTokens,
			&i.TotalCacheWriteTokens,
			&i.TotalReasoningTokens,
			&i.CostCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExecutionAttemptClaimed = `-- name: MarkExecutionAttemptClaimed :execrows
UPDATE chetter_execution_attempts
SET status = 'running', runner_id = $1, claimed_at = $2, lease_expires_at = $3, started_at = $4, updated_at = $5
WHERE id = $6 AND status = 'pending'
`

type MarkExecutionAttemptClaimedParams struct {
	RunnerID       sql.NullString `json:"runner_id"`
	ClaimedAt      sql.NullTime   `json:"claimed_at"`
	LeaseExpiresAt sql.NullTime   `json:"lease_expires_at"`
	StartedAt      sql.NullTime   `json:"started_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ID             string         `json:"id"`
}

func (q *Queries) MarkExecutionAttemptClaimed(ctx context.Context, arg MarkExecutionAttemptClaimedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markExecutionAttemptClaimed,
		arg.RunnerID,
		arg.ClaimedAt,
		arg.LeaseExpiresAt,
		arg.StartedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markExecutionAttemptLost = `-- name: MarkExecutionAttemptLost :execrows
UPDATE chetter_execution_attempts
SET status = 'lost', error = $1, ended_at = $2, updated_at = $3
WHERE id = $4 AND status = 'running'
`

type MarkExecutionAttemptLostParams struct {
	Error     sql.NullString `json:"error"`
	EndedAt   sql.NullTime   `json:"ended_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) MarkExecutionAttemptLost(ctx context.Context, arg MarkExecutionAttemptLostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markExecutionAttemptLost,
		arg.Error,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renewExecutionAttemptLease = `-- name: RenewExecutionAttemptLease :execrows
UPDATE chetter_execution_attempts
SET lease_expires_at = $1, updated_at = $2
WHERE id = $3 AND runner_id = $4 AND status = 'running'
`

type RenewExecutionAttemptLeaseParams struct {
	LeaseExpiresAt sql.NullTime   `json:"lease_expires_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ID             string         `json:"id"`
	RunnerID       sql.NullString `json:"runner_id"`
}

func (q *Queries) RenewExecutionAttemptLease(ctx context.Context, arg RenewExecutionAttemptLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewExecutionAttemptLease,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.ID,
		arg.RunnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateExecutionAttemptFromRunnerEvent = `-- name: UpdateExecutionAttemptFromRunnerEvent :execrows
UPDATE chetter_execution_attempts
SET status = $1,
    summary = $2,
    error = $3,
    error_category = COALESCE(NULLIF($4::text, ''), error_category),
    session_export = COALESCE($5, session_export),
    lease_expires_at = $6,
    started_at = COALESCE($7, started_at),
    ended_at = COALESCE($8, ended_at),
    workspace_path = COALESCE(NULLIF($9::text, ''), workspace_path),
    harness_execution_id = COALESCE(NULLIF($10::text, ''), harness_execution_id),
    total_input_tokens = total_input_tokens + $11,
    total_output_tokens = total_output_tokens + $12,
    total_cache_read_tokens = total_cache_read_tokens + $13,
    total_cache_write_tokens = total_cache_write_tokens + $14,
    total_reasoning_tokens = total_reasoning_tokens + $15,
    cost_cents = cost_cents + $16,
    updated_at = $17
WHERE id = $18 AND runner_id = $19 AND status = 'running'
`

type UpdateExecutionAttemptFromRunnerEventParams struct {
	Status                string         `json:"status"`
	Summary               sql.NullString `json:"summary"`
	Error                 sql.NullString `json:"error"`
	ErrorCategory         string         `json:"error_category"`
	SessionExport         sql.NullString `json:"session_export"`
	LeaseExpiresAt        sql.NullTime   `json:"lease_expires_at"`
	StartedAt             sql.NullTime   `json:"started_at"`
	EndedAt               sql.NullTime   `json:"ended_at"`
	WorkspacePath         string         `json:"workspace_path"`
	HarnessExecutionID    string         `json:"harness_execution_id"`
	TotalInputTokens      int64          `json:"total_input_tokens"`
	TotalOutputTokens     int64          `json:"total_output_tokens"`
	TotalCacheReadTokens  int64          `json:"total_cache_read_tokens"`
	TotalCacheWriteTokens int64          `json:"total_cache_write_tokens"`
	TotalReasoningTokens  int64          `json:"total_reasoning_tokens"`
	CostCents             int64          `json:"cost_cents"`
	UpdatedAt             time.Time      `json:"updated_at"`
	ID                    string         `json:"id"`
	RunnerID              sql.NullString `json:"runner_id"`
}

func (q *Queries) UpdateExecutionAttemptFromRunnerEvent(ctx context.Context, arg UpdateExecutionAttemptFromRunnerEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateExecutionAttemptFromRunnerEvent,
		arg.Status,
		arg.Summary,
		arg.Error,
		arg.ErrorCategory,
		arg.SessionExport,
		arg.LeaseExpiresAt,
		arg.StartedAt,
		arg.EndedAt,
		arg.WorkspacePath,
		arg.HarnessExecutionID,
		arg.TotalInputTokens,
		arg.TotalOutputTokens,
		arg.TotalCacheReadTokens,
		arg.TotalCacheWriteTokens,
		arg.TotalReasoningTokens,
		arg.CostCents,
		arg.UpdatedAt,
		arg.ID,
		arg.RunnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
