// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runners.sql

package repositorypostgres

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const listLiveRunners = `-- name: ListLiveRunners :many
SELECT id, status, image_ref, image_digest, version, max_concurrent, running_tasks, available_slots, total_started, total_completed, total_errors, started_at, first_seen_at, last_seen_at, updated_at, metadata
FROM chetter_runners
WHERE last_seen_at >= $1
ORDER BY last_seen_at DESC
`

func (q *Queries) ListLiveRunners(ctx context.Context, lastSeenAt time.Time) ([]ChetterRunner, error) {
	rows, err := q.db.QueryContext(ctx, listLiveRunners, lastSeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterRunner{}
	for rows.Next() {
		var i ChetterRunner
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ImageRef,
			&i.ImageDigest,
			&i.Version,
			&i.MaxConcurrent,
			&i.RunningTasks,
			&i.AvailableSlots,
			&i.TotalStarted,
			&i.TotalCompleted,
			&i.TotalErrors,
			&i.StartedAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRunnerHeartbeat = `-- name: UpsertRunnerHeartbeat :exec
INSERT INTO chetter_runners
    (id, status, image_ref, image_digest, version,
     max_concurrent, running_tasks, available_slots, total_started, total_completed, total_errors,
     started_at, first_seen_at, last_seen_at, updated_at, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    image_ref = EXCLUDED.image_ref,
    image_digest = EXCLUDED.image_digest,
    version = EXCLUDED.version,
    max_concurrent = EXCLUDED.max_concurrent,
    running_tasks = EXCLUDED.running_tasks,
    available_slots = EXCLUDED.available_slots,
    total_started = EXCLUDED.total_started,
    total_completed = EXCLUDED.total_completed,
    total_errors = EXCLUDED.total_errors,
    started_at = COALESCE(EXCLUDED.started_at, chetter_runners.started_at),
    last_seen_at = EXCLUDED.last_seen_at,
    updated_at = EXCLUDED.updated_at,
    metadata = EXCLUDED.metadata
`

type UpsertRunnerHeartbeatParams struct {
	ID             string          `json:"id"`
	Status         string          `json:"status"`
	ImageRef       sql.NullString  `json:"image_ref"`
	ImageDigest    sql.NullString  `json:"image_digest"`
	Version        sql.NullString  `json:"version"`
	MaxConcurrent  int32           `json:"max_concurrent"`
	RunningTasks   int32           `json:"running_tasks"`
	AvailableSlots int32           `json:"available_slots"`
	TotalStarted   int64           `json:"total_started"`
	TotalCompleted int64           `json:"total_completed"`
	TotalErrors    int64           `json:"total_errors"`
	StartedAt      sql.NullTime    `json:"started_at"`
	FirstSeenAt    time.Time       `json:"first_seen_at"`
	LastSeenAt     time.Time       `json:"last_seen_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	Metadata       json.RawMessage `json:"metadata"`
}

func (q *Queries) UpsertRunnerHeartbeat(ctx context.Context, arg UpsertRunnerHeartbeatParams) error {
	_, err := q.db.ExecContext(ctx, upsertRunnerHeartbeat,
		arg.ID,
		arg.Status,
		arg.ImageRef,
		arg.ImageDigest,
		arg.Version,
		arg.MaxConcurrent,
		arg.RunningTasks,
		arg.AvailableSlots,
		arg.TotalStarted,
		arg.TotalCompleted,
		arg.TotalErrors,
		arg.StartedAt,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.UpdatedAt,
		arg.Metadata,
	)
	return err
}
