// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package repositorypostgres

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const cancelTask = `-- name: CancelTask :execrows
UPDATE chetter_tasks
SET status = 'cancelled',
    error = $1,
    error_category = 'cancelled',
    ended_at = COALESCE(ended_at, $2),
    updated_at = $3
WHERE id = $4 AND status IN ('pending', 'running')
`

type CancelTaskParams struct {
	Error     sql.NullString `json:"error"`
	EndedAt   sql.NullTime   `json:"ended_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) CancelTask(ctx context.Context, arg CancelTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelTask,
		arg.Error,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearPendingTasks = `-- name: ClearPendingTasks :execrows
UPDATE chetter_tasks
SET status = 'cancelled',
    error = $1,
    error_category = 'cancelled',
    ended_at = COALESCE(ended_at, $2),
    updated_at = $3
WHERE status = 'pending'
`

type ClearPendingTasksParams struct {
	Error     sql.NullString `json:"error"`
	EndedAt   sql.NullTime   `json:"ended_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) ClearPendingTasks(ctx context.Context, arg ClearPendingTasksParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearPendingTasks, arg.Error, arg.EndedAt, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failExpiredLeases = `-- name: FailExpiredLeases :execrows
UPDATE chetter_tasks task
SET status = 'error',
    error = attempt.error,
    error_category = 'timeout',
    ended_at = $1,
    updated_at = $2
FROM chetter_user_prompts prompt, chetter_execution_attempts attempt
WHERE prompt.task_id = task.id
  AND attempt.user_prompt_id = prompt.id
  AND task.status = 'running'
  AND attempt.status = 'error'
  AND attempt.error_category = 'timeout'
  AND attempt.lease_expires_at IS NOT NULL
  AND attempt.lease_expires_at < $3
`

type FailExpiredLeasesParams struct {
	EndedAt        sql.NullTime `json:"ended_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	LeaseExpiresAt sql.NullTime `json:"lease_expires_at"`
}

func (q *Queries) FailExpiredLeases(ctx context.Context, arg FailExpiredLeasesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failExpiredLeases, arg.EndedAt, arg.UpdatedAt, arg.LeaseExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLatestTaskEvent = `-- name: GetLatestTaskEvent :one
SELECT id, task_id, subject, status, event_type, payload, created_at, agent_session_id, user_prompt_id, execution_attempt_id FROM chetter_task_events
WHERE task_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestTaskEvent(ctx context.Context, taskID string) (ChetterTaskEvent, error) {
	row := q.db.QueryRowContext(ctx, getLatestTaskEvent, taskID)
	var i ChetterTaskEvent
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Subject,
		&i.Status,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
		&i.AgentSessionID,
		&i.UserPromptID,
		&i.ExecutionAttemptID,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, team_id, status, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, commit_author_name, commit_author_email, checkpoint_after_success, trigger_name, trigger_type, submission_source, max_attempts, skills, env, summary, error, error_category, created_at, updated_at, ended_at, search_text, git_identity_id, mcp_endpoints FROM chetter_tasks WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id string) (ChetterTask, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i ChetterTask
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Status,
		&i.Prompt,
		&i.GitUrl,
		&i.GitRef,
		&i.AgentImage,
		&i.Agent,
		&i.ProviderID,
		&i.ModelID,
		&i.VariantID,
		&i.CommitAuthorName,
		&i.CommitAuthorEmail,
		&i.CheckpointAfterSuccess,
		&i.TriggerName,
		&i.TriggerType,
		&i.SubmissionSource,
		&i.MaxAttempts,
		&i.Skills,
		&i.Env,
		&i.Summary,
		&i.Error,
		&i.ErrorCategory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.SearchText,
		&i.GitIdentityID,
		&i.McpEndpoints,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :exec
INSERT INTO chetter_tasks
    (id, team_id, status, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, commit_author_name, commit_author_email, git_identity_id, trigger_name, trigger_type, submission_source, checkpoint_after_success, skills, mcp_endpoints, env, search_text, created_at, updated_at)
VALUES ($1, $2, 'pending', $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23)
`

type InsertTaskParams struct {
	ID                     string           `json:"id"`
	TeamID                 sql.NullString   `json:"team_id"`
	Prompt                 string           `json:"prompt"`
	GitUrl                 sql.NullString   `json:"git_url"`
	GitRef                 sql.NullString   `json:"git_ref"`
	AgentImage             sql.NullString   `json:"agent_image"`
	Agent                  sql.NullString   `json:"agent"`
	ProviderID             sql.NullString   `json:"provider_id"`
	ModelID                sql.NullString   `json:"model_id"`
	VariantID              sql.NullString   `json:"variant_id"`
	CommitAuthorName       sql.NullString   `json:"commit_author_name"`
	CommitAuthorEmail      sql.NullString   `json:"commit_author_email"`
	GitIdentityID          sql.NullString   `json:"git_identity_id"`
	TriggerName            sql.NullString   `json:"trigger_name"`
	TriggerType            sql.NullString   `json:"trigger_type"`
	SubmissionSource       string           `json:"submission_source"`
	CheckpointAfterSuccess bool             `json:"checkpoint_after_success"`
	Skills                 json.RawMessage  `json:"skills"`
	McpEndpoints           *json.RawMessage `json:"mcp_endpoints"`
	Env                    json.RawMessage  `json:"env"`
	SearchText             sql.NullString   `json:"search_text"`
	CreatedAt              time.Time        `json:"created_at"`
	UpdatedAt              time.Time        `json:"updated_at"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) error {
	_, err := q.db.ExecContext(ctx, insertTask,
		arg.ID,
		arg.TeamID,
		arg.Prompt,
		arg.GitUrl,
		arg.GitRef,
		arg.AgentImage,
		arg.Agent,
		arg.ProviderID,
		arg.ModelID,
		arg.VariantID,
		arg.CommitAuthorName,
		arg.CommitAuthorEmail,
		arg.GitIdentityID,
		arg.TriggerName,
		arg.TriggerType,
		arg.SubmissionSource,
		arg.CheckpointAfterSuccess,
		arg.Skills,
		arg.McpEndpoints,
		arg.Env,
		arg.SearchText,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, team_id, status, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, commit_author_name, commit_author_email, checkpoint_after_success, trigger_name, trigger_type, submission_source, max_attempts, skills, env, summary, error, error_category, created_at, updated_at, ended_at, search_text, git_identity_id, mcp_endpoints FROM chetter_tasks
WHERE ($1 = '' OR status = $1)
  AND (COALESCE($2, '') = '' OR trigger_name = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListTasksByStatusParams struct {
	StatusFilter      interface{} `json:"status_filter"`
	TriggerNameFilter interface{} `json:"trigger_name_filter"`
	PageOffset        int32       `json:"page_offset"`
	PageLimit         int32       `json:"page_limit"`
}

func (q *Queries) ListTasksByStatus(ctx context.Context, arg ListTasksByStatusParams) ([]ChetterTask, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatus,
		arg.StatusFilter,
		arg.TriggerNameFilter,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterTask{}
	for rows.Next() {
		var i ChetterTask
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Status,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.CommitAuthorName,
			&i.CommitAuthorEmail,
			&i.CheckpointAfterSuccess,
			&i.TriggerName,
			&i.TriggerType,
			&i.SubmissionSource,
			&i.MaxAttempts,
			&i.Skills,
			&i.Env,
			&i.Summary,
			&i.Error,
			&i.ErrorCategory,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedAt,
			&i.SearchText,
			&i.GitIdentityID,
			&i.McpEndpoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatusAndTeam = `-- name: ListTasksByStatusAndTeam :many
SELECT id, team_id, status, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, commit_author_name, commit_author_email, checkpoint_after_success, trigger_name, trigger_type, submission_source, max_attempts, skills, env, summary, error, error_category, created_at, updated_at, ended_at, search_text, git_identity_id, mcp_endpoints FROM chetter_tasks
WHERE team_id = $1
  AND ($2 = '' OR status = $2)
  AND (COALESCE($3, '') = '' OR trigger_name = $3)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListTasksByStatusAndTeamParams struct {
	TeamID            sql.NullString `json:"team_id"`
	StatusFilter      interface{}    `json:"status_filter"`
	TriggerNameFilter interface{}    `json:"trigger_name_filter"`
	PageOffset        int32          `json:"page_offset"`
	PageLimit         int32          `json:"page_limit"`
}

func (q *Queries) ListTasksByStatusAndTeam(ctx context.Context, arg ListTasksByStatusAndTeamParams) ([]ChetterTask, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatusAndTeam,
		arg.TeamID,
		arg.StatusFilter,
		arg.TriggerNameFilter,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterTask{}
	for rows.Next() {
		var i ChetterTask
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Status,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.CommitAuthorName,
			&i.CommitAuthorEmail,
			&i.CheckpointAfterSuccess,
			&i.TriggerName,
			&i.TriggerType,
			&i.SubmissionSource,
			&i.MaxAttempts,
			&i.Skills,
			&i.Env,
			&i.Summary,
			&i.Error,
			&i.ErrorCategory,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedAt,
			&i.SearchText,
			&i.GitIdentityID,
			&i.McpEndpoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatusAndTeams = `-- name: ListTasksByStatusAndTeams :many
SELECT id, team_id, status, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, commit_author_name, commit_author_email, checkpoint_after_success, trigger_name, trigger_type, submission_source, max_attempts, skills, env, summary, error, error_category, created_at, updated_at, ended_at, search_text, git_identity_id, mcp_endpoints FROM chetter_tasks
WHERE team_id = ANY($1::text[])
  AND ($2 = '' OR status = $2)
  AND (COALESCE($3, '') = '' OR trigger_name = $3)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListTasksByStatusAndTeamsParams struct {
	TeamIds           []string    `json:"team_ids"`
	StatusFilter      interface{} `json:"status_filter"`
	TriggerNameFilter interface{} `json:"trigger_name_filter"`
	PageOffset        int32       `json:"page_offset"`
	PageLimit         int32       `json:"page_limit"`
}

func (q *Queries) ListTasksByStatusAndTeams(ctx context.Context, arg ListTasksByStatusAndTeamsParams) ([]ChetterTask, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatusAndTeams,
		pq.Array(arg.TeamIds),
		arg.StatusFilter,
		arg.TriggerNameFilter,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterTask{}
	for rows.Next() {
		var i ChetterTask
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Status,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.CommitAuthorName,
			&i.CommitAuthorEmail,
			&i.CheckpointAfterSuccess,
			&i.TriggerName,
			&i.TriggerType,
			&i.SubmissionSource,
			&i.MaxAttempts,
			&i.Skills,
			&i.Env,
			&i.Summary,
			&i.Error,
			&i.ErrorCategory,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedAt,
			&i.SearchText,
			&i.GitIdentityID,
			&i.McpEndpoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskRunning = `-- name: MarkTaskRunning :execrows
UPDATE chetter_tasks
SET status = 'running',
    updated_at = $1
WHERE id = $2 AND status = 'pending'
`

type MarkTaskRunningParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) MarkTaskRunning(ctx context.Context, arg MarkTaskRunningParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markTaskRunning, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueTaskForPrompt = `-- name: RequeueTaskForPrompt :execrows
UPDATE chetter_tasks
SET status = 'pending',
    summary = NULL,
    error = NULL,
    error_category = NULL,
    ended_at = NULL,
    updated_at = $1
WHERE id = $2
  AND status IN ('done', 'error', 'cancelled')
`

type RequeueTaskForPromptParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) RequeueTaskForPrompt(ctx context.Context, arg RequeueTaskForPromptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueTaskForPrompt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const searchTasks = `-- name: SearchTasks :many
SELECT id, team_id, status, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, commit_author_name, commit_author_email, checkpoint_after_success, trigger_name, trigger_type, submission_source, max_attempts, skills, env, summary, error, error_category, created_at, updated_at, ended_at, search_text, git_identity_id, mcp_endpoints FROM chetter_tasks
WHERE ($1 = '' OR team_id = $1)
  AND ($2 = '' OR status = $2)
  AND (COALESCE($3, '') = '' OR trigger_name = $3)
  AND search_text ILIKE '%' || $4 || '%'
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type SearchTasksParams struct {
	TeamFilter        interface{}    `json:"team_filter"`
	StatusFilter      interface{}    `json:"status_filter"`
	TriggerNameFilter interface{}    `json:"trigger_name_filter"`
	Search            sql.NullString `json:"search"`
	PageOffset        int32          `json:"page_offset"`
	PageLimit         int32          `json:"page_limit"`
}

func (q *Queries) SearchTasks(ctx context.Context, arg SearchTasksParams) ([]ChetterTask, error) {
	rows, err := q.db.QueryContext(ctx, searchTasks,
		arg.TeamFilter,
		arg.StatusFilter,
		arg.TriggerNameFilter,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterTask{}
	for rows.Next() {
		var i ChetterTask
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Status,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.CommitAuthorName,
			&i.CommitAuthorEmail,
			&i.CheckpointAfterSuccess,
			&i.TriggerName,
			&i.TriggerType,
			&i.SubmissionSource,
			&i.MaxAttempts,
			&i.Skills,
			&i.Env,
			&i.Summary,
			&i.Error,
			&i.ErrorCategory,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedAt,
			&i.SearchText,
			&i.GitIdentityID,
			&i.McpEndpoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTasksByTeams = `-- name: SearchTasksByTeams :many
SELECT id, team_id, status, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, commit_author_name, commit_author_email, checkpoint_after_success, trigger_name, trigger_type, submission_source, max_attempts, skills, env, summary, error, error_category, created_at, updated_at, ended_at, search_text, git_identity_id, mcp_endpoints FROM chetter_tasks
WHERE team_id = ANY($1::text[])
  AND ($2 = '' OR status = $2)
  AND (COALESCE($3, '') = '' OR trigger_name = $3)
  AND search_text ILIKE '%' || $4 || '%'
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type SearchTasksByTeamsParams struct {
	TeamIds           []string       `json:"team_ids"`
	StatusFilter      interface{}    `json:"status_filter"`
	TriggerNameFilter interface{}    `json:"trigger_name_filter"`
	Search            sql.NullString `json:"search"`
	PageOffset        int32          `json:"page_offset"`
	PageLimit         int32          `json:"page_limit"`
}

func (q *Queries) SearchTasksByTeams(ctx context.Context, arg SearchTasksByTeamsParams) ([]ChetterTask, error) {
	rows, err := q.db.QueryContext(ctx, searchTasksByTeams,
		pq.Array(arg.TeamIds),
		arg.StatusFilter,
		arg.TriggerNameFilter,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterTask{}
	for rows.Next() {
		var i ChetterTask
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Status,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.CommitAuthorName,
			&i.CommitAuthorEmail,
			&i.CheckpointAfterSuccess,
			&i.TriggerName,
			&i.TriggerType,
			&i.SubmissionSource,
			&i.MaxAttempts,
			&i.Skills,
			&i.Env,
			&i.Summary,
			&i.Error,
			&i.ErrorCategory,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedAt,
			&i.SearchText,
			&i.GitIdentityID,
			&i.McpEndpoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskAggregateFromRunnerEvent = `-- name: UpdateTaskAggregateFromRunnerEvent :execrows
UPDATE chetter_tasks
SET status = $1,
    summary = $2,
    error = $3,
    error_category = COALESCE(NULLIF($4, ''), error_category),
    ended_at = COALESCE($5, ended_at),
    updated_at = $6
WHERE id = $7
  AND (status = 'running' OR status = $1)
`

type UpdateTaskAggregateFromRunnerEventParams struct {
	Status        string         `json:"status"`
	Summary       sql.NullString `json:"summary"`
	Error         sql.NullString `json:"error"`
	ErrorCategory interface{}    `json:"error_category"`
	EndedAt       sql.NullTime   `json:"ended_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateTaskAggregateFromRunnerEvent(ctx context.Context, arg UpdateTaskAggregateFromRunnerEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTaskAggregateFromRunnerEvent,
		arg.Status,
		arg.Summary,
		arg.Error,
		arg.ErrorCategory,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTaskSearchText = `-- name: UpdateTaskSearchText :exec
UPDATE chetter_tasks
SET search_text = concat_ws(' ',
    COALESCE(prompt, ''), COALESCE(summary, ''), COALESCE(error, ''),
    COALESCE(agent, ''), COALESCE(model_id, ''), COALESCE(trigger_name, ''),
    COALESCE(git_url, '')
)
WHERE id = $1
`

func (q *Queries) UpdateTaskSearchText(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateTaskSearchText, id)
	return err
}
