// Code generated by go generate; DO NOT EDIT.

package data

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/flatout-works/chetter/internal/repository"
	"github.com/flatout-works/chetter/internal/repositorypostgres"
)

// Repository is the database-independent query surface used by services.
type Repository interface {
	DB() *sql.DB
	SearchTasks(context.Context, repository.SearchTasksParams) ([]repository.ChetterTask, error)
	ListAuditLog(context.Context, repository.ListAuditLogParams) ([]repository.ListAuditLogRow, error)
	ListTaskArtifacts(context.Context, repository.ListTaskArtifactsParams) ([]repository.ListTaskArtifactsRow, error)
	AddTokenTeam(ctx context.Context, arg repository.AddTokenTeamParams) error
	AddUserTeamMembership(ctx context.Context, arg repository.AddUserTeamMembershipParams) error
	CancelTask(ctx context.Context, arg repository.CancelTaskParams) (int64, error)
	ClearPendingTasks(ctx context.Context, arg repository.ClearPendingTasksParams) (int64, error)
	CreateTeam(ctx context.Context, arg repository.CreateTeamParams) error
	CreateToken(ctx context.Context, arg repository.CreateTokenParams) error
	CreateTrigger(ctx context.Context, arg repository.CreateTriggerParams) error
	CreateUser(ctx context.Context, arg repository.CreateUserParams) error
	DeactivateDefinitionsBySource(ctx context.Context, arg repository.DeactivateDefinitionsBySourceParams) error
	DeactivateModelCatalogs(ctx context.Context, updatedAt time.Time) error
	DeleteEventCallback(ctx context.Context, arg repository.DeleteEventCallbackParams) (int64, error)
	DeleteTeam(ctx context.Context, name string) error
	DeleteToken(ctx context.Context, name string) error
	DeleteTokenTeamsByTeam(ctx context.Context, teamID string) error
	DeleteTokensByTeam(ctx context.Context, arg repository.DeleteTokensByTeamParams) error
	DeleteTrigger(ctx context.Context, name string) error
	DeleteTriggersBySource(ctx context.Context, sourceID sql.NullString) error
	DeleteUserTeamMembershipsByTeam(ctx context.Context, teamID string) error
	DeleteUsersByTeam(ctx context.Context, teamID string) error
	ExpirePausedSessions(ctx context.Context, arg repository.ExpirePausedSessionsParams) (int64, error)
	ExtendTaskTimeout(ctx context.Context, arg repository.ExtendTaskTimeoutParams) (int64, error)
	FailExpiredLeases(ctx context.Context, arg repository.FailExpiredLeasesParams) (int64, error)
	FailPendingResumeTasksForMissingRunner(ctx context.Context, arg repository.FailPendingResumeTasksForMissingRunnerParams) (int64, error)
	FailPendingSessionRunsForUnavailableRunner(ctx context.Context, arg repository.FailPendingSessionRunsForUnavailableRunnerParams) (int64, error)
	GetActiveModelCatalog(ctx context.Context) (repository.ChetterModelCatalog, error)
	GetAgentSessionByID(ctx context.Context, id string) (repository.ChetterAgentSession, error)
	GetAgentSessionByTaskID(ctx context.Context, taskID string) (repository.ChetterAgentSession, error)
	GetClaimableTaskForUpdate(ctx context.Context, runnerID sql.NullString) (repository.ChetterTask, error)
	GetDefinitionBySourceTypeName(ctx context.Context, arg repository.GetDefinitionBySourceTypeNameParams) (repository.Definition, error)
	GetDefinitionChangeProposal(ctx context.Context, id string) (repository.DefinitionChangeProposal, error)
	GetDefinitionChangeProposalByPR(ctx context.Context, arg repository.GetDefinitionChangeProposalByPRParams) (repository.DefinitionChangeProposal, error)
	GetDefinitionSource(ctx context.Context, id string) (repository.DefinitionSource, error)
	GetDefinitionSourceByName(ctx context.Context, name string) (repository.DefinitionSource, error)
	GetEventCallbackByID(ctx context.Context, id string) (repository.ChetterEventCallback, error)
	GetEventCallbackByName(ctx context.Context, arg repository.GetEventCallbackByNameParams) (repository.ChetterEventCallback, error)
	GetLatestAgentSessionCheckpoint(ctx context.Context, agentSessionID string) (repository.ChetterAgentSessionCheckpoint, error)
	GetLatestAgentSessionCheckpointByTaskID(ctx context.Context, taskID string) (repository.ChetterAgentSessionCheckpoint, error)
	GetLatestTaskEvent(ctx context.Context, taskID string) (repository.ChetterTaskEvent, error)
	GetModelCatalogByName(ctx context.Context, name string) (repository.ChetterModelCatalog, error)
	GetPausedSessionByArtifact(ctx context.Context, arg repository.GetPausedSessionByArtifactParams) (repository.ChetterAgentSession, error)
	GetSessionRunByTaskID(ctx context.Context, taskID string) (repository.ChetterSessionRun, error)
	GetTaskByID(ctx context.Context, id string) (repository.ChetterTask, error)
	GetTeamByID(ctx context.Context, id string) (repository.Team, error)
	GetTeamByName(ctx context.Context, name string) (repository.Team, error)
	GetTokenByHash(ctx context.Context, tokenHash string) (repository.GetTokenByHashRow, error)
	GetTriggerByID(ctx context.Context, id string) (repository.ChetterTrigger, error)
	GetTriggerByName(ctx context.Context, name string) (repository.ChetterTrigger, error)
	GetUserByID(ctx context.Context, id string) (repository.User, error)
	InsertAgentSession(ctx context.Context, arg repository.InsertAgentSessionParams) error
	InsertAgentSessionCheckpoint(ctx context.Context, arg repository.InsertAgentSessionCheckpointParams) error
	InsertAuditLog(ctx context.Context, arg repository.InsertAuditLogParams) error
	InsertDefinitionChangeProposal(ctx context.Context, arg repository.InsertDefinitionChangeProposalParams) error
	InsertDefinitionSyncRun(ctx context.Context, arg repository.InsertDefinitionSyncRunParams) error
	InsertEventCallback(ctx context.Context, arg repository.InsertEventCallbackParams) error
	InsertModelCatalog(ctx context.Context, arg repository.InsertModelCatalogParams) error
	InsertSessionRun(ctx context.Context, arg repository.InsertSessionRunParams) error
	InsertTask(ctx context.Context, arg repository.InsertTaskParams) error
	InsertTaskArtifact(ctx context.Context, arg repository.InsertTaskArtifactParams) error
	InsertTaskEvent(ctx context.Context, arg repository.InsertTaskEventParams) error
	InsertTriggerRun(ctx context.Context, arg repository.InsertTriggerRunParams) error
	IsRunnerAlive(ctx context.Context, arg repository.IsRunnerAliveParams) (bool, error)
	ListAgentSessions(ctx context.Context, arg repository.ListAgentSessionsParams) ([]repository.ChetterAgentSession, error)
	ListAgentSessionsByTeams(ctx context.Context, arg repository.ListAgentSessionsByTeamsParams) ([]repository.ChetterAgentSession, error)
	ListDefinitionChangeProposals(ctx context.Context, arg repository.ListDefinitionChangeProposalsParams) ([]repository.DefinitionChangeProposal, error)
	ListDefinitionSources(ctx context.Context) ([]repository.DefinitionSource, error)
	ListDefinitionSyncRuns(ctx context.Context, arg repository.ListDefinitionSyncRunsParams) ([]repository.DefinitionSyncRun, error)
	ListDefinitions(ctx context.Context, arg repository.ListDefinitionsParams) ([]repository.Definition, error)
	ListEnabledEventCallbacksForEvent(ctx context.Context, arg repository.ListEnabledEventCallbacksForEventParams) ([]repository.ChetterEventCallback, error)
	ListEnabledIssueTriggersByRepo(ctx context.Context, repo json.RawMessage) ([]repository.ChetterTrigger, error)
	ListEnabledPRReviewTriggersByRepo(ctx context.Context, repo json.RawMessage) ([]repository.ChetterTrigger, error)
	ListEnabledTriggers(ctx context.Context) ([]repository.ChetterTrigger, error)
	ListEnabledTriggersByTeam(ctx context.Context, teamID sql.NullString) ([]repository.ChetterTrigger, error)
	ListEnabledTriggersByTeams(ctx context.Context, teamIds []sql.NullString) ([]repository.ChetterTrigger, error)
	ListEnabledTriggersByType(ctx context.Context, triggerType string) ([]repository.ChetterTrigger, error)
	ListEventCallbacks(ctx context.Context, arg repository.ListEventCallbacksParams) ([]repository.ChetterEventCallback, error)
	ListEventCallbacksByTeams(ctx context.Context, arg repository.ListEventCallbacksByTeamsParams) ([]repository.ChetterEventCallback, error)
	ListHeartbeatTasks(ctx context.Context, arg repository.ListHeartbeatTasksParams) ([]repository.ListHeartbeatTasksRow, error)
	ListLiveRunners(ctx context.Context, lastSeenAt time.Time) ([]repository.ChetterRunner, error)
	ListModelCatalogs(ctx context.Context) ([]repository.ChetterModelCatalog, error)
	ListSessionRunsBySession(ctx context.Context, agentSessionID string) ([]repository.ChetterSessionRun, error)
	ListTaskEvents(ctx context.Context, arg repository.ListTaskEventsParams) ([]repository.ChetterTaskEvent, error)
	ListTaskEventsSince(ctx context.Context, arg repository.ListTaskEventsSinceParams) ([]repository.ChetterTaskEvent, error)
	ListTasksByStatus(ctx context.Context, arg repository.ListTasksByStatusParams) ([]repository.ChetterTask, error)
	ListTasksByStatusAndTeam(ctx context.Context, arg repository.ListTasksByStatusAndTeamParams) ([]repository.ChetterTask, error)
	ListTasksByStatusAndTeams(ctx context.Context, arg repository.ListTasksByStatusAndTeamsParams) ([]repository.ChetterTask, error)
	ListTeams(ctx context.Context) ([]repository.Team, error)
	ListTokens(ctx context.Context) ([]repository.ListTokensRow, error)
	ListTriggerRunsByTeam(ctx context.Context, arg repository.ListTriggerRunsByTeamParams) ([]repository.ListTriggerRunsByTeamRow, error)
	ListTriggerRunsByTeams(ctx context.Context, arg repository.ListTriggerRunsByTeamsParams) ([]repository.ListTriggerRunsByTeamsRow, error)
	ListTriggerRunsByTrigger(ctx context.Context, arg repository.ListTriggerRunsByTriggerParams) ([]repository.ListTriggerRunsByTriggerRow, error)
	ListTriggers(ctx context.Context) ([]repository.ChetterTrigger, error)
	ListTriggersByTeam(ctx context.Context, teamID sql.NullString) ([]repository.ChetterTrigger, error)
	ListTriggersByTeams(ctx context.Context, teamIds []sql.NullString) ([]repository.ChetterTrigger, error)
	ListUsers(ctx context.Context) ([]repository.ListUsersRow, error)
	ListUsersByTeam(ctx context.Context, teamID string) ([]repository.ListUsersByTeamRow, error)
	MarkAgentSessionResuming(ctx context.Context, arg repository.MarkAgentSessionResumingParams) (int64, error)
	MarkAgentSessionTerminalByTask(ctx context.Context, arg repository.MarkAgentSessionTerminalByTaskParams) (int64, error)
	MarkDefinitionSourceSynced(ctx context.Context, arg repository.MarkDefinitionSourceSyncedParams) error
	MarkResumingSessionsFailedForUnavailableRunner(ctx context.Context, updatedAt time.Time) (int64, error)
	MarkSessionRunRunningByTask(ctx context.Context, arg repository.MarkSessionRunRunningByTaskParams) (int64, error)
	MarkSessionRunTerminalByTask(ctx context.Context, arg repository.MarkSessionRunTerminalByTaskParams) (int64, error)
	MarkTaskClaimed(ctx context.Context, arg repository.MarkTaskClaimedParams) (int64, error)
	PauseAgentSessionByTaskID(ctx context.Context, arg repository.PauseAgentSessionByTaskIDParams) (int64, error)
	ReapStaleSessionRuns(ctx context.Context) (int64, error)
	ReapStaleSessionsForTerminalRuns(ctx context.Context) (int64, error)
	ReclaimExpiredLeases(ctx context.Context, arg repository.ReclaimExpiredLeasesParams) (int64, error)
	RenewRunningTaskLeases(ctx context.Context, arg repository.RenewRunningTaskLeasesParams) (int64, error)
	RenewTaskLease(ctx context.Context, arg repository.RenewTaskLeaseParams) (int64, error)
	RevertOrphanedRunningSessionRuns(ctx context.Context) (int64, error)
	SearchAgentSessions(ctx context.Context, arg repository.SearchAgentSessionsParams) ([]repository.ChetterAgentSession, error)
	SearchAgentSessionsByTeams(ctx context.Context, arg repository.SearchAgentSessionsByTeamsParams) ([]repository.ChetterAgentSession, error)
	SearchAuditLog(ctx context.Context, arg repository.SearchAuditLogParams) ([]repository.SearchAuditLogRow, error)
	SearchTaskArtifacts(ctx context.Context, arg repository.SearchTaskArtifactsParams) ([]repository.SearchTaskArtifactsRow, error)
	SearchTasksByTeams(ctx context.Context, arg repository.SearchTasksByTeamsParams) ([]repository.ChetterTask, error)
	SetTriggerLastRun(ctx context.Context, arg repository.SetTriggerLastRunParams) error
	SetTriggerNextRun(ctx context.Context, arg repository.SetTriggerNextRunParams) error
	UpdateDefinitionChangeProposalStatus(ctx context.Context, arg repository.UpdateDefinitionChangeProposalStatusParams) error
	UpdateEventCallback(ctx context.Context, arg repository.UpdateEventCallbackParams) (int64, error)
	UpdateTaskFromRunnerEvent(ctx context.Context, arg repository.UpdateTaskFromRunnerEventParams) (int64, error)
	UpdateTaskSearchText(ctx context.Context, id string) error
	UpdateTrigger(ctx context.Context, arg repository.UpdateTriggerParams) error
	UpsertDefinition(ctx context.Context, arg repository.UpsertDefinitionParams) error
	UpsertDefinitionSource(ctx context.Context, arg repository.UpsertDefinitionSourceParams) error
	UpsertRunnerHeartbeat(ctx context.Context, arg repository.UpsertRunnerHeartbeatParams) error
	UpsertTrigger(ctx context.Context, arg repository.UpsertTriggerParams) error
}

func (q *Queries) AddTokenTeam(ctx context.Context, arg repository.AddTokenTeamParams) error {
	return q.postgres.AddTokenTeam(ctx, convert[repositorypostgres.AddTokenTeamParams](arg))
}

func (q *Queries) AddUserTeamMembership(ctx context.Context, arg repository.AddUserTeamMembershipParams) error {
	return q.postgres.AddUserTeamMembership(ctx, convert[repositorypostgres.AddUserTeamMembershipParams](arg))
}

func (q *Queries) CancelTask(ctx context.Context, arg repository.CancelTaskParams) (int64, error) {
	value, err := q.postgres.CancelTask(ctx, convert[repositorypostgres.CancelTaskParams](arg))
	return convert[int64](value), err
}

func (q *Queries) ClearPendingTasks(ctx context.Context, arg repository.ClearPendingTasksParams) (int64, error) {
	value, err := q.postgres.ClearPendingTasks(ctx, convert[repositorypostgres.ClearPendingTasksParams](arg))
	return convert[int64](value), err
}

func (q *Queries) CreateTeam(ctx context.Context, arg repository.CreateTeamParams) error {
	return q.postgres.CreateTeam(ctx, convert[repositorypostgres.CreateTeamParams](arg))
}

func (q *Queries) CreateToken(ctx context.Context, arg repository.CreateTokenParams) error {
	return q.postgres.CreateToken(ctx, convert[repositorypostgres.CreateTokenParams](arg))
}

func (q *Queries) CreateTrigger(ctx context.Context, arg repository.CreateTriggerParams) error {
	return q.postgres.CreateTrigger(ctx, convert[repositorypostgres.CreateTriggerParams](arg))
}

func (q *Queries) CreateUser(ctx context.Context, arg repository.CreateUserParams) error {
	return q.postgres.CreateUser(ctx, convert[repositorypostgres.CreateUserParams](arg))
}

func (q *Queries) DeactivateDefinitionsBySource(ctx context.Context, arg repository.DeactivateDefinitionsBySourceParams) error {
	return q.postgres.DeactivateDefinitionsBySource(ctx, convert[repositorypostgres.DeactivateDefinitionsBySourceParams](arg))
}

func (q *Queries) DeactivateModelCatalogs(ctx context.Context, updatedAt time.Time) error {
	return q.postgres.DeactivateModelCatalogs(ctx, convert[time.Time](updatedAt))
}

func (q *Queries) DeleteEventCallback(ctx context.Context, arg repository.DeleteEventCallbackParams) (int64, error) {
	value, err := q.postgres.DeleteEventCallback(ctx, convert[repositorypostgres.DeleteEventCallbackParams](arg))
	return convert[int64](value), err
}

func (q *Queries) DeleteTeam(ctx context.Context, name string) error {
	return q.postgres.DeleteTeam(ctx, convert[string](name))
}

func (q *Queries) DeleteToken(ctx context.Context, name string) error {
	return q.postgres.DeleteToken(ctx, convert[string](name))
}

func (q *Queries) DeleteTokenTeamsByTeam(ctx context.Context, teamID string) error {
	return q.postgres.DeleteTokenTeamsByTeam(ctx, convert[string](teamID))
}

func (q *Queries) DeleteTokensByTeam(ctx context.Context, arg repository.DeleteTokensByTeamParams) error {
	return q.postgres.DeleteTokensByTeam(ctx, convert[repositorypostgres.DeleteTokensByTeamParams](arg))
}

func (q *Queries) DeleteTrigger(ctx context.Context, name string) error {
	return q.postgres.DeleteTrigger(ctx, convert[string](name))
}

func (q *Queries) DeleteTriggersBySource(ctx context.Context, sourceID sql.NullString) error {
	return q.postgres.DeleteTriggersBySource(ctx, convert[sql.NullString](sourceID))
}

func (q *Queries) DeleteUserTeamMembershipsByTeam(ctx context.Context, teamID string) error {
	return q.postgres.DeleteUserTeamMembershipsByTeam(ctx, convert[string](teamID))
}

func (q *Queries) DeleteUsersByTeam(ctx context.Context, teamID string) error {
	return q.postgres.DeleteUsersByTeam(ctx, convert[string](teamID))
}

func (q *Queries) ExpirePausedSessions(ctx context.Context, arg repository.ExpirePausedSessionsParams) (int64, error) {
	value, err := q.postgres.ExpirePausedSessions(ctx, convert[repositorypostgres.ExpirePausedSessionsParams](arg))
	return convert[int64](value), err
}

func (q *Queries) ExtendTaskTimeout(ctx context.Context, arg repository.ExtendTaskTimeoutParams) (int64, error) {
	value, err := q.postgres.ExtendTaskTimeout(ctx, convert[repositorypostgres.ExtendTaskTimeoutParams](arg))
	return convert[int64](value), err
}

func (q *Queries) FailExpiredLeases(ctx context.Context, arg repository.FailExpiredLeasesParams) (int64, error) {
	value, err := q.postgres.FailExpiredLeases(ctx, convert[repositorypostgres.FailExpiredLeasesParams](arg))
	return convert[int64](value), err
}

func (q *Queries) FailPendingResumeTasksForMissingRunner(ctx context.Context, arg repository.FailPendingResumeTasksForMissingRunnerParams) (int64, error) {
	value, err := q.postgres.FailPendingResumeTasksForMissingRunner(ctx, convert[repositorypostgres.FailPendingResumeTasksForMissingRunnerParams](arg))
	return convert[int64](value), err
}

func (q *Queries) FailPendingSessionRunsForUnavailableRunner(ctx context.Context, arg repository.FailPendingSessionRunsForUnavailableRunnerParams) (int64, error) {
	value, err := q.postgres.FailPendingSessionRunsForUnavailableRunner(ctx, convert[repositorypostgres.FailPendingSessionRunsForUnavailableRunnerParams](arg))
	return convert[int64](value), err
}

func (q *Queries) GetActiveModelCatalog(ctx context.Context) (repository.ChetterModelCatalog, error) {
	value, err := q.postgres.GetActiveModelCatalog(ctx)
	return convert[repository.ChetterModelCatalog](value), err
}

func (q *Queries) GetAgentSessionByID(ctx context.Context, id string) (repository.ChetterAgentSession, error) {
	value, err := q.postgres.GetAgentSessionByID(ctx, convert[string](id))
	return convert[repository.ChetterAgentSession](value), err
}

func (q *Queries) GetAgentSessionByTaskID(ctx context.Context, taskID string) (repository.ChetterAgentSession, error) {
	value, err := q.postgres.GetAgentSessionByTaskID(ctx, convert[string](taskID))
	return convert[repository.ChetterAgentSession](value), err
}

func (q *Queries) GetClaimableTaskForUpdate(ctx context.Context, runnerID sql.NullString) (repository.ChetterTask, error) {
	value, err := q.postgres.GetClaimableTaskForUpdate(ctx, convert[sql.NullString](runnerID))
	return convert[repository.ChetterTask](value), err
}

func (q *Queries) GetDefinitionBySourceTypeName(ctx context.Context, arg repository.GetDefinitionBySourceTypeNameParams) (repository.Definition, error) {
	value, err := q.postgres.GetDefinitionBySourceTypeName(ctx, convert[repositorypostgres.GetDefinitionBySourceTypeNameParams](arg))
	return convert[repository.Definition](value), err
}

func (q *Queries) GetDefinitionChangeProposal(ctx context.Context, id string) (repository.DefinitionChangeProposal, error) {
	value, err := q.postgres.GetDefinitionChangeProposal(ctx, convert[string](id))
	return convert[repository.DefinitionChangeProposal](value), err
}

func (q *Queries) GetDefinitionChangeProposalByPR(ctx context.Context, arg repository.GetDefinitionChangeProposalByPRParams) (repository.DefinitionChangeProposal, error) {
	value, err := q.postgres.GetDefinitionChangeProposalByPR(ctx, convert[repositorypostgres.GetDefinitionChangeProposalByPRParams](arg))
	return convert[repository.DefinitionChangeProposal](value), err
}

func (q *Queries) GetDefinitionSource(ctx context.Context, id string) (repository.DefinitionSource, error) {
	value, err := q.postgres.GetDefinitionSource(ctx, convert[string](id))
	return convert[repository.DefinitionSource](value), err
}

func (q *Queries) GetDefinitionSourceByName(ctx context.Context, name string) (repository.DefinitionSource, error) {
	value, err := q.postgres.GetDefinitionSourceByName(ctx, convert[string](name))
	return convert[repository.DefinitionSource](value), err
}

func (q *Queries) GetEventCallbackByID(ctx context.Context, id string) (repository.ChetterEventCallback, error) {
	value, err := q.postgres.GetEventCallbackByID(ctx, convert[string](id))
	return convert[repository.ChetterEventCallback](value), err
}

func (q *Queries) GetEventCallbackByName(ctx context.Context, arg repository.GetEventCallbackByNameParams) (repository.ChetterEventCallback, error) {
	value, err := q.postgres.GetEventCallbackByName(ctx, convert[repositorypostgres.GetEventCallbackByNameParams](arg))
	return convert[repository.ChetterEventCallback](value), err
}

func (q *Queries) GetLatestAgentSessionCheckpoint(ctx context.Context, agentSessionID string) (repository.ChetterAgentSessionCheckpoint, error) {
	value, err := q.postgres.GetLatestAgentSessionCheckpoint(ctx, convert[string](agentSessionID))
	return convert[repository.ChetterAgentSessionCheckpoint](value), err
}

func (q *Queries) GetLatestAgentSessionCheckpointByTaskID(ctx context.Context, taskID string) (repository.ChetterAgentSessionCheckpoint, error) {
	value, err := q.postgres.GetLatestAgentSessionCheckpointByTaskID(ctx, convert[string](taskID))
	return convert[repository.ChetterAgentSessionCheckpoint](value), err
}

func (q *Queries) GetLatestTaskEvent(ctx context.Context, taskID string) (repository.ChetterTaskEvent, error) {
	value, err := q.postgres.GetLatestTaskEvent(ctx, convert[string](taskID))
	return convert[repository.ChetterTaskEvent](value), err
}

func (q *Queries) GetModelCatalogByName(ctx context.Context, name string) (repository.ChetterModelCatalog, error) {
	value, err := q.postgres.GetModelCatalogByName(ctx, convert[string](name))
	return convert[repository.ChetterModelCatalog](value), err
}

func (q *Queries) GetPausedSessionByArtifact(ctx context.Context, arg repository.GetPausedSessionByArtifactParams) (repository.ChetterAgentSession, error) {
	value, err := q.postgres.GetPausedSessionByArtifact(ctx, convert[repositorypostgres.GetPausedSessionByArtifactParams](arg))
	return convert[repository.ChetterAgentSession](value), err
}

func (q *Queries) GetSessionRunByTaskID(ctx context.Context, taskID string) (repository.ChetterSessionRun, error) {
	value, err := q.postgres.GetSessionRunByTaskID(ctx, convert[string](taskID))
	return convert[repository.ChetterSessionRun](value), err
}

func (q *Queries) GetTaskByID(ctx context.Context, id string) (repository.ChetterTask, error) {
	value, err := q.postgres.GetTaskByID(ctx, convert[string](id))
	return convert[repository.ChetterTask](value), err
}

func (q *Queries) GetTeamByID(ctx context.Context, id string) (repository.Team, error) {
	value, err := q.postgres.GetTeamByID(ctx, convert[string](id))
	return convert[repository.Team](value), err
}

func (q *Queries) GetTeamByName(ctx context.Context, name string) (repository.Team, error) {
	value, err := q.postgres.GetTeamByName(ctx, convert[string](name))
	return convert[repository.Team](value), err
}

func (q *Queries) GetTokenByHash(ctx context.Context, tokenHash string) (repository.GetTokenByHashRow, error) {
	value, err := q.postgres.GetTokenByHash(ctx, convert[string](tokenHash))
	return convert[repository.GetTokenByHashRow](value), err
}

func (q *Queries) GetTriggerByID(ctx context.Context, id string) (repository.ChetterTrigger, error) {
	value, err := q.postgres.GetTriggerByID(ctx, convert[string](id))
	return convert[repository.ChetterTrigger](value), err
}

func (q *Queries) GetTriggerByName(ctx context.Context, name string) (repository.ChetterTrigger, error) {
	value, err := q.postgres.GetTriggerByName(ctx, convert[string](name))
	return convert[repository.ChetterTrigger](value), err
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (repository.User, error) {
	value, err := q.postgres.GetUserByID(ctx, convert[string](id))
	return convert[repository.User](value), err
}

func (q *Queries) InsertAgentSession(ctx context.Context, arg repository.InsertAgentSessionParams) error {
	return q.postgres.InsertAgentSession(ctx, convert[repositorypostgres.InsertAgentSessionParams](arg))
}

func (q *Queries) InsertAgentSessionCheckpoint(ctx context.Context, arg repository.InsertAgentSessionCheckpointParams) error {
	return q.postgres.InsertAgentSessionCheckpoint(ctx, convert[repositorypostgres.InsertAgentSessionCheckpointParams](arg))
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg repository.InsertAuditLogParams) error {
	return q.postgres.InsertAuditLog(ctx, convert[repositorypostgres.InsertAuditLogParams](arg))
}

func (q *Queries) InsertDefinitionChangeProposal(ctx context.Context, arg repository.InsertDefinitionChangeProposalParams) error {
	return q.postgres.InsertDefinitionChangeProposal(ctx, convert[repositorypostgres.InsertDefinitionChangeProposalParams](arg))
}

func (q *Queries) InsertDefinitionSyncRun(ctx context.Context, arg repository.InsertDefinitionSyncRunParams) error {
	return q.postgres.InsertDefinitionSyncRun(ctx, convert[repositorypostgres.InsertDefinitionSyncRunParams](arg))
}

func (q *Queries) InsertEventCallback(ctx context.Context, arg repository.InsertEventCallbackParams) error {
	return q.postgres.InsertEventCallback(ctx, convert[repositorypostgres.InsertEventCallbackParams](arg))
}

func (q *Queries) InsertModelCatalog(ctx context.Context, arg repository.InsertModelCatalogParams) error {
	return q.postgres.InsertModelCatalog(ctx, convert[repositorypostgres.InsertModelCatalogParams](arg))
}

func (q *Queries) InsertSessionRun(ctx context.Context, arg repository.InsertSessionRunParams) error {
	return q.postgres.InsertSessionRun(ctx, convert[repositorypostgres.InsertSessionRunParams](arg))
}

func (q *Queries) InsertTask(ctx context.Context, arg repository.InsertTaskParams) error {
	return q.postgres.InsertTask(ctx, convert[repositorypostgres.InsertTaskParams](arg))
}

func (q *Queries) InsertTaskArtifact(ctx context.Context, arg repository.InsertTaskArtifactParams) error {
	return q.postgres.InsertTaskArtifact(ctx, convert[repositorypostgres.InsertTaskArtifactParams](arg))
}

func (q *Queries) InsertTaskEvent(ctx context.Context, arg repository.InsertTaskEventParams) error {
	return q.postgres.InsertTaskEvent(ctx, convert[repositorypostgres.InsertTaskEventParams](arg))
}

func (q *Queries) InsertTriggerRun(ctx context.Context, arg repository.InsertTriggerRunParams) error {
	return q.postgres.InsertTriggerRun(ctx, convert[repositorypostgres.InsertTriggerRunParams](arg))
}

func (q *Queries) IsRunnerAlive(ctx context.Context, arg repository.IsRunnerAliveParams) (bool, error) {
	value, err := q.postgres.IsRunnerAlive(ctx, convert[repositorypostgres.IsRunnerAliveParams](arg))
	return convert[bool](value), err
}

func (q *Queries) ListAgentSessions(ctx context.Context, arg repository.ListAgentSessionsParams) ([]repository.ChetterAgentSession, error) {
	value, err := q.postgres.ListAgentSessions(ctx, convert[repositorypostgres.ListAgentSessionsParams](arg))
	return convert[[]repository.ChetterAgentSession](value), err
}

func (q *Queries) ListAgentSessionsByTeams(ctx context.Context, arg repository.ListAgentSessionsByTeamsParams) ([]repository.ChetterAgentSession, error) {
	value, err := q.postgres.ListAgentSessionsByTeams(ctx, convert[repositorypostgres.ListAgentSessionsByTeamsParams](arg))
	return convert[[]repository.ChetterAgentSession](value), err
}

func (q *Queries) ListDefinitionChangeProposals(ctx context.Context, arg repository.ListDefinitionChangeProposalsParams) ([]repository.DefinitionChangeProposal, error) {
	value, err := q.postgres.ListDefinitionChangeProposals(ctx, convert[repositorypostgres.ListDefinitionChangeProposalsParams](arg))
	return convert[[]repository.DefinitionChangeProposal](value), err
}

func (q *Queries) ListDefinitionSources(ctx context.Context) ([]repository.DefinitionSource, error) {
	value, err := q.postgres.ListDefinitionSources(ctx)
	return convert[[]repository.DefinitionSource](value), err
}

func (q *Queries) ListDefinitionSyncRuns(ctx context.Context, arg repository.ListDefinitionSyncRunsParams) ([]repository.DefinitionSyncRun, error) {
	value, err := q.postgres.ListDefinitionSyncRuns(ctx, convert[repositorypostgres.ListDefinitionSyncRunsParams](arg))
	return convert[[]repository.DefinitionSyncRun](value), err
}

func (q *Queries) ListDefinitions(ctx context.Context, arg repository.ListDefinitionsParams) ([]repository.Definition, error) {
	value, err := q.postgres.ListDefinitions(ctx, convert[repositorypostgres.ListDefinitionsParams](arg))
	return convert[[]repository.Definition](value), err
}

func (q *Queries) ListEnabledEventCallbacksForEvent(ctx context.Context, arg repository.ListEnabledEventCallbacksForEventParams) ([]repository.ChetterEventCallback, error) {
	value, err := q.postgres.ListEnabledEventCallbacksForEvent(ctx, convert[repositorypostgres.ListEnabledEventCallbacksForEventParams](arg))
	return convert[[]repository.ChetterEventCallback](value), err
}

func (q *Queries) ListEnabledIssueTriggersByRepo(ctx context.Context, repo json.RawMessage) ([]repository.ChetterTrigger, error) {
	value, err := q.postgres.ListEnabledIssueTriggersByRepo(ctx, convert[json.RawMessage](repo))
	return convert[[]repository.ChetterTrigger](value), err
}

func (q *Queries) ListEnabledPRReviewTriggersByRepo(ctx context.Context, repo json.RawMessage) ([]repository.ChetterTrigger, error) {
	value, err := q.postgres.ListEnabledPRReviewTriggersByRepo(ctx, convert[json.RawMessage](repo))
	return convert[[]repository.ChetterTrigger](value), err
}

func (q *Queries) ListEnabledTriggers(ctx context.Context) ([]repository.ChetterTrigger, error) {
	value, err := q.postgres.ListEnabledTriggers(ctx)
	return convert[[]repository.ChetterTrigger](value), err
}

func (q *Queries) ListEnabledTriggersByTeam(ctx context.Context, teamID sql.NullString) ([]repository.ChetterTrigger, error) {
	value, err := q.postgres.ListEnabledTriggersByTeam(ctx, convert[sql.NullString](teamID))
	return convert[[]repository.ChetterTrigger](value), err
}

func (q *Queries) ListEnabledTriggersByTeams(ctx context.Context, teamIds []sql.NullString) ([]repository.ChetterTrigger, error) {
	value, err := q.postgres.ListEnabledTriggersByTeams(ctx, convert[[]string](teamIds))
	return convert[[]repository.ChetterTrigger](value), err
}

func (q *Queries) ListEnabledTriggersByType(ctx context.Context, triggerType string) ([]repository.ChetterTrigger, error) {
	value, err := q.postgres.ListEnabledTriggersByType(ctx, convert[string](triggerType))
	return convert[[]repository.ChetterTrigger](value), err
}

func (q *Queries) ListEventCallbacks(ctx context.Context, arg repository.ListEventCallbacksParams) ([]repository.ChetterEventCallback, error) {
	value, err := q.postgres.ListEventCallbacks(ctx, convert[repositorypostgres.ListEventCallbacksParams](arg))
	return convert[[]repository.ChetterEventCallback](value), err
}

func (q *Queries) ListEventCallbacksByTeams(ctx context.Context, arg repository.ListEventCallbacksByTeamsParams) ([]repository.ChetterEventCallback, error) {
	value, err := q.postgres.ListEventCallbacksByTeams(ctx, convert[repositorypostgres.ListEventCallbacksByTeamsParams](arg))
	return convert[[]repository.ChetterEventCallback](value), err
}

func (q *Queries) ListHeartbeatTasks(ctx context.Context, arg repository.ListHeartbeatTasksParams) ([]repository.ListHeartbeatTasksRow, error) {
	value, err := q.postgres.ListHeartbeatTasks(ctx, convert[repositorypostgres.ListHeartbeatTasksParams](arg))
	return convert[[]repository.ListHeartbeatTasksRow](value), err
}

func (q *Queries) ListLiveRunners(ctx context.Context, lastSeenAt time.Time) ([]repository.ChetterRunner, error) {
	value, err := q.postgres.ListLiveRunners(ctx, convert[time.Time](lastSeenAt))
	return convert[[]repository.ChetterRunner](value), err
}

func (q *Queries) ListModelCatalogs(ctx context.Context) ([]repository.ChetterModelCatalog, error) {
	value, err := q.postgres.ListModelCatalogs(ctx)
	return convert[[]repository.ChetterModelCatalog](value), err
}

func (q *Queries) ListSessionRunsBySession(ctx context.Context, agentSessionID string) ([]repository.ChetterSessionRun, error) {
	value, err := q.postgres.ListSessionRunsBySession(ctx, convert[string](agentSessionID))
	return convert[[]repository.ChetterSessionRun](value), err
}

func (q *Queries) ListTaskEvents(ctx context.Context, arg repository.ListTaskEventsParams) ([]repository.ChetterTaskEvent, error) {
	value, err := q.postgres.ListTaskEvents(ctx, convert[repositorypostgres.ListTaskEventsParams](arg))
	return convert[[]repository.ChetterTaskEvent](value), err
}

func (q *Queries) ListTaskEventsSince(ctx context.Context, arg repository.ListTaskEventsSinceParams) ([]repository.ChetterTaskEvent, error) {
	value, err := q.postgres.ListTaskEventsSince(ctx, convert[repositorypostgres.ListTaskEventsSinceParams](arg))
	return convert[[]repository.ChetterTaskEvent](value), err
}

func (q *Queries) ListTasksByStatus(ctx context.Context, arg repository.ListTasksByStatusParams) ([]repository.ChetterTask, error) {
	value, err := q.postgres.ListTasksByStatus(ctx, convert[repositorypostgres.ListTasksByStatusParams](arg))
	return convert[[]repository.ChetterTask](value), err
}

func (q *Queries) ListTasksByStatusAndTeam(ctx context.Context, arg repository.ListTasksByStatusAndTeamParams) ([]repository.ChetterTask, error) {
	value, err := q.postgres.ListTasksByStatusAndTeam(ctx, convert[repositorypostgres.ListTasksByStatusAndTeamParams](arg))
	return convert[[]repository.ChetterTask](value), err
}

func (q *Queries) ListTasksByStatusAndTeams(ctx context.Context, arg repository.ListTasksByStatusAndTeamsParams) ([]repository.ChetterTask, error) {
	value, err := q.postgres.ListTasksByStatusAndTeams(ctx, convert[repositorypostgres.ListTasksByStatusAndTeamsParams](arg))
	return convert[[]repository.ChetterTask](value), err
}

func (q *Queries) ListTeams(ctx context.Context) ([]repository.Team, error) {
	value, err := q.postgres.ListTeams(ctx)
	return convert[[]repository.Team](value), err
}

func (q *Queries) ListTokens(ctx context.Context) ([]repository.ListTokensRow, error) {
	value, err := q.postgres.ListTokens(ctx)
	return convert[[]repository.ListTokensRow](value), err
}

func (q *Queries) ListTriggerRunsByTeam(ctx context.Context, arg repository.ListTriggerRunsByTeamParams) ([]repository.ListTriggerRunsByTeamRow, error) {
	value, err := q.postgres.ListTriggerRunsByTeam(ctx, convert[repositorypostgres.ListTriggerRunsByTeamParams](arg))
	return convert[[]repository.ListTriggerRunsByTeamRow](value), err
}

func (q *Queries) ListTriggerRunsByTeams(ctx context.Context, arg repository.ListTriggerRunsByTeamsParams) ([]repository.ListTriggerRunsByTeamsRow, error) {
	value, err := q.postgres.ListTriggerRunsByTeams(ctx, convert[repositorypostgres.ListTriggerRunsByTeamsParams](arg))
	return convert[[]repository.ListTriggerRunsByTeamsRow](value), err
}

func (q *Queries) ListTriggerRunsByTrigger(ctx context.Context, arg repository.ListTriggerRunsByTriggerParams) ([]repository.ListTriggerRunsByTriggerRow, error) {
	value, err := q.postgres.ListTriggerRunsByTrigger(ctx, convert[repositorypostgres.ListTriggerRunsByTriggerParams](arg))
	return convert[[]repository.ListTriggerRunsByTriggerRow](value), err
}

func (q *Queries) ListTriggers(ctx context.Context) ([]repository.ChetterTrigger, error) {
	value, err := q.postgres.ListTriggers(ctx)
	return convert[[]repository.ChetterTrigger](value), err
}

func (q *Queries) ListTriggersByTeam(ctx context.Context, teamID sql.NullString) ([]repository.ChetterTrigger, error) {
	value, err := q.postgres.ListTriggersByTeam(ctx, convert[sql.NullString](teamID))
	return convert[[]repository.ChetterTrigger](value), err
}

func (q *Queries) ListTriggersByTeams(ctx context.Context, teamIds []sql.NullString) ([]repository.ChetterTrigger, error) {
	value, err := q.postgres.ListTriggersByTeams(ctx, convert[[]string](teamIds))
	return convert[[]repository.ChetterTrigger](value), err
}

func (q *Queries) ListUsers(ctx context.Context) ([]repository.ListUsersRow, error) {
	value, err := q.postgres.ListUsers(ctx)
	return convert[[]repository.ListUsersRow](value), err
}

func (q *Queries) ListUsersByTeam(ctx context.Context, teamID string) ([]repository.ListUsersByTeamRow, error) {
	value, err := q.postgres.ListUsersByTeam(ctx, convert[string](teamID))
	return convert[[]repository.ListUsersByTeamRow](value), err
}

func (q *Queries) MarkAgentSessionResuming(ctx context.Context, arg repository.MarkAgentSessionResumingParams) (int64, error) {
	value, err := q.postgres.MarkAgentSessionResuming(ctx, convert[repositorypostgres.MarkAgentSessionResumingParams](arg))
	return convert[int64](value), err
}

func (q *Queries) MarkAgentSessionTerminalByTask(ctx context.Context, arg repository.MarkAgentSessionTerminalByTaskParams) (int64, error) {
	value, err := q.postgres.MarkAgentSessionTerminalByTask(ctx, convert[repositorypostgres.MarkAgentSessionTerminalByTaskParams](arg))
	return convert[int64](value), err
}

func (q *Queries) MarkDefinitionSourceSynced(ctx context.Context, arg repository.MarkDefinitionSourceSyncedParams) error {
	return q.postgres.MarkDefinitionSourceSynced(ctx, convert[repositorypostgres.MarkDefinitionSourceSyncedParams](arg))
}

func (q *Queries) MarkResumingSessionsFailedForUnavailableRunner(ctx context.Context, updatedAt time.Time) (int64, error) {
	value, err := q.postgres.MarkResumingSessionsFailedForUnavailableRunner(ctx, convert[time.Time](updatedAt))
	return convert[int64](value), err
}

func (q *Queries) MarkSessionRunRunningByTask(ctx context.Context, arg repository.MarkSessionRunRunningByTaskParams) (int64, error) {
	value, err := q.postgres.MarkSessionRunRunningByTask(ctx, convert[repositorypostgres.MarkSessionRunRunningByTaskParams](arg))
	return convert[int64](value), err
}

func (q *Queries) MarkSessionRunTerminalByTask(ctx context.Context, arg repository.MarkSessionRunTerminalByTaskParams) (int64, error) {
	value, err := q.postgres.MarkSessionRunTerminalByTask(ctx, convert[repositorypostgres.MarkSessionRunTerminalByTaskParams](arg))
	return convert[int64](value), err
}

func (q *Queries) MarkTaskClaimed(ctx context.Context, arg repository.MarkTaskClaimedParams) (int64, error) {
	value, err := q.postgres.MarkTaskClaimed(ctx, convert[repositorypostgres.MarkTaskClaimedParams](arg))
	return convert[int64](value), err
}

func (q *Queries) PauseAgentSessionByTaskID(ctx context.Context, arg repository.PauseAgentSessionByTaskIDParams) (int64, error) {
	value, err := q.postgres.PauseAgentSessionByTaskID(ctx, convert[repositorypostgres.PauseAgentSessionByTaskIDParams](arg))
	return convert[int64](value), err
}

func (q *Queries) ReapStaleSessionRuns(ctx context.Context) (int64, error) {
	value, err := q.postgres.ReapStaleSessionRuns(ctx)
	return convert[int64](value), err
}

func (q *Queries) ReapStaleSessionsForTerminalRuns(ctx context.Context) (int64, error) {
	value, err := q.postgres.ReapStaleSessionsForTerminalRuns(ctx)
	return convert[int64](value), err
}

func (q *Queries) ReclaimExpiredLeases(ctx context.Context, arg repository.ReclaimExpiredLeasesParams) (int64, error) {
	value, err := q.postgres.ReclaimExpiredLeases(ctx, convert[repositorypostgres.ReclaimExpiredLeasesParams](arg))
	return convert[int64](value), err
}

func (q *Queries) RenewRunningTaskLeases(ctx context.Context, arg repository.RenewRunningTaskLeasesParams) (int64, error) {
	value, err := q.postgres.RenewRunningTaskLeases(ctx, convert[repositorypostgres.RenewRunningTaskLeasesParams](arg))
	return convert[int64](value), err
}

func (q *Queries) RenewTaskLease(ctx context.Context, arg repository.RenewTaskLeaseParams) (int64, error) {
	value, err := q.postgres.RenewTaskLease(ctx, convert[repositorypostgres.RenewTaskLeaseParams](arg))
	return convert[int64](value), err
}

func (q *Queries) RevertOrphanedRunningSessionRuns(ctx context.Context) (int64, error) {
	value, err := q.postgres.RevertOrphanedRunningSessionRuns(ctx)
	return convert[int64](value), err
}

func (q *Queries) SearchAgentSessions(ctx context.Context, arg repository.SearchAgentSessionsParams) ([]repository.ChetterAgentSession, error) {
	value, err := q.postgres.SearchAgentSessions(ctx, convert[repositorypostgres.SearchAgentSessionsParams](arg))
	return convert[[]repository.ChetterAgentSession](value), err
}

func (q *Queries) SearchAgentSessionsByTeams(ctx context.Context, arg repository.SearchAgentSessionsByTeamsParams) ([]repository.ChetterAgentSession, error) {
	value, err := q.postgres.SearchAgentSessionsByTeams(ctx, convert[repositorypostgres.SearchAgentSessionsByTeamsParams](arg))
	return convert[[]repository.ChetterAgentSession](value), err
}

func (q *Queries) SearchAuditLog(ctx context.Context, arg repository.SearchAuditLogParams) ([]repository.SearchAuditLogRow, error) {
	value, err := q.postgres.SearchAuditLog(ctx, convert[repositorypostgres.SearchAuditLogParams](arg))
	return convert[[]repository.SearchAuditLogRow](value), err
}

func (q *Queries) SearchTaskArtifacts(ctx context.Context, arg repository.SearchTaskArtifactsParams) ([]repository.SearchTaskArtifactsRow, error) {
	value, err := q.postgres.SearchTaskArtifacts(ctx, convert[repositorypostgres.SearchTaskArtifactsParams](arg))
	return convert[[]repository.SearchTaskArtifactsRow](value), err
}

func (q *Queries) SearchTasksByTeams(ctx context.Context, arg repository.SearchTasksByTeamsParams) ([]repository.ChetterTask, error) {
	value, err := q.postgres.SearchTasksByTeams(ctx, convert[repositorypostgres.SearchTasksByTeamsParams](arg))
	return convert[[]repository.ChetterTask](value), err
}

func (q *Queries) SetTriggerLastRun(ctx context.Context, arg repository.SetTriggerLastRunParams) error {
	return q.postgres.SetTriggerLastRun(ctx, convert[repositorypostgres.SetTriggerLastRunParams](arg))
}

func (q *Queries) SetTriggerNextRun(ctx context.Context, arg repository.SetTriggerNextRunParams) error {
	return q.postgres.SetTriggerNextRun(ctx, convert[repositorypostgres.SetTriggerNextRunParams](arg))
}

func (q *Queries) UpdateDefinitionChangeProposalStatus(ctx context.Context, arg repository.UpdateDefinitionChangeProposalStatusParams) error {
	return q.postgres.UpdateDefinitionChangeProposalStatus(ctx, convert[repositorypostgres.UpdateDefinitionChangeProposalStatusParams](arg))
}

func (q *Queries) UpdateEventCallback(ctx context.Context, arg repository.UpdateEventCallbackParams) (int64, error) {
	value, err := q.postgres.UpdateEventCallback(ctx, convert[repositorypostgres.UpdateEventCallbackParams](arg))
	return convert[int64](value), err
}

func (q *Queries) UpdateTaskFromRunnerEvent(ctx context.Context, arg repository.UpdateTaskFromRunnerEventParams) (int64, error) {
	value, err := q.postgres.UpdateTaskFromRunnerEvent(ctx, convert[repositorypostgres.UpdateTaskFromRunnerEventParams](arg))
	return convert[int64](value), err
}

func (q *Queries) UpdateTaskSearchText(ctx context.Context, id string) error {
	return q.postgres.UpdateTaskSearchText(ctx, convert[string](id))
}

func (q *Queries) UpdateTrigger(ctx context.Context, arg repository.UpdateTriggerParams) error {
	return q.postgres.UpdateTrigger(ctx, convert[repositorypostgres.UpdateTriggerParams](arg))
}

func (q *Queries) UpsertDefinition(ctx context.Context, arg repository.UpsertDefinitionParams) error {
	return q.postgres.UpsertDefinition(ctx, convert[repositorypostgres.UpsertDefinitionParams](arg))
}

func (q *Queries) UpsertDefinitionSource(ctx context.Context, arg repository.UpsertDefinitionSourceParams) error {
	return q.postgres.UpsertDefinitionSource(ctx, convert[repositorypostgres.UpsertDefinitionSourceParams](arg))
}

func (q *Queries) UpsertRunnerHeartbeat(ctx context.Context, arg repository.UpsertRunnerHeartbeatParams) error {
	return q.postgres.UpsertRunnerHeartbeat(ctx, convert[repositorypostgres.UpsertRunnerHeartbeatParams](arg))
}

func (q *Queries) UpsertTrigger(ctx context.Context, arg repository.UpsertTriggerParams) error {
	return q.postgres.UpsertTrigger(ctx, convert[repositorypostgres.UpsertTriggerParams](arg))
}
