// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_sessions.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const expirePausedSessions = `-- name: ExpirePausedSessions :execrows
UPDATE chetter_agent_sessions
SET status = 'expired',
    updated_at = ?
WHERE status IN ('paused', 'recoverable', 'paused_waiting_review')
  AND expires_at IS NOT NULL
  AND expires_at < ?
`

type ExpirePausedSessionsParams struct {
	UpdatedAt time.Time    `json:"updated_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) ExpirePausedSessions(ctx context.Context, arg ExpirePausedSessionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expirePausedSessions, arg.UpdatedAt, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failPendingResumeTasksForMissingRunner = `-- name: FailPendingResumeTasksForMissingRunner :execrows
UPDATE chetter_tasks t
LEFT JOIN chetter_runners r ON r.id = t.required_runner_id
SET t.status = 'error',
    t.error = CONCAT('pinned runner ', t.required_runner_id, ' is not alive'),
    t.error_category = 'runner_unavailable',
    t.ended_at = ?,
    t.updated_at = ?,
    t.last_event_at = ?
WHERE t.status = 'pending'
  AND t.required_runner_id IS NOT NULL
  AND t.required_runner_id <> ''
  AND (
    r.id IS NULL
    OR r.status <> 'active'
    OR r.last_seen_at <= DATE_SUB(NOW(), INTERVAL ? SECOND)
  )
  AND EXISTS (
    SELECT 1
    FROM chetter_session_runs sr
    JOIN chetter_agent_sessions s ON s.id = sr.agent_session_id
    WHERE sr.task_id = t.id
      AND sr.status = 'pending'
      AND s.status = 'resuming'
  )
`

type FailPendingResumeTasksForMissingRunnerParams struct {
	EndedAt      sql.NullTime `json:"ended_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	LastEventAt  sql.NullTime `json:"last_event_at"`
	StaleSeconds interface{}  `json:"stale_seconds"`
}

func (q *Queries) FailPendingResumeTasksForMissingRunner(ctx context.Context, arg FailPendingResumeTasksForMissingRunnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failPendingResumeTasksForMissingRunner,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.LastEventAt,
		arg.StaleSeconds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failPendingSessionRunsForUnavailableRunner = `-- name: FailPendingSessionRunsForUnavailableRunner :execrows
UPDATE chetter_session_runs sr
JOIN chetter_tasks t ON t.id = sr.task_id
SET sr.status = 'failed',
    sr.error = t.error,
    sr.ended_at = COALESCE(sr.ended_at, ?),
    sr.updated_at = ?
WHERE sr.status = 'pending'
  AND t.status = 'error'
  AND t.error_category = 'runner_unavailable'
`

type FailPendingSessionRunsForUnavailableRunnerParams struct {
	EndedAt   sql.NullTime `json:"ended_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

func (q *Queries) FailPendingSessionRunsForUnavailableRunner(ctx context.Context, arg FailPendingSessionRunsForUnavailableRunnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failPendingSessionRunsForUnavailableRunner, arg.EndedAt, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgentSessionByID = `-- name: GetAgentSessionByID :one
SELECT id, team_id, status, resume_mode, pinned_runner_id, pinned_runner_name, checkpoint_id, workspace_path, container_name, harness_session_id, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, created_at, updated_at, paused_at, expires_at, pause_reason, error FROM chetter_agent_sessions
WHERE id = ?
`

func (q *Queries) GetAgentSessionByID(ctx context.Context, id string) (ChetterAgentSession, error) {
	row := q.db.QueryRowContext(ctx, getAgentSessionByID, id)
	var i ChetterAgentSession
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Status,
		&i.ResumeMode,
		&i.PinnedRunnerID,
		&i.PinnedRunnerName,
		&i.CheckpointID,
		&i.WorkspacePath,
		&i.ContainerName,
		&i.HarnessSessionID,
		&i.GitUrl,
		&i.GitRef,
		&i.AgentImage,
		&i.Agent,
		&i.ProviderID,
		&i.ModelID,
		&i.VariantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
		&i.ExpiresAt,
		&i.PauseReason,
		&i.Error,
	)
	return i, err
}

const getAgentSessionByTaskID = `-- name: GetAgentSessionByTaskID :one
SELECT id, team_id, status, resume_mode, pinned_runner_id, pinned_runner_name, checkpoint_id, workspace_path, container_name, harness_session_id, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, created_at, updated_at, paused_at, expires_at, pause_reason, error FROM chetter_agent_sessions
WHERE id = (
    SELECT agent_session_id
    FROM chetter_session_runs
    WHERE task_id = ?
    LIMIT 1
)
`

func (q *Queries) GetAgentSessionByTaskID(ctx context.Context, taskID string) (ChetterAgentSession, error) {
	row := q.db.QueryRowContext(ctx, getAgentSessionByTaskID, taskID)
	var i ChetterAgentSession
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Status,
		&i.ResumeMode,
		&i.PinnedRunnerID,
		&i.PinnedRunnerName,
		&i.CheckpointID,
		&i.WorkspacePath,
		&i.ContainerName,
		&i.HarnessSessionID,
		&i.GitUrl,
		&i.GitRef,
		&i.AgentImage,
		&i.Agent,
		&i.ProviderID,
		&i.ModelID,
		&i.VariantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
		&i.ExpiresAt,
		&i.PauseReason,
		&i.Error,
	)
	return i, err
}

const getLatestAgentSessionCheckpoint = `-- name: GetLatestAgentSessionCheckpoint :one
SELECT id, agent_session_id, session_run_id, runner_id, checkpoint_path, workspace_path, container_name, runsc_version, agent_image, size_bytes, status, error, created_at, updated_at, expires_at FROM chetter_agent_session_checkpoints
WHERE agent_session_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAgentSessionCheckpoint(ctx context.Context, agentSessionID string) (ChetterAgentSessionCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, getLatestAgentSessionCheckpoint, agentSessionID)
	var i ChetterAgentSessionCheckpoint
	err := row.Scan(
		&i.ID,
		&i.AgentSessionID,
		&i.SessionRunID,
		&i.RunnerID,
		&i.CheckpointPath,
		&i.WorkspacePath,
		&i.ContainerName,
		&i.RunscVersion,
		&i.AgentImage,
		&i.SizeBytes,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getLatestAgentSessionCheckpointByTaskID = `-- name: GetLatestAgentSessionCheckpointByTaskID :one
SELECT chk.id, chk.agent_session_id, chk.session_run_id, chk.runner_id, chk.checkpoint_path, chk.workspace_path, chk.container_name, chk.runsc_version, chk.agent_image, chk.size_bytes, chk.status, chk.error, chk.created_at, chk.updated_at, chk.expires_at FROM chetter_agent_session_checkpoints chk
JOIN chetter_session_runs r ON r.agent_session_id = chk.agent_session_id
WHERE r.task_id = ?
ORDER BY chk.created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAgentSessionCheckpointByTaskID(ctx context.Context, taskID string) (ChetterAgentSessionCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, getLatestAgentSessionCheckpointByTaskID, taskID)
	var i ChetterAgentSessionCheckpoint
	err := row.Scan(
		&i.ID,
		&i.AgentSessionID,
		&i.SessionRunID,
		&i.RunnerID,
		&i.CheckpointPath,
		&i.WorkspacePath,
		&i.ContainerName,
		&i.RunscVersion,
		&i.AgentImage,
		&i.SizeBytes,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPausedSessionByArtifact = `-- name: GetPausedSessionByArtifact :one
SELECT s.id, s.team_id, s.status, s.resume_mode, s.pinned_runner_id, s.pinned_runner_name, s.checkpoint_id, s.workspace_path, s.container_name, s.harness_session_id, s.git_url, s.git_ref, s.agent_image, s.agent, s.provider_id, s.model_id, s.variant_id, s.created_at, s.updated_at, s.paused_at, s.expires_at, s.pause_reason, s.error FROM chetter_agent_sessions s
JOIN chetter_task_artifacts a ON a.agent_session_id = s.id
WHERE a.repo = ?
  AND a.number = ?
  AND a.artifact_type = ?
  AND s.status IN ('paused', 'recoverable', 'paused_waiting_review')
  AND s.resume_mode IN ('gvisor_checkpoint', 'harness_session')
ORDER BY a.discovered_at DESC
LIMIT 1
`

type GetPausedSessionByArtifactParams struct {
	Repo         string        `json:"repo"`
	Number       sql.NullInt32 `json:"number"`
	ArtifactType string        `json:"artifact_type"`
}

func (q *Queries) GetPausedSessionByArtifact(ctx context.Context, arg GetPausedSessionByArtifactParams) (ChetterAgentSession, error) {
	row := q.db.QueryRowContext(ctx, getPausedSessionByArtifact, arg.Repo, arg.Number, arg.ArtifactType)
	var i ChetterAgentSession
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Status,
		&i.ResumeMode,
		&i.PinnedRunnerID,
		&i.PinnedRunnerName,
		&i.CheckpointID,
		&i.WorkspacePath,
		&i.ContainerName,
		&i.HarnessSessionID,
		&i.GitUrl,
		&i.GitRef,
		&i.AgentImage,
		&i.Agent,
		&i.ProviderID,
		&i.ModelID,
		&i.VariantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
		&i.ExpiresAt,
		&i.PauseReason,
		&i.Error,
	)
	return i, err
}

const getSessionRunByTaskID = `-- name: GetSessionRunByTaskID :one
SELECT id, agent_session_id, task_id, status, prompt, required_runner_id, summary, error, session_export, created_at, updated_at, started_at, ended_at FROM chetter_session_runs
WHERE task_id = ?
`

func (q *Queries) GetSessionRunByTaskID(ctx context.Context, taskID string) (ChetterSessionRun, error) {
	row := q.db.QueryRowContext(ctx, getSessionRunByTaskID, taskID)
	var i ChetterSessionRun
	err := row.Scan(
		&i.ID,
		&i.AgentSessionID,
		&i.TaskID,
		&i.Status,
		&i.Prompt,
		&i.RequiredRunnerID,
		&i.Summary,
		&i.Error,
		&i.SessionExport,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const insertAgentSession = `-- name: InsertAgentSession :exec
INSERT INTO chetter_agent_sessions
    (id, team_id, status, resume_mode, pause_reason, expires_at, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAgentSessionParams struct {
	ID          string         `json:"id"`
	TeamID      sql.NullString `json:"team_id"`
	Status      string         `json:"status"`
	ResumeMode  string         `json:"resume_mode"`
	PauseReason sql.NullString `json:"pause_reason"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
	GitUrl      sql.NullString `json:"git_url"`
	GitRef      sql.NullString `json:"git_ref"`
	AgentImage  sql.NullString `json:"agent_image"`
	Agent       sql.NullString `json:"agent"`
	ProviderID  sql.NullString `json:"provider_id"`
	ModelID     sql.NullString `json:"model_id"`
	VariantID   sql.NullString `json:"variant_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) InsertAgentSession(ctx context.Context, arg InsertAgentSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentSession,
		arg.ID,
		arg.TeamID,
		arg.Status,
		arg.ResumeMode,
		arg.PauseReason,
		arg.ExpiresAt,
		arg.GitUrl,
		arg.GitRef,
		arg.AgentImage,
		arg.Agent,
		arg.ProviderID,
		arg.ModelID,
		arg.VariantID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertAgentSessionCheckpoint = `-- name: InsertAgentSessionCheckpoint :exec
INSERT INTO chetter_agent_session_checkpoints
    (id, agent_session_id, session_run_id, runner_id, checkpoint_path, workspace_path, container_name, runsc_version, agent_image, size_bytes, status, error, created_at, updated_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAgentSessionCheckpointParams struct {
	ID             string         `json:"id"`
	AgentSessionID string         `json:"agent_session_id"`
	SessionRunID   sql.NullString `json:"session_run_id"`
	RunnerID       string         `json:"runner_id"`
	CheckpointPath string         `json:"checkpoint_path"`
	WorkspacePath  string         `json:"workspace_path"`
	ContainerName  sql.NullString `json:"container_name"`
	RunscVersion   sql.NullString `json:"runsc_version"`
	AgentImage     sql.NullString `json:"agent_image"`
	SizeBytes      int64          `json:"size_bytes"`
	Status         string         `json:"status"`
	Error          sql.NullString `json:"error"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ExpiresAt      sql.NullTime   `json:"expires_at"`
}

func (q *Queries) InsertAgentSessionCheckpoint(ctx context.Context, arg InsertAgentSessionCheckpointParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentSessionCheckpoint,
		arg.ID,
		arg.AgentSessionID,
		arg.SessionRunID,
		arg.RunnerID,
		arg.CheckpointPath,
		arg.WorkspacePath,
		arg.ContainerName,
		arg.RunscVersion,
		arg.AgentImage,
		arg.SizeBytes,
		arg.Status,
		arg.Error,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertSessionRun = `-- name: InsertSessionRun :exec
INSERT INTO chetter_session_runs
    (id, agent_session_id, task_id, status, prompt, required_runner_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSessionRunParams struct {
	ID               string         `json:"id"`
	AgentSessionID   string         `json:"agent_session_id"`
	TaskID           string         `json:"task_id"`
	Status           string         `json:"status"`
	Prompt           string         `json:"prompt"`
	RequiredRunnerID sql.NullString `json:"required_runner_id"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

func (q *Queries) InsertSessionRun(ctx context.Context, arg InsertSessionRunParams) error {
	_, err := q.db.ExecContext(ctx, insertSessionRun,
		arg.ID,
		arg.AgentSessionID,
		arg.TaskID,
		arg.Status,
		arg.Prompt,
		arg.RequiredRunnerID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const isRunnerAlive = `-- name: IsRunnerAlive :one
SELECT COUNT(*) > 0 FROM chetter_runners
WHERE id = ?
  AND status = 'active'
  AND last_seen_at > DATE_SUB(NOW(), INTERVAL ? SECOND)
`

type IsRunnerAliveParams struct {
	RunnerID     string      `json:"runner_id"`
	StaleSeconds interface{} `json:"stale_seconds"`
}

func (q *Queries) IsRunnerAlive(ctx context.Context, arg IsRunnerAliveParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isRunnerAlive, arg.RunnerID, arg.StaleSeconds)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listAgentSessions = `-- name: ListAgentSessions :many
SELECT id, team_id, status, resume_mode, pinned_runner_id, pinned_runner_name, checkpoint_id, workspace_path, container_name, harness_session_id, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, created_at, updated_at, paused_at, expires_at, pause_reason, error FROM chetter_agent_sessions
WHERE (? = '' OR COALESCE(team_id, '') = ?)
  AND (? = '' OR status = ?)
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type ListAgentSessionsParams struct {
	TeamFilter   sql.NullString `json:"team_filter"`
	StatusFilter string         `json:"status_filter"`
	Limit        int32          `json:"limit"`
	Offset       int32          `json:"offset"`
}

func (q *Queries) ListAgentSessions(ctx context.Context, arg ListAgentSessionsParams) ([]ChetterAgentSession, error) {
	rows, err := q.db.QueryContext(ctx, listAgentSessions,
		arg.TeamFilter,
		arg.TeamFilter,
		arg.StatusFilter,
		arg.StatusFilter,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterAgentSession{}
	for rows.Next() {
		var i ChetterAgentSession
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Status,
			&i.ResumeMode,
			&i.PinnedRunnerID,
			&i.PinnedRunnerName,
			&i.CheckpointID,
			&i.WorkspacePath,
			&i.ContainerName,
			&i.HarnessSessionID,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
			&i.ExpiresAt,
			&i.PauseReason,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionRunsBySession = `-- name: ListSessionRunsBySession :many
SELECT id, agent_session_id, task_id, status, prompt, required_runner_id, summary, error, session_export, created_at, updated_at, started_at, ended_at FROM chetter_session_runs
WHERE agent_session_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListSessionRunsBySession(ctx context.Context, agentSessionID string) ([]ChetterSessionRun, error) {
	rows, err := q.db.QueryContext(ctx, listSessionRunsBySession, agentSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterSessionRun{}
	for rows.Next() {
		var i ChetterSessionRun
		if err := rows.Scan(
			&i.ID,
			&i.AgentSessionID,
			&i.TaskID,
			&i.Status,
			&i.Prompt,
			&i.RequiredRunnerID,
			&i.Summary,
			&i.Error,
			&i.SessionExport,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentSessionResuming = `-- name: MarkAgentSessionResuming :execrows
UPDATE chetter_agent_sessions
SET status = ?,
    updated_at = ?
WHERE id = ?
`

type MarkAgentSessionResumingParams struct {
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) MarkAgentSessionResuming(ctx context.Context, arg MarkAgentSessionResumingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAgentSessionResuming, arg.Status, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markAgentSessionTerminalByTask = `-- name: MarkAgentSessionTerminalByTask :execrows
UPDATE chetter_agent_sessions
SET status = ?,
    harness_session_id = COALESCE(NULLIF(?, ''), harness_session_id),
    error = ?,
    updated_at = ?
WHERE id = (
    SELECT agent_session_id
    FROM chetter_session_runs
    WHERE task_id = ?
    LIMIT 1
)
AND status IN ('running', 'resuming')
`

type MarkAgentSessionTerminalByTaskParams struct {
	Status           string         `json:"status"`
	HarnessSessionID interface{}    `json:"harness_session_id"`
	Error            sql.NullString `json:"error"`
	UpdatedAt        time.Time      `json:"updated_at"`
	TaskID           string         `json:"task_id"`
}

func (q *Queries) MarkAgentSessionTerminalByTask(ctx context.Context, arg MarkAgentSessionTerminalByTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAgentSessionTerminalByTask,
		arg.Status,
		arg.HarnessSessionID,
		arg.Error,
		arg.UpdatedAt,
		arg.TaskID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markResumingSessionsFailedForUnavailableRunner = `-- name: MarkResumingSessionsFailedForUnavailableRunner :execrows
UPDATE chetter_agent_sessions s
JOIN chetter_session_runs sr ON sr.agent_session_id = s.id
JOIN chetter_tasks t ON t.id = sr.task_id
SET s.status = 'error',
    s.error = COALESCE(sr.error, t.error),
    s.updated_at = ?
WHERE s.status = 'resuming'
  AND sr.status = 'failed'
  AND t.status = 'error'
  AND t.error_category = 'runner_unavailable'
`

func (q *Queries) MarkResumingSessionsFailedForUnavailableRunner(ctx context.Context, updatedAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, markResumingSessionsFailedForUnavailableRunner, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markSessionRunRunningByTask = `-- name: MarkSessionRunRunningByTask :execrows
UPDATE chetter_session_runs
SET status = 'running',
    started_at = COALESCE(started_at, ?),
    updated_at = ?
WHERE task_id = ?
  AND status IN ('pending', 'claimed')
`

type MarkSessionRunRunningByTaskParams struct {
	StartedAt sql.NullTime `json:"started_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	TaskID    string       `json:"task_id"`
}

func (q *Queries) MarkSessionRunRunningByTask(ctx context.Context, arg MarkSessionRunRunningByTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markSessionRunRunningByTask, arg.StartedAt, arg.UpdatedAt, arg.TaskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markSessionRunTerminalByTask = `-- name: MarkSessionRunTerminalByTask :execrows
UPDATE chetter_session_runs
SET status = ?,
    summary = ?,
    error = ?,
    session_export = COALESCE(?, session_export),
    started_at = COALESCE(started_at, ?),
    ended_at = COALESCE(?, ended_at),
    updated_at = ?
WHERE task_id = ?
`

type MarkSessionRunTerminalByTaskParams struct {
	Status        string         `json:"status"`
	Summary       sql.NullString `json:"summary"`
	Error         sql.NullString `json:"error"`
	SessionExport sql.NullString `json:"session_export"`
	StartedAt     sql.NullTime   `json:"started_at"`
	EndedAt       sql.NullTime   `json:"ended_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	TaskID        string         `json:"task_id"`
}

func (q *Queries) MarkSessionRunTerminalByTask(ctx context.Context, arg MarkSessionRunTerminalByTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markSessionRunTerminalByTask,
		arg.Status,
		arg.Summary,
		arg.Error,
		arg.SessionExport,
		arg.StartedAt,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.TaskID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pauseAgentSessionByTaskID = `-- name: PauseAgentSessionByTaskID :execrows
UPDATE chetter_agent_sessions
SET status = ?,
    pinned_runner_id = COALESCE(NULLIF(?, ''), pinned_runner_id),
    checkpoint_id = COALESCE(NULLIF(?, ''), checkpoint_id),
    workspace_path = COALESCE(NULLIF(?, ''), workspace_path),
    container_name = COALESCE(NULLIF(?, ''), container_name),
    harness_session_id = COALESCE(NULLIF(?, ''), harness_session_id),
    paused_at = ?,
    updated_at = ?
WHERE id = (
    SELECT agent_session_id
    FROM chetter_session_runs
    WHERE task_id = ?
    LIMIT 1
)
AND status IN ('running', 'resuming')
`

type PauseAgentSessionByTaskIDParams struct {
	Status           string       `json:"status"`
	PinnedRunnerID   interface{}  `json:"pinned_runner_id"`
	CheckpointID     interface{}  `json:"checkpoint_id"`
	WorkspacePath    interface{}  `json:"workspace_path"`
	ContainerName    interface{}  `json:"container_name"`
	HarnessSessionID interface{}  `json:"harness_session_id"`
	PausedAt         sql.NullTime `json:"paused_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
	TaskID           string       `json:"task_id"`
}

func (q *Queries) PauseAgentSessionByTaskID(ctx context.Context, arg PauseAgentSessionByTaskIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pauseAgentSessionByTaskID,
		arg.Status,
		arg.PinnedRunnerID,
		arg.CheckpointID,
		arg.WorkspacePath,
		arg.ContainerName,
		arg.HarnessSessionID,
		arg.PausedAt,
		arg.UpdatedAt,
		arg.TaskID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reapStaleSessionRuns = `-- name: ReapStaleSessionRuns :execrows
UPDATE chetter_session_runs sr
JOIN chetter_tasks t ON t.id = sr.task_id
SET sr.status = CASE
    WHEN t.status = 'done' THEN 'completed'
    WHEN t.status = 'cancelled' THEN 'cancelled'
    ELSE 'failed'
END,
sr.error = COALESCE(NULLIF(sr.error, ''), t.error, sr.error),
sr.ended_at = COALESCE(sr.ended_at, t.ended_at, NOW()),
sr.updated_at = NOW()
WHERE sr.status = 'running'
  AND t.status IN ('done', 'error', 'cancelled')
`

func (q *Queries) ReapStaleSessionRuns(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, reapStaleSessionRuns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reapStaleSessionsForTerminalRuns = `-- name: ReapStaleSessionsForTerminalRuns :execrows
UPDATE chetter_agent_sessions s
JOIN chetter_session_runs sr ON sr.agent_session_id = s.id
JOIN chetter_tasks t ON t.id = sr.task_id
SET s.status = CASE
    WHEN t.status = 'done' THEN 'completed'
    WHEN t.status = 'cancelled' THEN 'error'
    ELSE 'error'
END,
s.error = COALESCE(NULLIF(s.error, ''), t.error, s.error),
s.updated_at = NOW()
WHERE s.status = 'running'
  AND sr.status IN ('failed', 'completed', 'cancelled')
  AND t.status IN ('done', 'error', 'cancelled')
`

func (q *Queries) ReapStaleSessionsForTerminalRuns(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, reapStaleSessionsForTerminalRuns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revertOrphanedRunningSessionRuns = `-- name: RevertOrphanedRunningSessionRuns :execrows
UPDATE chetter_session_runs sr
JOIN chetter_tasks t ON t.id = sr.task_id
SET sr.status = 'pending',
    sr.started_at = NULL,
    sr.updated_at = NOW()
WHERE sr.status = 'running'
  AND t.status = 'pending'
`

func (q *Queries) RevertOrphanedRunningSessionRuns(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, revertOrphanedRunningSessionRuns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const searchAgentSessions = `-- name: SearchAgentSessions :many
SELECT id, team_id, status, resume_mode, pinned_runner_id, pinned_runner_name, checkpoint_id, workspace_path, container_name, harness_session_id, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, created_at, updated_at, paused_at, expires_at, pause_reason, error FROM chetter_agent_sessions
WHERE (? = '' OR COALESCE(team_id, '') = ?)
  AND (? = '' OR status = ?)
  AND (CONCAT(COALESCE(id, ''), '|', COALESCE(agent, ''), '|', COALESCE(model_id, ''), '|', COALESCE(git_url, '')) LIKE CONCAT('%', ?, '%'))
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type SearchAgentSessionsParams struct {
	TeamFilter   sql.NullString `json:"team_filter"`
	StatusFilter string         `json:"status_filter"`
	CONCAT       interface{}    `json:"CONCAT"`
	Limit        int32          `json:"limit"`
	Offset       int32          `json:"offset"`
}

func (q *Queries) SearchAgentSessions(ctx context.Context, arg SearchAgentSessionsParams) ([]ChetterAgentSession, error) {
	rows, err := q.db.QueryContext(ctx, searchAgentSessions,
		arg.TeamFilter,
		arg.TeamFilter,
		arg.StatusFilter,
		arg.StatusFilter,
		arg.CONCAT,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterAgentSession{}
	for rows.Next() {
		var i ChetterAgentSession
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Status,
			&i.ResumeMode,
			&i.PinnedRunnerID,
			&i.PinnedRunnerName,
			&i.CheckpointID,
			&i.WorkspacePath,
			&i.ContainerName,
			&i.HarnessSessionID,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
			&i.ExpiresAt,
			&i.PauseReason,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
