// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_sessions.sql

package repository

import (
	"context"
	"database/sql"
	"encoding/json"
	"strings"
	"time"
)

const abandonAgentSession = `-- name: AbandonAgentSession :execrows
UPDATE chetter_agent_sessions
SET status = 'abandoned', error = ?, ended_at = ?, updated_at = ?
WHERE id = ? AND status IN ('running', 'resuming')
`

type AbandonAgentSessionParams struct {
	Error     sql.NullString `json:"error"`
	EndedAt   sql.NullTime   `json:"ended_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) AbandonAgentSession(ctx context.Context, arg AbandonAgentSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, abandonAgentSession,
		arg.Error,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const abandonUserPrompt = `-- name: AbandonUserPrompt :execrows
UPDATE chetter_user_prompts
SET status = 'failed', error = ?, ended_at = ?, updated_at = ?
WHERE id = ? AND status IN ('pending', 'claimed', 'running')
`

type AbandonUserPromptParams struct {
	Error     sql.NullString `json:"error"`
	EndedAt   sql.NullTime   `json:"ended_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) AbandonUserPrompt(ctx context.Context, arg AbandonUserPromptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, abandonUserPrompt,
		arg.Error,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expirePausedSessions = `-- name: ExpirePausedSessions :execrows
UPDATE chetter_agent_sessions
SET status = 'expired',
    ended_at = ?,
    updated_at = ?
WHERE status IN ('paused', 'recoverable', 'paused_waiting_review')
  AND expires_at IS NOT NULL
  AND expires_at < ?
`

type ExpirePausedSessionsParams struct {
	EndedAt   sql.NullTime `json:"ended_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) ExpirePausedSessions(ctx context.Context, arg ExpirePausedSessionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expirePausedSessions, arg.EndedAt, arg.UpdatedAt, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failPendingResumeTasksForMissingRunner = `-- name: FailPendingResumeTasksForMissingRunner :execrows
UPDATE chetter_tasks t
JOIN chetter_user_prompts prompt ON prompt.task_id = t.id
JOIN chetter_execution_attempts attempt ON attempt.user_prompt_id = prompt.id
SET t.status = 'error',
    t.error = attempt.error,
    t.error_category = 'runner_unavailable',
    t.ended_at = ?,
    t.updated_at = ?
WHERE t.status = 'pending'
  AND attempt.status = 'error'
  AND attempt.error_category = 'runner_unavailable'
`

type FailPendingResumeTasksForMissingRunnerParams struct {
	EndedAt   sql.NullTime `json:"ended_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

func (q *Queries) FailPendingResumeTasksForMissingRunner(ctx context.Context, arg FailPendingResumeTasksForMissingRunnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failPendingResumeTasksForMissingRunner, arg.EndedAt, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failPendingUserPromptsForUnavailableRunner = `-- name: FailPendingUserPromptsForUnavailableRunner :execrows
UPDATE chetter_user_prompts sr
JOIN chetter_tasks t ON t.id = sr.task_id
SET sr.status = 'failed',
    sr.error = t.error,
    sr.ended_at = COALESCE(sr.ended_at, ?),
    sr.updated_at = ?
WHERE sr.status = 'pending'
  AND t.status = 'error'
  AND t.error_category = 'runner_unavailable'
`

type FailPendingUserPromptsForUnavailableRunnerParams struct {
	EndedAt   sql.NullTime `json:"ended_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

func (q *Queries) FailPendingUserPromptsForUnavailableRunner(ctx context.Context, arg FailPendingUserPromptsForUnavailableRunnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failPendingUserPromptsForUnavailableRunner, arg.EndedAt, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgentSessionByID = `-- name: GetAgentSessionByID :one
SELECT id, team_id, status, resume_mode, pinned_runner_id, pinned_runner_name, checkpoint_id, workspace_path, container_name, harness_session_id, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, created_at, updated_at, paused_at, expires_at, pause_reason, error, search_text, sequence, task_id, harness, mcp_endpoints, commit_author_name, commit_author_email, git_identity_id, skills, env, summary, started_at, ended_at FROM chetter_agent_sessions
WHERE id = ?
`

func (q *Queries) GetAgentSessionByID(ctx context.Context, id string) (ChetterAgentSession, error) {
	row := q.db.QueryRowContext(ctx, getAgentSessionByID, id)
	var i ChetterAgentSession
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Status,
		&i.ResumeMode,
		&i.PinnedRunnerID,
		&i.PinnedRunnerName,
		&i.CheckpointID,
		&i.WorkspacePath,
		&i.ContainerName,
		&i.HarnessSessionID,
		&i.GitUrl,
		&i.GitRef,
		&i.AgentImage,
		&i.Agent,
		&i.ProviderID,
		&i.ModelID,
		&i.VariantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
		&i.ExpiresAt,
		&i.PauseReason,
		&i.Error,
		&i.SearchText,
		&i.Sequence,
		&i.TaskID,
		&i.Harness,
		&i.McpEndpoints,
		&i.CommitAuthorName,
		&i.CommitAuthorEmail,
		&i.GitIdentityID,
		&i.Skills,
		&i.Env,
		&i.Summary,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getAgentSessionByTaskID = `-- name: GetAgentSessionByTaskID :one
SELECT id, team_id, status, resume_mode, pinned_runner_id, pinned_runner_name, checkpoint_id, workspace_path, container_name, harness_session_id, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, created_at, updated_at, paused_at, expires_at, pause_reason, error, search_text, sequence, task_id, harness, mcp_endpoints, commit_author_name, commit_author_email, git_identity_id, skills, env, summary, started_at, ended_at FROM chetter_agent_sessions
WHERE task_id = ?
ORDER BY sequence DESC
LIMIT 1
`

func (q *Queries) GetAgentSessionByTaskID(ctx context.Context, taskID string) (ChetterAgentSession, error) {
	row := q.db.QueryRowContext(ctx, getAgentSessionByTaskID, taskID)
	var i ChetterAgentSession
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Status,
		&i.ResumeMode,
		&i.PinnedRunnerID,
		&i.PinnedRunnerName,
		&i.CheckpointID,
		&i.WorkspacePath,
		&i.ContainerName,
		&i.HarnessSessionID,
		&i.GitUrl,
		&i.GitRef,
		&i.AgentImage,
		&i.Agent,
		&i.ProviderID,
		&i.ModelID,
		&i.VariantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
		&i.ExpiresAt,
		&i.PauseReason,
		&i.Error,
		&i.SearchText,
		&i.Sequence,
		&i.TaskID,
		&i.Harness,
		&i.McpEndpoints,
		&i.CommitAuthorName,
		&i.CommitAuthorEmail,
		&i.GitIdentityID,
		&i.Skills,
		&i.Env,
		&i.Summary,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getLatestAgentSessionCheckpoint = `-- name: GetLatestAgentSessionCheckpoint :one
SELECT id, agent_session_id, runner_id, checkpoint_path, workspace_path, container_name, runsc_version, agent_image, size_bytes, status, error, created_at, updated_at, expires_at, user_prompt_id FROM chetter_agent_session_checkpoints
WHERE agent_session_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAgentSessionCheckpoint(ctx context.Context, agentSessionID string) (ChetterAgentSessionCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, getLatestAgentSessionCheckpoint, agentSessionID)
	var i ChetterAgentSessionCheckpoint
	err := row.Scan(
		&i.ID,
		&i.AgentSessionID,
		&i.RunnerID,
		&i.CheckpointPath,
		&i.WorkspacePath,
		&i.ContainerName,
		&i.RunscVersion,
		&i.AgentImage,
		&i.SizeBytes,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.UserPromptID,
	)
	return i, err
}

const getLatestAgentSessionCheckpointByTaskID = `-- name: GetLatestAgentSessionCheckpointByTaskID :one
SELECT chk.id, chk.agent_session_id, chk.runner_id, chk.checkpoint_path, chk.workspace_path, chk.container_name, chk.runsc_version, chk.agent_image, chk.size_bytes, chk.status, chk.error, chk.created_at, chk.updated_at, chk.expires_at, chk.user_prompt_id FROM chetter_agent_session_checkpoints chk
JOIN chetter_user_prompts r ON r.agent_session_id = chk.agent_session_id
WHERE r.task_id = ?
ORDER BY chk.created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAgentSessionCheckpointByTaskID(ctx context.Context, taskID string) (ChetterAgentSessionCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, getLatestAgentSessionCheckpointByTaskID, taskID)
	var i ChetterAgentSessionCheckpoint
	err := row.Scan(
		&i.ID,
		&i.AgentSessionID,
		&i.RunnerID,
		&i.CheckpointPath,
		&i.WorkspacePath,
		&i.ContainerName,
		&i.RunscVersion,
		&i.AgentImage,
		&i.SizeBytes,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.UserPromptID,
	)
	return i, err
}

const getNextAgentSessionSequence = `-- name: GetNextAgentSessionSequence :one
SELECT COALESCE(MAX(sequence), 0) + 1
FROM chetter_agent_sessions
WHERE task_id = ?
`

func (q *Queries) GetNextAgentSessionSequence(ctx context.Context, taskID string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getNextAgentSessionSequence, taskID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getNextUserPromptSequence = `-- name: GetNextUserPromptSequence :one
SELECT COALESCE(MAX(sequence), 0) + 1
FROM chetter_user_prompts
WHERE agent_session_id = ?
`

func (q *Queries) GetNextUserPromptSequence(ctx context.Context, agentSessionID string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getNextUserPromptSequence, agentSessionID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getPausedSessionByArtifact = `-- name: GetPausedSessionByArtifact :one
SELECT s.id, s.team_id, s.status, s.resume_mode, s.pinned_runner_id, s.pinned_runner_name, s.checkpoint_id, s.workspace_path, s.container_name, s.harness_session_id, s.git_url, s.git_ref, s.agent_image, s.agent, s.provider_id, s.model_id, s.variant_id, s.created_at, s.updated_at, s.paused_at, s.expires_at, s.pause_reason, s.error, s.search_text, s.sequence, s.task_id, s.harness, s.mcp_endpoints, s.commit_author_name, s.commit_author_email, s.git_identity_id, s.skills, s.env, s.summary, s.started_at, s.ended_at FROM chetter_agent_sessions s
JOIN chetter_task_artifacts a ON a.agent_session_id = s.id
WHERE a.repo = ?
  AND a.number = ?
  AND a.artifact_type = ?
  AND s.status IN ('paused', 'recoverable', 'paused_waiting_review')
  AND s.resume_mode IN ('gvisor_checkpoint', 'harness_session')
ORDER BY a.discovered_at DESC
LIMIT 1
`

type GetPausedSessionByArtifactParams struct {
	Repo         string        `json:"repo"`
	Number       sql.NullInt32 `json:"number"`
	ArtifactType string        `json:"artifact_type"`
}

func (q *Queries) GetPausedSessionByArtifact(ctx context.Context, arg GetPausedSessionByArtifactParams) (ChetterAgentSession, error) {
	row := q.db.QueryRowContext(ctx, getPausedSessionByArtifact, arg.Repo, arg.Number, arg.ArtifactType)
	var i ChetterAgentSession
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Status,
		&i.ResumeMode,
		&i.PinnedRunnerID,
		&i.PinnedRunnerName,
		&i.CheckpointID,
		&i.WorkspacePath,
		&i.ContainerName,
		&i.HarnessSessionID,
		&i.GitUrl,
		&i.GitRef,
		&i.AgentImage,
		&i.Agent,
		&i.ProviderID,
		&i.ModelID,
		&i.VariantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
		&i.ExpiresAt,
		&i.PauseReason,
		&i.Error,
		&i.SearchText,
		&i.Sequence,
		&i.TaskID,
		&i.Harness,
		&i.McpEndpoints,
		&i.CommitAuthorName,
		&i.CommitAuthorEmail,
		&i.GitIdentityID,
		&i.Skills,
		&i.Env,
		&i.Summary,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getUserPromptByID = `-- name: GetUserPromptByID :one
SELECT id, agent_session_id, task_id, status, prompt, summary, error, session_export, created_at, updated_at, started_at, ended_at, sequence, source_user_prompt_id FROM chetter_user_prompts WHERE id = ?
`

func (q *Queries) GetUserPromptByID(ctx context.Context, id string) (ChetterUserPrompt, error) {
	row := q.db.QueryRowContext(ctx, getUserPromptByID, id)
	var i ChetterUserPrompt
	err := row.Scan(
		&i.ID,
		&i.AgentSessionID,
		&i.TaskID,
		&i.Status,
		&i.Prompt,
		&i.Summary,
		&i.Error,
		&i.SessionExport,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Sequence,
		&i.SourceUserPromptID,
	)
	return i, err
}

const getUserPromptByTaskID = `-- name: GetUserPromptByTaskID :one
SELECT prompt.id, prompt.agent_session_id, prompt.task_id, prompt.status, prompt.prompt, prompt.summary, prompt.error, prompt.session_export, prompt.created_at, prompt.updated_at, prompt.started_at, prompt.ended_at, prompt.sequence, prompt.source_user_prompt_id FROM chetter_user_prompts prompt
JOIN chetter_agent_sessions session ON session.id = prompt.agent_session_id
WHERE prompt.task_id = ?
ORDER BY session.sequence DESC, prompt.sequence DESC
LIMIT 1
`

func (q *Queries) GetUserPromptByTaskID(ctx context.Context, taskID string) (ChetterUserPrompt, error) {
	row := q.db.QueryRowContext(ctx, getUserPromptByTaskID, taskID)
	var i ChetterUserPrompt
	err := row.Scan(
		&i.ID,
		&i.AgentSessionID,
		&i.TaskID,
		&i.Status,
		&i.Prompt,
		&i.Summary,
		&i.Error,
		&i.SessionExport,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Sequence,
		&i.SourceUserPromptID,
	)
	return i, err
}

const insertAgentSession = `-- name: InsertAgentSession :exec
INSERT INTO chetter_agent_sessions
    (id, task_id, sequence, team_id, status, resume_mode, pause_reason, expires_at, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, mcp_endpoints, env, commit_author_name, commit_author_email, git_identity_id, search_text, created_at, updated_at, started_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAgentSessionParams struct {
	ID                string           `json:"id"`
	TaskID            string           `json:"task_id"`
	Sequence          int32            `json:"sequence"`
	TeamID            sql.NullString   `json:"team_id"`
	Status            string           `json:"status"`
	ResumeMode        string           `json:"resume_mode"`
	PauseReason       sql.NullString   `json:"pause_reason"`
	ExpiresAt         sql.NullTime     `json:"expires_at"`
	GitUrl            sql.NullString   `json:"git_url"`
	GitRef            sql.NullString   `json:"git_ref"`
	AgentImage        sql.NullString   `json:"agent_image"`
	Agent             sql.NullString   `json:"agent"`
	ProviderID        sql.NullString   `json:"provider_id"`
	ModelID           sql.NullString   `json:"model_id"`
	VariantID         sql.NullString   `json:"variant_id"`
	Harness           sql.NullString   `json:"harness"`
	Skills            json.RawMessage  `json:"skills"`
	McpEndpoints      *json.RawMessage `json:"mcp_endpoints"`
	Env               json.RawMessage  `json:"env"`
	CommitAuthorName  sql.NullString   `json:"commit_author_name"`
	CommitAuthorEmail sql.NullString   `json:"commit_author_email"`
	GitIdentityID     sql.NullString   `json:"git_identity_id"`
	SearchText        sql.NullString   `json:"search_text"`
	CreatedAt         time.Time        `json:"created_at"`
	UpdatedAt         time.Time        `json:"updated_at"`
	StartedAt         sql.NullTime     `json:"started_at"`
}

func (q *Queries) InsertAgentSession(ctx context.Context, arg InsertAgentSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentSession,
		arg.ID,
		arg.TaskID,
		arg.Sequence,
		arg.TeamID,
		arg.Status,
		arg.ResumeMode,
		arg.PauseReason,
		arg.ExpiresAt,
		arg.GitUrl,
		arg.GitRef,
		arg.AgentImage,
		arg.Agent,
		arg.ProviderID,
		arg.ModelID,
		arg.VariantID,
		arg.Harness,
		arg.Skills,
		arg.McpEndpoints,
		arg.Env,
		arg.CommitAuthorName,
		arg.CommitAuthorEmail,
		arg.GitIdentityID,
		arg.SearchText,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.StartedAt,
	)
	return err
}

const insertAgentSessionCheckpoint = `-- name: InsertAgentSessionCheckpoint :exec
INSERT INTO chetter_agent_session_checkpoints
    (id, agent_session_id, user_prompt_id, runner_id, checkpoint_path, workspace_path, container_name, runsc_version, agent_image, size_bytes, status, error, created_at, updated_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAgentSessionCheckpointParams struct {
	ID             string         `json:"id"`
	AgentSessionID string         `json:"agent_session_id"`
	UserPromptID   sql.NullString `json:"user_prompt_id"`
	RunnerID       string         `json:"runner_id"`
	CheckpointPath string         `json:"checkpoint_path"`
	WorkspacePath  string         `json:"workspace_path"`
	ContainerName  sql.NullString `json:"container_name"`
	RunscVersion   sql.NullString `json:"runsc_version"`
	AgentImage     sql.NullString `json:"agent_image"`
	SizeBytes      int64          `json:"size_bytes"`
	Status         string         `json:"status"`
	Error          sql.NullString `json:"error"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ExpiresAt      sql.NullTime   `json:"expires_at"`
}

func (q *Queries) InsertAgentSessionCheckpoint(ctx context.Context, arg InsertAgentSessionCheckpointParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentSessionCheckpoint,
		arg.ID,
		arg.AgentSessionID,
		arg.UserPromptID,
		arg.RunnerID,
		arg.CheckpointPath,
		arg.WorkspacePath,
		arg.ContainerName,
		arg.RunscVersion,
		arg.AgentImage,
		arg.SizeBytes,
		arg.Status,
		arg.Error,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertUserPrompt = `-- name: InsertUserPrompt :exec
INSERT INTO chetter_user_prompts
    (id, agent_session_id, task_id, sequence, status, prompt, source_user_prompt_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertUserPromptParams struct {
	ID                 string         `json:"id"`
	AgentSessionID     string         `json:"agent_session_id"`
	TaskID             string         `json:"task_id"`
	Sequence           int32          `json:"sequence"`
	Status             string         `json:"status"`
	Prompt             string         `json:"prompt"`
	SourceUserPromptID sql.NullString `json:"source_user_prompt_id"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

func (q *Queries) InsertUserPrompt(ctx context.Context, arg InsertUserPromptParams) error {
	_, err := q.db.ExecContext(ctx, insertUserPrompt,
		arg.ID,
		arg.AgentSessionID,
		arg.TaskID,
		arg.Sequence,
		arg.Status,
		arg.Prompt,
		arg.SourceUserPromptID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const isRunnerAlive = `-- name: IsRunnerAlive :one
SELECT COUNT(*) > 0 FROM chetter_runners
WHERE id = ?
  AND status = 'active'
  AND last_seen_at > DATE_SUB(NOW(), INTERVAL ? SECOND)
`

type IsRunnerAliveParams struct {
	RunnerID     string      `json:"runner_id"`
	StaleSeconds interface{} `json:"stale_seconds"`
}

func (q *Queries) IsRunnerAlive(ctx context.Context, arg IsRunnerAliveParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isRunnerAlive, arg.RunnerID, arg.StaleSeconds)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listAgentSessions = `-- name: ListAgentSessions :many
SELECT id, team_id, status, resume_mode, pinned_runner_id, pinned_runner_name, checkpoint_id, workspace_path, container_name, harness_session_id, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, created_at, updated_at, paused_at, expires_at, pause_reason, error, search_text, sequence, task_id, harness, mcp_endpoints, commit_author_name, commit_author_email, git_identity_id, skills, env, summary, started_at, ended_at FROM chetter_agent_sessions
WHERE (? = '' OR COALESCE(team_id, '') = ?)
  AND (? = '' OR status = ?)
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type ListAgentSessionsParams struct {
	TeamFilter   sql.NullString `json:"team_filter"`
	StatusFilter string         `json:"status_filter"`
	Limit        int32          `json:"limit"`
	Offset       int32          `json:"offset"`
}

func (q *Queries) ListAgentSessions(ctx context.Context, arg ListAgentSessionsParams) ([]ChetterAgentSession, error) {
	rows, err := q.db.QueryContext(ctx, listAgentSessions,
		arg.TeamFilter,
		arg.TeamFilter,
		arg.StatusFilter,
		arg.StatusFilter,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterAgentSession{}
	for rows.Next() {
		var i ChetterAgentSession
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Status,
			&i.ResumeMode,
			&i.PinnedRunnerID,
			&i.PinnedRunnerName,
			&i.CheckpointID,
			&i.WorkspacePath,
			&i.ContainerName,
			&i.HarnessSessionID,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
			&i.ExpiresAt,
			&i.PauseReason,
			&i.Error,
			&i.SearchText,
			&i.Sequence,
			&i.TaskID,
			&i.Harness,
			&i.McpEndpoints,
			&i.CommitAuthorName,
			&i.CommitAuthorEmail,
			&i.GitIdentityID,
			&i.Skills,
			&i.Env,
			&i.Summary,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSessionsByTeams = `-- name: ListAgentSessionsByTeams :many
SELECT id, team_id, status, resume_mode, pinned_runner_id, pinned_runner_name, checkpoint_id, workspace_path, container_name, harness_session_id, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, created_at, updated_at, paused_at, expires_at, pause_reason, error, search_text, sequence, task_id, harness, mcp_endpoints, commit_author_name, commit_author_email, git_identity_id, skills, env, summary, started_at, ended_at FROM chetter_agent_sessions
WHERE team_id IN (/*SLICE:team_ids*/?)
  AND (? = '' OR status = ?)
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type ListAgentSessionsByTeamsParams struct {
	TeamIds      []sql.NullString `json:"team_ids"`
	StatusFilter string           `json:"status_filter"`
	Limit        int32            `json:"limit"`
	Offset       int32            `json:"offset"`
}

func (q *Queries) ListAgentSessionsByTeams(ctx context.Context, arg ListAgentSessionsByTeamsParams) ([]ChetterAgentSession, error) {
	query := listAgentSessionsByTeams
	var queryParams []interface{}
	if len(arg.TeamIds) > 0 {
		for _, v := range arg.TeamIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:team_ids*/?", strings.Repeat(",?", len(arg.TeamIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:team_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.StatusFilter)
	queryParams = append(queryParams, arg.StatusFilter)
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterAgentSession{}
	for rows.Next() {
		var i ChetterAgentSession
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Status,
			&i.ResumeMode,
			&i.PinnedRunnerID,
			&i.PinnedRunnerName,
			&i.CheckpointID,
			&i.WorkspacePath,
			&i.ContainerName,
			&i.HarnessSessionID,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
			&i.ExpiresAt,
			&i.PauseReason,
			&i.Error,
			&i.SearchText,
			&i.Sequence,
			&i.TaskID,
			&i.Harness,
			&i.McpEndpoints,
			&i.CommitAuthorName,
			&i.CommitAuthorEmail,
			&i.GitIdentityID,
			&i.Skills,
			&i.Env,
			&i.Summary,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPromptsBySession = `-- name: ListUserPromptsBySession :many
SELECT id, agent_session_id, task_id, status, prompt, summary, error, session_export, created_at, updated_at, started_at, ended_at, sequence, source_user_prompt_id FROM chetter_user_prompts
WHERE agent_session_id = ?
ORDER BY sequence ASC, created_at ASC
`

func (q *Queries) ListUserPromptsBySession(ctx context.Context, agentSessionID string) ([]ChetterUserPrompt, error) {
	rows, err := q.db.QueryContext(ctx, listUserPromptsBySession, agentSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterUserPrompt{}
	for rows.Next() {
		var i ChetterUserPrompt
		if err := rows.Scan(
			&i.ID,
			&i.AgentSessionID,
			&i.TaskID,
			&i.Status,
			&i.Prompt,
			&i.Summary,
			&i.Error,
			&i.SessionExport,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Sequence,
			&i.SourceUserPromptID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentSessionResuming = `-- name: MarkAgentSessionResuming :execrows
UPDATE chetter_agent_sessions
SET status = ?,
    updated_at = ?
WHERE id = ?
`

type MarkAgentSessionResumingParams struct {
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) MarkAgentSessionResuming(ctx context.Context, arg MarkAgentSessionResumingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAgentSessionResuming, arg.Status, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markAgentSessionTerminalByTask = `-- name: MarkAgentSessionTerminalByTask :execrows
UPDATE chetter_agent_sessions
SET status = ?,
    harness_session_id = COALESCE(NULLIF(?, ''), harness_session_id),
    summary = ?,
    error = ?,
    ended_at = ?,
    updated_at = ?
WHERE id = (SELECT agent.id FROM chetter_agent_sessions agent WHERE agent.task_id = ? ORDER BY agent.sequence DESC LIMIT 1)
AND status IN ('running', 'resuming')
`

type MarkAgentSessionTerminalByTaskParams struct {
	Status           string         `json:"status"`
	HarnessSessionID interface{}    `json:"harness_session_id"`
	Summary          sql.NullString `json:"summary"`
	Error            sql.NullString `json:"error"`
	EndedAt          sql.NullTime   `json:"ended_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	TaskID           string         `json:"task_id"`
}

func (q *Queries) MarkAgentSessionTerminalByTask(ctx context.Context, arg MarkAgentSessionTerminalByTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAgentSessionTerminalByTask,
		arg.Status,
		arg.HarnessSessionID,
		arg.Summary,
		arg.Error,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.TaskID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markResumingSessionsFailedForUnavailableRunner = `-- name: MarkResumingSessionsFailedForUnavailableRunner :execrows
UPDATE chetter_agent_sessions s
JOIN chetter_user_prompts sr ON sr.agent_session_id = s.id
JOIN chetter_tasks t ON t.id = sr.task_id
SET s.status = 'error',
    s.error = COALESCE(sr.error, t.error),
    s.ended_at = ?,
    s.updated_at = ?
WHERE s.status = 'resuming'
  AND sr.status = 'failed'
  AND t.status = 'error'
  AND t.error_category = 'runner_unavailable'
`

type MarkResumingSessionsFailedForUnavailableRunnerParams struct {
	EndedAt   sql.NullTime `json:"ended_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

func (q *Queries) MarkResumingSessionsFailedForUnavailableRunner(ctx context.Context, arg MarkResumingSessionsFailedForUnavailableRunnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markResumingSessionsFailedForUnavailableRunner, arg.EndedAt, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markUserPromptRunningByTask = `-- name: MarkUserPromptRunningByTask :execrows
UPDATE chetter_user_prompts
SET status = 'running',
    started_at = COALESCE(started_at, ?),
    updated_at = ?
WHERE id = (
    SELECT prompt.id FROM chetter_user_prompts prompt
    JOIN chetter_agent_sessions session ON session.id = prompt.agent_session_id
    WHERE prompt.task_id = ?
    ORDER BY session.sequence DESC, prompt.sequence DESC
    LIMIT 1
)
  AND status IN ('pending', 'claimed')
`

type MarkUserPromptRunningByTaskParams struct {
	StartedAt sql.NullTime `json:"started_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	TaskID    string       `json:"task_id"`
}

func (q *Queries) MarkUserPromptRunningByTask(ctx context.Context, arg MarkUserPromptRunningByTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markUserPromptRunningByTask, arg.StartedAt, arg.UpdatedAt, arg.TaskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markUserPromptTerminalByTask = `-- name: MarkUserPromptTerminalByTask :execrows
UPDATE chetter_user_prompts
SET status = ?,
    summary = ?,
    error = ?,
    session_export = COALESCE(?, session_export),
    started_at = COALESCE(started_at, ?),
    ended_at = COALESCE(?, ended_at),
    updated_at = ?
WHERE id = (
    SELECT prompt.id FROM chetter_user_prompts prompt
    JOIN chetter_agent_sessions session ON session.id = prompt.agent_session_id
    WHERE prompt.task_id = ?
    ORDER BY session.sequence DESC, prompt.sequence DESC
    LIMIT 1
)
`

type MarkUserPromptTerminalByTaskParams struct {
	Status        string         `json:"status"`
	Summary       sql.NullString `json:"summary"`
	Error         sql.NullString `json:"error"`
	SessionExport sql.NullString `json:"session_export"`
	StartedAt     sql.NullTime   `json:"started_at"`
	EndedAt       sql.NullTime   `json:"ended_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	TaskID        string         `json:"task_id"`
}

func (q *Queries) MarkUserPromptTerminalByTask(ctx context.Context, arg MarkUserPromptTerminalByTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markUserPromptTerminalByTask,
		arg.Status,
		arg.Summary,
		arg.Error,
		arg.SessionExport,
		arg.StartedAt,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.TaskID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pauseAgentSessionByTaskID = `-- name: PauseAgentSessionByTaskID :execrows
UPDATE chetter_agent_sessions
SET status = ?,
    pinned_runner_id = COALESCE(NULLIF(?, ''), pinned_runner_id),
    checkpoint_id = COALESCE(NULLIF(?, ''), checkpoint_id),
    workspace_path = COALESCE(NULLIF(?, ''), workspace_path),
    container_name = COALESCE(NULLIF(?, ''), container_name),
    harness_session_id = COALESCE(NULLIF(?, ''), harness_session_id),
    paused_at = ?,
    updated_at = ?
WHERE id = (SELECT agent.id FROM chetter_agent_sessions agent WHERE agent.task_id = ? ORDER BY agent.sequence DESC LIMIT 1)
AND status IN ('running', 'resuming')
`

type PauseAgentSessionByTaskIDParams struct {
	Status           string       `json:"status"`
	PinnedRunnerID   interface{}  `json:"pinned_runner_id"`
	CheckpointID     interface{}  `json:"checkpoint_id"`
	WorkspacePath    interface{}  `json:"workspace_path"`
	ContainerName    interface{}  `json:"container_name"`
	HarnessSessionID interface{}  `json:"harness_session_id"`
	PausedAt         sql.NullTime `json:"paused_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
	TaskID           string       `json:"task_id"`
}

func (q *Queries) PauseAgentSessionByTaskID(ctx context.Context, arg PauseAgentSessionByTaskIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pauseAgentSessionByTaskID,
		arg.Status,
		arg.PinnedRunnerID,
		arg.CheckpointID,
		arg.WorkspacePath,
		arg.ContainerName,
		arg.HarnessSessionID,
		arg.PausedAt,
		arg.UpdatedAt,
		arg.TaskID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reapStaleSessionsForTerminalRuns = `-- name: ReapStaleSessionsForTerminalRuns :execrows
UPDATE chetter_agent_sessions s
JOIN chetter_user_prompts sr ON sr.agent_session_id = s.id
JOIN chetter_tasks t ON t.id = sr.task_id
SET s.status = CASE
    WHEN t.status = 'done' THEN 'completed'
    WHEN t.status = 'cancelled' THEN 'error'
    ELSE 'error'
END,
s.error = COALESCE(NULLIF(s.error, ''), t.error, s.error),
s.summary = COALESCE(NULLIF(s.summary, ''), t.summary, s.summary),
s.ended_at = COALESCE(s.ended_at, t.ended_at, NOW()),
s.updated_at = NOW()
WHERE s.status = 'running'
  AND sr.status IN ('failed', 'completed', 'cancelled')
  AND t.status IN ('done', 'error', 'cancelled')
`

func (q *Queries) ReapStaleSessionsForTerminalRuns(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, reapStaleSessionsForTerminalRuns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reapStaleUserPrompts = `-- name: ReapStaleUserPrompts :execrows
UPDATE chetter_user_prompts sr
JOIN chetter_tasks t ON t.id = sr.task_id
SET sr.status = CASE
    WHEN t.status = 'done' THEN 'completed'
    WHEN t.status = 'cancelled' THEN 'cancelled'
    ELSE 'failed'
END,
sr.error = COALESCE(NULLIF(sr.error, ''), t.error, sr.error),
sr.ended_at = COALESCE(sr.ended_at, t.ended_at, NOW()),
sr.updated_at = NOW()
WHERE sr.status = 'running'
  AND t.status IN ('done', 'error', 'cancelled')
`

func (q *Queries) ReapStaleUserPrompts(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, reapStaleUserPrompts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revertOrphanedRunningUserPrompts = `-- name: RevertOrphanedRunningUserPrompts :execrows
UPDATE chetter_user_prompts sr
JOIN chetter_tasks t ON t.id = sr.task_id
SET sr.status = 'pending',
    sr.started_at = NULL,
    sr.updated_at = NOW()
WHERE sr.status = 'running'
  AND t.status = 'pending'
`

func (q *Queries) RevertOrphanedRunningUserPrompts(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, revertOrphanedRunningUserPrompts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const searchAgentSessions = `-- name: SearchAgentSessions :many
SELECT id, team_id, status, resume_mode, pinned_runner_id, pinned_runner_name, checkpoint_id, workspace_path, container_name, harness_session_id, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, created_at, updated_at, paused_at, expires_at, pause_reason, error, search_text, sequence, task_id, harness, mcp_endpoints, commit_author_name, commit_author_email, git_identity_id, skills, env, summary, started_at, ended_at FROM chetter_agent_sessions
WHERE (? = '' OR COALESCE(team_id, '') = ?)
  AND (? = '' OR status = ?)
  AND (search_text LIKE CONCAT('%', ?, '%'))
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type SearchAgentSessionsParams struct {
	TeamFilter   sql.NullString `json:"team_filter"`
	StatusFilter string         `json:"status_filter"`
	Search       interface{}    `json:"search"`
	Limit        int32          `json:"limit"`
	Offset       int32          `json:"offset"`
}

func (q *Queries) SearchAgentSessions(ctx context.Context, arg SearchAgentSessionsParams) ([]ChetterAgentSession, error) {
	rows, err := q.db.QueryContext(ctx, searchAgentSessions,
		arg.TeamFilter,
		arg.TeamFilter,
		arg.StatusFilter,
		arg.StatusFilter,
		arg.Search,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterAgentSession{}
	for rows.Next() {
		var i ChetterAgentSession
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Status,
			&i.ResumeMode,
			&i.PinnedRunnerID,
			&i.PinnedRunnerName,
			&i.CheckpointID,
			&i.WorkspacePath,
			&i.ContainerName,
			&i.HarnessSessionID,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
			&i.ExpiresAt,
			&i.PauseReason,
			&i.Error,
			&i.SearchText,
			&i.Sequence,
			&i.TaskID,
			&i.Harness,
			&i.McpEndpoints,
			&i.CommitAuthorName,
			&i.CommitAuthorEmail,
			&i.GitIdentityID,
			&i.Skills,
			&i.Env,
			&i.Summary,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAgentSessionsByTeams = `-- name: SearchAgentSessionsByTeams :many
SELECT id, team_id, status, resume_mode, pinned_runner_id, pinned_runner_name, checkpoint_id, workspace_path, container_name, harness_session_id, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, created_at, updated_at, paused_at, expires_at, pause_reason, error, search_text, sequence, task_id, harness, mcp_endpoints, commit_author_name, commit_author_email, git_identity_id, skills, env, summary, started_at, ended_at FROM chetter_agent_sessions
WHERE team_id IN (/*SLICE:team_ids*/?)
  AND (? = '' OR status = ?)
  AND (search_text LIKE CONCAT('%', ?, '%'))
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type SearchAgentSessionsByTeamsParams struct {
	TeamIds      []sql.NullString `json:"team_ids"`
	StatusFilter string           `json:"status_filter"`
	Search       interface{}      `json:"search"`
	Limit        int32            `json:"limit"`
	Offset       int32            `json:"offset"`
}

func (q *Queries) SearchAgentSessionsByTeams(ctx context.Context, arg SearchAgentSessionsByTeamsParams) ([]ChetterAgentSession, error) {
	query := searchAgentSessionsByTeams
	var queryParams []interface{}
	if len(arg.TeamIds) > 0 {
		for _, v := range arg.TeamIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:team_ids*/?", strings.Repeat(",?", len(arg.TeamIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:team_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.StatusFilter)
	queryParams = append(queryParams, arg.StatusFilter)
	queryParams = append(queryParams, arg.Search)
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterAgentSession{}
	for rows.Next() {
		var i ChetterAgentSession
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Status,
			&i.ResumeMode,
			&i.PinnedRunnerID,
			&i.PinnedRunnerName,
			&i.CheckpointID,
			&i.WorkspacePath,
			&i.ContainerName,
			&i.HarnessSessionID,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
			&i.ExpiresAt,
			&i.PauseReason,
			&i.Error,
			&i.SearchText,
			&i.Sequence,
			&i.TaskID,
			&i.Harness,
			&i.McpEndpoints,
			&i.CommitAuthorName,
			&i.CommitAuthorEmail,
			&i.GitIdentityID,
			&i.Skills,
			&i.Env,
			&i.Summary,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentSessionFromRunnerEvent = `-- name: UpdateAgentSessionFromRunnerEvent :execrows
UPDATE chetter_agent_sessions
SET provider_id = COALESCE(NULLIF(?, ''), provider_id),
    model_id = COALESCE(NULLIF(?, ''), model_id),
    variant_id = COALESCE(NULLIF(?, ''), variant_id),
    harness_session_id = COALESCE(NULLIF(?, ''), harness_session_id),
    updated_at = ?
WHERE id = (SELECT agent.id FROM chetter_agent_sessions agent WHERE agent.task_id = ? ORDER BY agent.sequence DESC LIMIT 1)
  AND status IN ('running', 'resuming')
`

type UpdateAgentSessionFromRunnerEventParams struct {
	ProviderID       interface{} `json:"provider_id"`
	ModelID          interface{} `json:"model_id"`
	VariantID        interface{} `json:"variant_id"`
	HarnessSessionID interface{} `json:"harness_session_id"`
	UpdatedAt        time.Time   `json:"updated_at"`
	TaskID           string      `json:"task_id"`
}

func (q *Queries) UpdateAgentSessionFromRunnerEvent(ctx context.Context, arg UpdateAgentSessionFromRunnerEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAgentSessionFromRunnerEvent,
		arg.ProviderID,
		arg.ModelID,
		arg.VariantID,
		arg.HarnessSessionID,
		arg.UpdatedAt,
		arg.TaskID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
