// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package repository

import (
	"context"
	"time"
)

const createTeam = `-- name: CreateTeam :exec
INSERT INTO teams (id, name, created_at, updated_at)
VALUES (?, ?, ?, ?)
`

type CreateTeamParams struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) error {
	_, err := q.db.ExecContext(ctx, createTeam,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createToken = `-- name: CreateToken :exec
INSERT INTO api_tokens (id, name, token_hash, user_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTokenParams struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	TokenHash string    `json:"token_hash"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.ExecContext(ctx, createToken,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, name, team_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	TeamID    string    `json:"team_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.TeamID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams
WHERE name = ?
`

func (q *Queries) DeleteTeam(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteTeam, name)
	return err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM api_tokens
WHERE name = ?
`

func (q *Queries) DeleteToken(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteToken, name)
	return err
}

const deleteTokensByTeam = `-- name: DeleteTokensByTeam :exec
DELETE FROM api_tokens
WHERE user_id IN (SELECT id FROM users WHERE team_id = ?)
`

func (q *Queries) DeleteTokensByTeam(ctx context.Context, teamID string) error {
	_, err := q.db.ExecContext(ctx, deleteTokensByTeam, teamID)
	return err
}

const deleteUsersByTeam = `-- name: DeleteUsersByTeam :exec
DELETE FROM users
WHERE team_id = ?
`

func (q *Queries) DeleteUsersByTeam(ctx context.Context, teamID string) error {
	_, err := q.db.ExecContext(ctx, deleteUsersByTeam, teamID)
	return err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, created_at, updated_at FROM teams
WHERE id = ?
`

func (q *Queries) GetTeamByID(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT id, name, created_at, updated_at FROM teams
WHERE name = ?
`

func (q *Queries) GetTeamByName(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByName, name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT t.id, t.name, t.token_hash, t.user_id, t.created_at, t.updated_at,
       u.name AS user_name, u.team_id, tm.name AS team_name
FROM api_tokens t
JOIN users u ON u.id = t.user_id
JOIN teams tm ON tm.id = u.team_id
WHERE t.token_hash = ?
`

type GetTokenByHashRow struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	TokenHash string    `json:"token_hash"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	UserName  string    `json:"user_name"`
	TeamID    string    `json:"team_id"`
	TeamName  string    `json:"team_name"`
}

func (q *Queries) GetTokenByHash(ctx context.Context, tokenHash string) (GetTokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getTokenByHash, tokenHash)
	var i GetTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.TeamID,
		&i.TeamName,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, team_id, created_at, updated_at FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, created_at, updated_at FROM teams
ORDER BY name ASC
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokens = `-- name: ListTokens :many
SELECT t.id, t.name, t.token_hash, t.user_id, t.created_at, t.updated_at,
       u.name AS user_name, u.team_id, tm.name AS team_name
FROM api_tokens t
JOIN users u ON u.id = t.user_id
JOIN teams tm ON tm.id = u.team_id
ORDER BY t.created_at DESC
`

type ListTokensRow struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	TokenHash string    `json:"token_hash"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	UserName  string    `json:"user_name"`
	TeamID    string    `json:"team_id"`
	TeamName  string    `json:"team_name"`
}

func (q *Queries) ListTokens(ctx context.Context) ([]ListTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, listTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokensRow{}
	for rows.Next() {
		var i ListTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.TeamID,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.name, u.team_id, tm.name AS team_name, u.created_at, u.updated_at
FROM users u
JOIN teams tm ON tm.id = u.team_id
ORDER BY u.name ASC
`

type ListUsersRow struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	TeamID    string    `json:"team_id"`
	TeamName  string    `json:"team_name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamID,
			&i.TeamName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTeam = `-- name: ListUsersByTeam :many
SELECT u.id, u.name, u.team_id, tm.name AS team_name, u.created_at, u.updated_at
FROM users u
JOIN teams tm ON tm.id = u.team_id
WHERE u.team_id = ?
ORDER BY u.name ASC
`

type ListUsersByTeamRow struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	TeamID    string    `json:"team_id"`
	TeamName  string    `json:"team_name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListUsersByTeam(ctx context.Context, teamID string) ([]ListUsersByTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByTeamRow{}
	for rows.Next() {
		var i ListUsersByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamID,
			&i.TeamName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
