// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package repository

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO chetter_audit_log (id, event_type, created_at, source_type, source_id, target_type, target_id, repo, github_event, github_action, github_delivery_id, parent_event_id, detail, search_text, payload)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditLogParams struct {
	ID               string           `json:"id"`
	EventType        string           `json:"event_type"`
	CreatedAt        time.Time        `json:"created_at"`
	SourceType       sql.NullString   `json:"source_type"`
	SourceID         sql.NullString   `json:"source_id"`
	TargetType       sql.NullString   `json:"target_type"`
	TargetID         sql.NullString   `json:"target_id"`
	Repo             sql.NullString   `json:"repo"`
	GithubEvent      sql.NullString   `json:"github_event"`
	GithubAction     sql.NullString   `json:"github_action"`
	GithubDeliveryID sql.NullString   `json:"github_delivery_id"`
	ParentEventID    sql.NullString   `json:"parent_event_id"`
	Detail           sql.NullString   `json:"detail"`
	SearchText       sql.NullString   `json:"search_text"`
	Payload          *json.RawMessage `json:"payload"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.ID,
		arg.EventType,
		arg.CreatedAt,
		arg.SourceType,
		arg.SourceID,
		arg.TargetType,
		arg.TargetID,
		arg.Repo,
		arg.GithubEvent,
		arg.GithubAction,
		arg.GithubDeliveryID,
		arg.ParentEventID,
		arg.Detail,
		arg.SearchText,
		arg.Payload,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, event_type, created_at, source_type, source_id, target_type, target_id, repo, github_event, github_action, github_delivery_id, parent_event_id, detail, payload
FROM chetter_audit_log
WHERE (event_type = ? OR ? = '')
  AND (source_type = ? OR ? = '')
  AND (source_id = ? OR ? = '')
  AND (target_type = ? OR ? = '')
  AND (target_id = ? OR ? = '')
  AND (repo = ? OR ? = '')
  AND (created_at >= ? OR ? IS NULL)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAuditLogParams struct {
	EventType  string         `json:"event_type"`
	Column2    interface{}    `json:"column_2"`
	SourceType sql.NullString `json:"source_type"`
	Column4    interface{}    `json:"column_4"`
	SourceID   sql.NullString `json:"source_id"`
	Column6    interface{}    `json:"column_6"`
	TargetType sql.NullString `json:"target_type"`
	Column8    interface{}    `json:"column_8"`
	TargetID   sql.NullString `json:"target_id"`
	Column10   interface{}    `json:"column_10"`
	Repo       sql.NullString `json:"repo"`
	Column12   interface{}    `json:"column_12"`
	CreatedAt  time.Time      `json:"created_at"`
	Column14   interface{}    `json:"column_14"`
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
}

type ListAuditLogRow struct {
	ID               string           `json:"id"`
	EventType        string           `json:"event_type"`
	CreatedAt        time.Time        `json:"created_at"`
	SourceType       sql.NullString   `json:"source_type"`
	SourceID         sql.NullString   `json:"source_id"`
	TargetType       sql.NullString   `json:"target_type"`
	TargetID         sql.NullString   `json:"target_id"`
	Repo             sql.NullString   `json:"repo"`
	GithubEvent      sql.NullString   `json:"github_event"`
	GithubAction     sql.NullString   `json:"github_action"`
	GithubDeliveryID sql.NullString   `json:"github_delivery_id"`
	ParentEventID    sql.NullString   `json:"parent_event_id"`
	Detail           sql.NullString   `json:"detail"`
	Payload          *json.RawMessage `json:"payload"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]ListAuditLogRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLog,
		arg.EventType,
		arg.Column2,
		arg.SourceType,
		arg.Column4,
		arg.SourceID,
		arg.Column6,
		arg.TargetType,
		arg.Column8,
		arg.TargetID,
		arg.Column10,
		arg.Repo,
		arg.Column12,
		arg.CreatedAt,
		arg.Column14,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogRow{}
	for rows.Next() {
		var i ListAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.CreatedAt,
			&i.SourceType,
			&i.SourceID,
			&i.TargetType,
			&i.TargetID,
			&i.Repo,
			&i.GithubEvent,
			&i.GithubAction,
			&i.GithubDeliveryID,
			&i.ParentEventID,
			&i.Detail,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAuditLog = `-- name: SearchAuditLog :many
SELECT id, event_type, created_at, source_type, source_id, target_type, target_id, repo, github_event, github_action, github_delivery_id, parent_event_id, detail, payload
FROM chetter_audit_log
WHERE (event_type = ? OR ? = '')
  AND (source_type = ? OR ? = '')
  AND (source_id = ? OR ? = '')
  AND (target_type = ? OR ? = '')
  AND (target_id = ? OR ? = '')
  AND (repo = ? OR ? = '')
  AND (created_at >= ? OR ? IS NULL)
  AND (search_text LIKE CONCAT('%', ?, '%'))
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type SearchAuditLogParams struct {
	EventType  string         `json:"event_type"`
	Column2    interface{}    `json:"column_2"`
	SourceType sql.NullString `json:"source_type"`
	Column4    interface{}    `json:"column_4"`
	SourceID   sql.NullString `json:"source_id"`
	Column6    interface{}    `json:"column_6"`
	TargetType sql.NullString `json:"target_type"`
	Column8    interface{}    `json:"column_8"`
	TargetID   sql.NullString `json:"target_id"`
	Column10   interface{}    `json:"column_10"`
	Repo       sql.NullString `json:"repo"`
	Column12   interface{}    `json:"column_12"`
	CreatedAt  time.Time      `json:"created_at"`
	Column14   interface{}    `json:"column_14"`
	Search     interface{}    `json:"search"`
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
}

type SearchAuditLogRow struct {
	ID               string           `json:"id"`
	EventType        string           `json:"event_type"`
	CreatedAt        time.Time        `json:"created_at"`
	SourceType       sql.NullString   `json:"source_type"`
	SourceID         sql.NullString   `json:"source_id"`
	TargetType       sql.NullString   `json:"target_type"`
	TargetID         sql.NullString   `json:"target_id"`
	Repo             sql.NullString   `json:"repo"`
	GithubEvent      sql.NullString   `json:"github_event"`
	GithubAction     sql.NullString   `json:"github_action"`
	GithubDeliveryID sql.NullString   `json:"github_delivery_id"`
	ParentEventID    sql.NullString   `json:"parent_event_id"`
	Detail           sql.NullString   `json:"detail"`
	Payload          *json.RawMessage `json:"payload"`
}

func (q *Queries) SearchAuditLog(ctx context.Context, arg SearchAuditLogParams) ([]SearchAuditLogRow, error) {
	rows, err := q.db.QueryContext(ctx, searchAuditLog,
		arg.EventType,
		arg.Column2,
		arg.SourceType,
		arg.Column4,
		arg.SourceID,
		arg.Column6,
		arg.TargetType,
		arg.Column8,
		arg.TargetID,
		arg.Column10,
		arg.Repo,
		arg.Column12,
		arg.CreatedAt,
		arg.Column14,
		arg.Search,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAuditLogRow{}
	for rows.Next() {
		var i SearchAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.CreatedAt,
			&i.SourceType,
			&i.SourceID,
			&i.TargetType,
			&i.TargetID,
			&i.Repo,
			&i.GithubEvent,
			&i.GithubAction,
			&i.GithubDeliveryID,
			&i.ParentEventID,
			&i.Detail,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
