// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_callbacks.sql

package repository

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const deleteEventCallback = `-- name: DeleteEventCallback :execrows
DELETE FROM chetter_event_callbacks
WHERE name = ?
  AND (team_id <=> ?)
`

type DeleteEventCallbackParams struct {
	Name   string         `json:"name"`
	TeamID sql.NullString `json:"team_id"`
}

func (q *Queries) DeleteEventCallback(ctx context.Context, arg DeleteEventCallbackParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEventCallback, arg.Name, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEventCallbackByID = `-- name: GetEventCallbackByID :one
SELECT id, team_id, name, event_type, action_type, action_config, enabled, created_at, updated_at FROM chetter_event_callbacks
WHERE id = ?
`

func (q *Queries) GetEventCallbackByID(ctx context.Context, id string) (ChetterEventCallback, error) {
	row := q.db.QueryRowContext(ctx, getEventCallbackByID, id)
	var i ChetterEventCallback
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.EventType,
		&i.ActionType,
		&i.ActionConfig,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventCallbackByName = `-- name: GetEventCallbackByName :one
SELECT id, team_id, name, event_type, action_type, action_config, enabled, created_at, updated_at FROM chetter_event_callbacks
WHERE name = ?
  AND (team_id <=> ?)
`

type GetEventCallbackByNameParams struct {
	Name   string         `json:"name"`
	TeamID sql.NullString `json:"team_id"`
}

func (q *Queries) GetEventCallbackByName(ctx context.Context, arg GetEventCallbackByNameParams) (ChetterEventCallback, error) {
	row := q.db.QueryRowContext(ctx, getEventCallbackByName, arg.Name, arg.TeamID)
	var i ChetterEventCallback
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.EventType,
		&i.ActionType,
		&i.ActionConfig,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEventCallback = `-- name: InsertEventCallback :exec
INSERT INTO chetter_event_callbacks
    (id, team_id, name, event_type, action_type, action_config, enabled, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventCallbackParams struct {
	ID           string          `json:"id"`
	TeamID       sql.NullString  `json:"team_id"`
	Name         string          `json:"name"`
	EventType    string          `json:"event_type"`
	ActionType   string          `json:"action_type"`
	ActionConfig json.RawMessage `json:"action_config"`
	Enabled      bool            `json:"enabled"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

func (q *Queries) InsertEventCallback(ctx context.Context, arg InsertEventCallbackParams) error {
	_, err := q.db.ExecContext(ctx, insertEventCallback,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.EventType,
		arg.ActionType,
		arg.ActionConfig,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listEnabledEventCallbacksForEvent = `-- name: ListEnabledEventCallbacksForEvent :many
SELECT id, team_id, name, event_type, action_type, action_config, enabled, created_at, updated_at FROM chetter_event_callbacks
WHERE enabled = true
  AND (team_id <=> ? OR team_id IS NULL)
  AND (
    event_type = ?
    OR (RIGHT(event_type, 2) = '.*' AND ? LIKE CONCAT(LEFT(event_type, CHAR_LENGTH(event_type) - 1), '%'))
  )
ORDER BY created_at ASC
`

type ListEnabledEventCallbacksForEventParams struct {
	TeamID    sql.NullString `json:"team_id"`
	EventType string         `json:"event_type"`
}

func (q *Queries) ListEnabledEventCallbacksForEvent(ctx context.Context, arg ListEnabledEventCallbacksForEventParams) ([]ChetterEventCallback, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledEventCallbacksForEvent, arg.TeamID, arg.EventType, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterEventCallback{}
	for rows.Next() {
		var i ChetterEventCallback
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.EventType,
			&i.ActionType,
			&i.ActionConfig,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventCallbacks = `-- name: ListEventCallbacks :many
SELECT id, team_id, name, event_type, action_type, action_config, enabled, created_at, updated_at FROM chetter_event_callbacks
WHERE (? = false OR enabled = true)
  AND (COALESCE(?, '') = '' OR event_type = ?)
  AND (
    ? = true
    OR team_id <=> ?
  )
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListEventCallbacksParams struct {
	EnabledOnly     interface{}    `json:"enabled_only"`
	EventTypeFilter string         `json:"event_type_filter"`
	IncludeGlobal   interface{}    `json:"include_global"`
	TeamID          sql.NullString `json:"team_id"`
	Limit           int32          `json:"limit"`
	Offset          int32          `json:"offset"`
}

func (q *Queries) ListEventCallbacks(ctx context.Context, arg ListEventCallbacksParams) ([]ChetterEventCallback, error) {
	rows, err := q.db.QueryContext(ctx, listEventCallbacks,
		arg.EnabledOnly,
		arg.EventTypeFilter,
		arg.EventTypeFilter,
		arg.IncludeGlobal,
		arg.TeamID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterEventCallback{}
	for rows.Next() {
		var i ChetterEventCallback
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.EventType,
			&i.ActionType,
			&i.ActionConfig,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventCallback = `-- name: UpdateEventCallback :execrows
UPDATE chetter_event_callbacks
SET event_type = ?,
    action_type = ?,
    action_config = ?,
    enabled = ?,
    updated_at = ?
WHERE name = ?
  AND (team_id <=> ?)
`

type UpdateEventCallbackParams struct {
	EventType    string          `json:"event_type"`
	ActionType   string          `json:"action_type"`
	ActionConfig json.RawMessage `json:"action_config"`
	Enabled      bool            `json:"enabled"`
	UpdatedAt    time.Time       `json:"updated_at"`
	Name         string          `json:"name"`
	TeamID       sql.NullString  `json:"team_id"`
}

func (q *Queries) UpdateEventCallback(ctx context.Context, arg UpdateEventCallbackParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEventCallback,
		arg.EventType,
		arg.ActionType,
		arg.ActionConfig,
		arg.Enabled,
		arg.UpdatedAt,
		arg.Name,
		arg.TeamID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
