// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: execution_attempts.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const getExecutionAttemptByID = `-- name: GetExecutionAttemptByID :one
SELECT id, user_prompt_id, sequence, status, runner_id, required_runner_id, claimed_at, lease_expires_at, started_at, ended_at, workspace_path, container_name, harness_execution_id, summary, error, error_category, session_export, total_input_tokens, total_output_tokens, total_cache_read_tokens, total_cache_write_tokens, total_reasoning_tokens, cost_cents, created_at, updated_at FROM chetter_execution_attempts WHERE id = ?
`

func (q *Queries) GetExecutionAttemptByID(ctx context.Context, id string) (ChetterExecutionAttempt, error) {
	row := q.db.QueryRowContext(ctx, getExecutionAttemptByID, id)
	var i ChetterExecutionAttempt
	err := row.Scan(
		&i.ID,
		&i.UserPromptID,
		&i.Sequence,
		&i.Status,
		&i.RunnerID,
		&i.RequiredRunnerID,
		&i.ClaimedAt,
		&i.LeaseExpiresAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.WorkspacePath,
		&i.ContainerName,
		&i.HarnessExecutionID,
		&i.Summary,
		&i.Error,
		&i.ErrorCategory,
		&i.SessionExport,
		&i.TotalInputTokens,
		&i.TotalOutputTokens,
		&i.TotalCacheReadTokens,
		&i.TotalCacheWriteTokens,
		&i.TotalReasoningTokens,
		&i.CostCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextExecutionAttemptSequence = `-- name: GetNextExecutionAttemptSequence :one
SELECT COALESCE(MAX(sequence), 0) + 1
FROM chetter_execution_attempts
WHERE user_prompt_id = ?
`

func (q *Queries) GetNextExecutionAttemptSequence(ctx context.Context, userPromptID string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getNextExecutionAttemptSequence, userPromptID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertExecutionAttempt = `-- name: InsertExecutionAttempt :exec
INSERT INTO chetter_execution_attempts
    (id, user_prompt_id, sequence, status, runner_id, required_runner_id, claimed_at, lease_expires_at, started_at, created_at, updated_at)
VALUES (?, ?, ?, 'running', ?, ?, ?, ?, ?, ?, ?)
`

type InsertExecutionAttemptParams struct {
	ID               string         `json:"id"`
	UserPromptID     string         `json:"user_prompt_id"`
	Sequence         int32          `json:"sequence"`
	RunnerID         sql.NullString `json:"runner_id"`
	RequiredRunnerID sql.NullString `json:"required_runner_id"`
	ClaimedAt        sql.NullTime   `json:"claimed_at"`
	LeaseExpiresAt   sql.NullTime   `json:"lease_expires_at"`
	StartedAt        sql.NullTime   `json:"started_at"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

func (q *Queries) InsertExecutionAttempt(ctx context.Context, arg InsertExecutionAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertExecutionAttempt,
		arg.ID,
		arg.UserPromptID,
		arg.Sequence,
		arg.RunnerID,
		arg.RequiredRunnerID,
		arg.ClaimedAt,
		arg.LeaseExpiresAt,
		arg.StartedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listExecutionAttemptsByPrompt = `-- name: ListExecutionAttemptsByPrompt :many
SELECT id, user_prompt_id, sequence, status, runner_id, required_runner_id, claimed_at, lease_expires_at, started_at, ended_at, workspace_path, container_name, harness_execution_id, summary, error, error_category, session_export, total_input_tokens, total_output_tokens, total_cache_read_tokens, total_cache_write_tokens, total_reasoning_tokens, cost_cents, created_at, updated_at FROM chetter_execution_attempts
WHERE user_prompt_id = ?
ORDER BY sequence ASC, created_at ASC
`

func (q *Queries) ListExecutionAttemptsByPrompt(ctx context.Context, userPromptID string) ([]ChetterExecutionAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listExecutionAttemptsByPrompt, userPromptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterExecutionAttempt{}
	for rows.Next() {
		var i ChetterExecutionAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserPromptID,
			&i.Sequence,
			&i.Status,
			&i.RunnerID,
			&i.RequiredRunnerID,
			&i.ClaimedAt,
			&i.LeaseExpiresAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.WorkspacePath,
			&i.ContainerName,
			&i.HarnessExecutionID,
			&i.Summary,
			&i.Error,
			&i.ErrorCategory,
			&i.SessionExport,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.TotalCacheReadTokens,
			&i.TotalCacheWriteTokens,
			&i.TotalReasoningTokens,
			&i.CostCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExecutionAttemptLost = `-- name: MarkExecutionAttemptLost :execrows
UPDATE chetter_execution_attempts
SET status = 'lost', error = ?, ended_at = ?, updated_at = ?
WHERE id = ? AND status = 'running'
`

type MarkExecutionAttemptLostParams struct {
	Error     sql.NullString `json:"error"`
	EndedAt   sql.NullTime   `json:"ended_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) MarkExecutionAttemptLost(ctx context.Context, arg MarkExecutionAttemptLostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markExecutionAttemptLost,
		arg.Error,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renewExecutionAttemptLease = `-- name: RenewExecutionAttemptLease :execrows
UPDATE chetter_execution_attempts
SET lease_expires_at = ?, updated_at = ?
WHERE id = ? AND runner_id = ? AND status = 'running'
`

type RenewExecutionAttemptLeaseParams struct {
	LeaseExpiresAt sql.NullTime   `json:"lease_expires_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ID             string         `json:"id"`
	RunnerID       sql.NullString `json:"runner_id"`
}

func (q *Queries) RenewExecutionAttemptLease(ctx context.Context, arg RenewExecutionAttemptLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewExecutionAttemptLease,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.ID,
		arg.RunnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateExecutionAttemptFromRunnerEvent = `-- name: UpdateExecutionAttemptFromRunnerEvent :execrows
UPDATE chetter_execution_attempts
SET status = ?,
    summary = ?,
    error = ?,
    error_category = COALESCE(NULLIF(?, ''), error_category),
    session_export = COALESCE(?, session_export),
    lease_expires_at = ?,
    started_at = COALESCE(?, started_at),
    ended_at = COALESCE(?, ended_at),
    workspace_path = COALESCE(NULLIF(?, ''), workspace_path),
    harness_execution_id = COALESCE(NULLIF(?, ''), harness_execution_id),
    total_input_tokens = total_input_tokens + ?,
    total_output_tokens = total_output_tokens + ?,
    total_cache_read_tokens = total_cache_read_tokens + ?,
    total_cache_write_tokens = total_cache_write_tokens + ?,
    total_reasoning_tokens = total_reasoning_tokens + ?,
    cost_cents = cost_cents + ?,
    updated_at = ?
WHERE id = ? AND runner_id = ? AND status = 'running'
`

type UpdateExecutionAttemptFromRunnerEventParams struct {
	Status                string         `json:"status"`
	Summary               sql.NullString `json:"summary"`
	Error                 sql.NullString `json:"error"`
	ErrorCategory         interface{}    `json:"error_category"`
	SessionExport         sql.NullString `json:"session_export"`
	LeaseExpiresAt        sql.NullTime   `json:"lease_expires_at"`
	StartedAt             sql.NullTime   `json:"started_at"`
	EndedAt               sql.NullTime   `json:"ended_at"`
	WorkspacePath         interface{}    `json:"workspace_path"`
	HarnessExecutionID    interface{}    `json:"harness_execution_id"`
	TotalInputTokens      int64          `json:"total_input_tokens"`
	TotalOutputTokens     int64          `json:"total_output_tokens"`
	TotalCacheReadTokens  int64          `json:"total_cache_read_tokens"`
	TotalCacheWriteTokens int64          `json:"total_cache_write_tokens"`
	TotalReasoningTokens  int64          `json:"total_reasoning_tokens"`
	CostCents             int64          `json:"cost_cents"`
	UpdatedAt             time.Time      `json:"updated_at"`
	ID                    string         `json:"id"`
	RunnerID              sql.NullString `json:"runner_id"`
}

func (q *Queries) UpdateExecutionAttemptFromRunnerEvent(ctx context.Context, arg UpdateExecutionAttemptFromRunnerEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateExecutionAttemptFromRunnerEvent,
		arg.Status,
		arg.Summary,
		arg.Error,
		arg.ErrorCategory,
		arg.SessionExport,
		arg.LeaseExpiresAt,
		arg.StartedAt,
		arg.EndedAt,
		arg.WorkspacePath,
		arg.HarnessExecutionID,
		arg.TotalInputTokens,
		arg.TotalOutputTokens,
		arg.TotalCacheReadTokens,
		arg.TotalCacheWriteTokens,
		arg.TotalReasoningTokens,
		arg.CostCents,
		arg.UpdatedAt,
		arg.ID,
		arg.RunnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
