// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbound_deliveries.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const getInboundDeliveryRetryState = `-- name: GetInboundDeliveryRetryState :one

SELECT id, endpoint_id, team_id, status FROM inbound_deliveries WHERE id = ?
`

type GetInboundDeliveryRetryStateRow struct {
	ID         string         `json:"id"`
	EndpointID string         `json:"endpoint_id"`
	TeamID     sql.NullString `json:"team_id"`
	Status     string         `json:"status"`
}

// inbound_deliveries is the durable inbox for generic inbound webhook
// endpoint requests (issue #120). A request row is durably inserted before the
// receiver answers 202; a leased multi-replica worker then claims due rows and
// performs the endpoint action (create_task) exactly once. Statuses: pending,
// processing, succeeded, retry_wait, failed_permanent, dead_letter.
//
// These queries cover the operator-initiated redelivery path (issue #421).
// The delivery lifecycle itself is driven by dialect-switched raw SQL in
// internal/service/inbound_deliveries.go.
// Read-only status lookup used to enforce team scope and explain why a retry
// was rejected. The authoritative eligibility check is the guarded UPDATE.
func (q *Queries) GetInboundDeliveryRetryState(ctx context.Context, id string) (GetInboundDeliveryRetryStateRow, error) {
	row := q.db.QueryRowContext(ctx, getInboundDeliveryRetryState, id)
	var i GetInboundDeliveryRetryStateRow
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.TeamID,
		&i.Status,
	)
	return i, err
}

const resetInboundDeliveryForRetry = `-- name: ResetInboundDeliveryForRetry :execrows
UPDATE inbound_deliveries
SET status = 'pending',
    attempts = 0,
    error = NULL,
    lease_expires_at = NULL,
    next_attempt_at = ?,
    processed_at = NULL,
    updated_at = ?
WHERE id = ?
  AND status IN ('failed_permanent', 'dead_letter')
`

type ResetInboundDeliveryForRetryParams struct {
	NextAttemptAt sql.NullTime `json:"next_attempt_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	ID            string       `json:"id"`
}

// Operator-initiated redelivery (issue #421): only terminal
// failed_permanent/dead_letter rows are eligible. The status predicate keeps a
// concurrently claimed row (processing with a live lease) and a succeeded row
// untouched. Task creation derives a deterministic id from the delivery row,
// so a redelivered row can never create a duplicate task.
func (q *Queries) ResetInboundDeliveryForRetry(ctx context.Context, arg ResetInboundDeliveryForRetryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetInboundDeliveryForRetry, arg.NextAttemptAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
