// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package repository

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createSchedule = `-- name: CreateSchedule :exec
INSERT INTO chetter_schedules
    (id, team_id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, TRUE, ?, ?)
`

type CreateScheduleParams struct {
	ID            string          `json:"id"`
	TeamID        sql.NullString  `json:"team_id"`
	Name          string          `json:"name"`
	TriggerType   string          `json:"trigger_type"`
	TriggerConfig json.RawMessage `json:"trigger_config"`
	CronExpr      string          `json:"cron_expr"`
	Prompt        string          `json:"prompt"`
	GitUrl        sql.NullString  `json:"git_url"`
	GitRef        sql.NullString  `json:"git_ref"`
	AgentImage    sql.NullString  `json:"agent_image"`
	Agent         sql.NullString  `json:"agent"`
	ProviderID    sql.NullString  `json:"provider_id"`
	ModelID       sql.NullString  `json:"model_id"`
	VariantID     sql.NullString  `json:"variant_id"`
	Harness       sql.NullString  `json:"harness"`
	Skills        json.RawMessage `json:"skills"`
	TimeoutSec    int32           `json:"timeout_sec"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) error {
	_, err := q.db.ExecContext(ctx, createSchedule,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.TriggerType,
		arg.TriggerConfig,
		arg.CronExpr,
		arg.Prompt,
		arg.GitUrl,
		arg.GitRef,
		arg.AgentImage,
		arg.Agent,
		arg.ProviderID,
		arg.ModelID,
		arg.VariantID,
		arg.Harness,
		arg.Skills,
		arg.TimeoutSec,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM chetter_schedules
WHERE name = ?
`

func (q *Queries) DeleteSchedule(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, name)
	return err
}

const getScheduleByID = `-- name: GetScheduleByID :one
SELECT id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at, last_run_at, next_run_at, team_id FROM chetter_schedules
WHERE id = ?
`

func (q *Queries) GetScheduleByID(ctx context.Context, id string) (ChetterSchedule, error) {
	row := q.db.QueryRowContext(ctx, getScheduleByID, id)
	var i ChetterSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.CronExpr,
		&i.Prompt,
		&i.GitUrl,
		&i.GitRef,
		&i.AgentImage,
		&i.Agent,
		&i.ProviderID,
		&i.ModelID,
		&i.VariantID,
		&i.Harness,
		&i.Skills,
		&i.TimeoutSec,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.TeamID,
	)
	return i, err
}

const getScheduleByName = `-- name: GetScheduleByName :one
SELECT id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at, last_run_at, next_run_at, team_id FROM chetter_schedules
WHERE name = ?
`

func (q *Queries) GetScheduleByName(ctx context.Context, name string) (ChetterSchedule, error) {
	row := q.db.QueryRowContext(ctx, getScheduleByName, name)
	var i ChetterSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.CronExpr,
		&i.Prompt,
		&i.GitUrl,
		&i.GitRef,
		&i.AgentImage,
		&i.Agent,
		&i.ProviderID,
		&i.ModelID,
		&i.VariantID,
		&i.Harness,
		&i.Skills,
		&i.TimeoutSec,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.TeamID,
	)
	return i, err
}

const insertScheduleRun = `-- name: InsertScheduleRun :exec
INSERT INTO chetter_schedule_runs (id, schedule_id, team_id, task_id, status, scheduled_for, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertScheduleRunParams struct {
	ID           string         `json:"id"`
	ScheduleID   string         `json:"schedule_id"`
	TeamID       sql.NullString `json:"team_id"`
	TaskID       string         `json:"task_id"`
	Status       string         `json:"status"`
	ScheduledFor time.Time      `json:"scheduled_for"`
	CreatedAt    time.Time      `json:"created_at"`
}

func (q *Queries) InsertScheduleRun(ctx context.Context, arg InsertScheduleRunParams) error {
	_, err := q.db.ExecContext(ctx, insertScheduleRun,
		arg.ID,
		arg.ScheduleID,
		arg.TeamID,
		arg.TaskID,
		arg.Status,
		arg.ScheduledFor,
		arg.CreatedAt,
	)
	return err
}

const listEnabledIssueTriggersByRepo = `-- name: ListEnabledIssueTriggersByRepo :many
SELECT id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at, last_run_at, next_run_at, team_id FROM chetter_schedules
WHERE enabled = TRUE
  AND trigger_type = 'issue'
  AND trigger_config->>'$.repo' = ?
ORDER BY created_at DESC
`

func (q *Queries) ListEnabledIssueTriggersByRepo(ctx context.Context, repo json.RawMessage) ([]ChetterSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledIssueTriggersByRepo, repo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterSchedule{}
	for rows.Next() {
		var i ChetterSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.CronExpr,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.Harness,
			&i.Skills,
			&i.TimeoutSec,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledPRReviewTriggersByRepo = `-- name: ListEnabledPRReviewTriggersByRepo :many
SELECT id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at, last_run_at, next_run_at, team_id FROM chetter_schedules
WHERE enabled = TRUE
  AND trigger_type = 'pr_review'
  AND trigger_config->>'$.repo' = ?
ORDER BY created_at DESC
`

func (q *Queries) ListEnabledPRReviewTriggersByRepo(ctx context.Context, repo json.RawMessage) ([]ChetterSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledPRReviewTriggersByRepo, repo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterSchedule{}
	for rows.Next() {
		var i ChetterSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.CronExpr,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.Harness,
			&i.Skills,
			&i.TimeoutSec,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledSchedules = `-- name: ListEnabledSchedules :many
SELECT id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at, last_run_at, next_run_at, team_id FROM chetter_schedules
WHERE enabled = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListEnabledSchedules(ctx context.Context) ([]ChetterSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterSchedule{}
	for rows.Next() {
		var i ChetterSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.CronExpr,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.Harness,
			&i.Skills,
			&i.TimeoutSec,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledSchedulesByTeam = `-- name: ListEnabledSchedulesByTeam :many
SELECT id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at, last_run_at, next_run_at, team_id FROM chetter_schedules
WHERE team_id = ?
  AND enabled = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListEnabledSchedulesByTeam(ctx context.Context, teamID sql.NullString) ([]ChetterSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledSchedulesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterSchedule{}
	for rows.Next() {
		var i ChetterSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.CronExpr,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.Harness,
			&i.Skills,
			&i.TimeoutSec,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledTriggersByType = `-- name: ListEnabledTriggersByType :many
SELECT id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at, last_run_at, next_run_at, team_id FROM chetter_schedules
WHERE enabled = TRUE
  AND trigger_type = ?
ORDER BY created_at DESC
`

func (q *Queries) ListEnabledTriggersByType(ctx context.Context, triggerType string) ([]ChetterSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledTriggersByType, triggerType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterSchedule{}
	for rows.Next() {
		var i ChetterSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.CronExpr,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.Harness,
			&i.Skills,
			&i.TimeoutSec,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleRunsBySchedule = `-- name: ListScheduleRunsBySchedule :many
SELECT sr.id, sr.schedule_id, s.name AS schedule_name, sr.task_id, sr.status, sr.scheduled_for, sr.created_at
FROM chetter_schedule_runs sr
JOIN chetter_schedules s ON s.id = sr.schedule_id
WHERE sr.schedule_id = ?
ORDER BY sr.created_at DESC
LIMIT ? OFFSET ?
`

type ListScheduleRunsByScheduleParams struct {
	ScheduleID string `json:"schedule_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

type ListScheduleRunsByScheduleRow struct {
	ID           string    `json:"id"`
	ScheduleID   string    `json:"schedule_id"`
	ScheduleName string    `json:"schedule_name"`
	TaskID       string    `json:"task_id"`
	Status       string    `json:"status"`
	ScheduledFor time.Time `json:"scheduled_for"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) ListScheduleRunsBySchedule(ctx context.Context, arg ListScheduleRunsByScheduleParams) ([]ListScheduleRunsByScheduleRow, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleRunsBySchedule, arg.ScheduleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleRunsByScheduleRow{}
	for rows.Next() {
		var i ListScheduleRunsByScheduleRow
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.ScheduleName,
			&i.TaskID,
			&i.Status,
			&i.ScheduledFor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleRunsByTeam = `-- name: ListScheduleRunsByTeam :many
SELECT sr.id, sr.schedule_id, s.name AS schedule_name, sr.task_id, sr.status, sr.scheduled_for, sr.created_at
FROM chetter_schedule_runs sr
JOIN chetter_schedules s ON s.id = sr.schedule_id
WHERE s.team_id = ?
ORDER BY sr.created_at DESC
LIMIT ? OFFSET ?
`

type ListScheduleRunsByTeamParams struct {
	TeamID sql.NullString `json:"team_id"`
	Limit  int32          `json:"limit"`
	Offset int32          `json:"offset"`
}

type ListScheduleRunsByTeamRow struct {
	ID           string    `json:"id"`
	ScheduleID   string    `json:"schedule_id"`
	ScheduleName string    `json:"schedule_name"`
	TaskID       string    `json:"task_id"`
	Status       string    `json:"status"`
	ScheduledFor time.Time `json:"scheduled_for"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) ListScheduleRunsByTeam(ctx context.Context, arg ListScheduleRunsByTeamParams) ([]ListScheduleRunsByTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleRunsByTeam, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleRunsByTeamRow{}
	for rows.Next() {
		var i ListScheduleRunsByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.ScheduleName,
			&i.TaskID,
			&i.Status,
			&i.ScheduledFor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at, last_run_at, next_run_at, team_id FROM chetter_schedules
ORDER BY created_at DESC
`

func (q *Queries) ListSchedules(ctx context.Context) ([]ChetterSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterSchedule{}
	for rows.Next() {
		var i ChetterSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.CronExpr,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.Harness,
			&i.Skills,
			&i.TimeoutSec,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByTeam = `-- name: ListSchedulesByTeam :many
SELECT id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at, last_run_at, next_run_at, team_id FROM chetter_schedules
WHERE team_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListSchedulesByTeam(ctx context.Context, teamID sql.NullString) ([]ChetterSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterSchedule{}
	for rows.Next() {
		var i ChetterSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.CronExpr,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.Harness,
			&i.Skills,
			&i.TimeoutSec,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setScheduleLastRun = `-- name: SetScheduleLastRun :exec
UPDATE chetter_schedules
SET last_run_at = ?, updated_at = ?
WHERE id = ?
`

type SetScheduleLastRunParams struct {
	LastRunAt sql.NullTime `json:"last_run_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) SetScheduleLastRun(ctx context.Context, arg SetScheduleLastRunParams) error {
	_, err := q.db.ExecContext(ctx, setScheduleLastRun, arg.LastRunAt, arg.UpdatedAt, arg.ID)
	return err
}

const setScheduleNextRun = `-- name: SetScheduleNextRun :exec
UPDATE chetter_schedules
SET next_run_at = ?, updated_at = ?
WHERE id = ?
`

type SetScheduleNextRunParams struct {
	NextRunAt sql.NullTime `json:"next_run_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) SetScheduleNextRun(ctx context.Context, arg SetScheduleNextRunParams) error {
	_, err := q.db.ExecContext(ctx, setScheduleNextRun, arg.NextRunAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateSchedule = `-- name: UpdateSchedule :exec
UPDATE chetter_schedules
SET name = ?, trigger_type = ?, trigger_config = ?, cron_expr = ?, prompt = ?,
    git_url = ?, git_ref = ?, agent_image = ?,
    agent = ?, provider_id = ?, model_id = ?, variant_id = ?,
    harness = ?, skills = ?, timeout_sec = ?, enabled = ?,
    updated_at = ?
WHERE name = ?
`

type UpdateScheduleParams struct {
	NewName       string          `json:"new_name"`
	TriggerType   string          `json:"trigger_type"`
	TriggerConfig json.RawMessage `json:"trigger_config"`
	CronExpr      string          `json:"cron_expr"`
	Prompt        string          `json:"prompt"`
	GitUrl        sql.NullString  `json:"git_url"`
	GitRef        sql.NullString  `json:"git_ref"`
	AgentImage    sql.NullString  `json:"agent_image"`
	Agent         sql.NullString  `json:"agent"`
	ProviderID    sql.NullString  `json:"provider_id"`
	ModelID       sql.NullString  `json:"model_id"`
	VariantID     sql.NullString  `json:"variant_id"`
	Harness       sql.NullString  `json:"harness"`
	Skills        json.RawMessage `json:"skills"`
	TimeoutSec    int32           `json:"timeout_sec"`
	Enabled       bool            `json:"enabled"`
	UpdatedAt     time.Time       `json:"updated_at"`
	OldName       string          `json:"old_name"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error {
	_, err := q.db.ExecContext(ctx, updateSchedule,
		arg.NewName,
		arg.TriggerType,
		arg.TriggerConfig,
		arg.CronExpr,
		arg.Prompt,
		arg.GitUrl,
		arg.GitRef,
		arg.AgentImage,
		arg.Agent,
		arg.ProviderID,
		arg.ModelID,
		arg.VariantID,
		arg.Harness,
		arg.Skills,
		arg.TimeoutSec,
		arg.Enabled,
		arg.UpdatedAt,
		arg.OldName,
	)
	return err
}
