// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_artifacts.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const insertTaskArtifact = `-- name: InsertTaskArtifact :exec
INSERT IGNORE INTO chetter_task_artifacts (id, task_id, agent_session_id, session_run_id, artifact_type, repo, number, url, ref, sha, created_at, discovered_at, discovery_source)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTaskArtifactParams struct {
	ID              string         `json:"id"`
	TaskID          string         `json:"task_id"`
	AgentSessionID  sql.NullString `json:"agent_session_id"`
	SessionRunID    sql.NullString `json:"session_run_id"`
	ArtifactType    string         `json:"artifact_type"`
	Repo            string         `json:"repo"`
	Number          sql.NullInt32  `json:"number"`
	Url             sql.NullString `json:"url"`
	Ref             sql.NullString `json:"ref"`
	Sha             sql.NullString `json:"sha"`
	CreatedAt       time.Time      `json:"created_at"`
	DiscoveredAt    time.Time      `json:"discovered_at"`
	DiscoverySource string         `json:"discovery_source"`
}

func (q *Queries) InsertTaskArtifact(ctx context.Context, arg InsertTaskArtifactParams) error {
	_, err := q.db.ExecContext(ctx, insertTaskArtifact,
		arg.ID,
		arg.TaskID,
		arg.AgentSessionID,
		arg.SessionRunID,
		arg.ArtifactType,
		arg.Repo,
		arg.Number,
		arg.Url,
		arg.Ref,
		arg.Sha,
		arg.CreatedAt,
		arg.DiscoveredAt,
		arg.DiscoverySource,
	)
	return err
}

const listTaskArtifacts = `-- name: ListTaskArtifacts :many
SELECT id, task_id, agent_session_id, session_run_id, artifact_type, repo, number, url, ref, sha, created_at, discovered_at, discovery_source
FROM chetter_task_artifacts
WHERE (task_id = ? OR ? = '')
  AND (agent_session_id = ? OR ? = '')
  AND (artifact_type = ? OR ? = '')
  AND (repo = ? OR ? = '')
ORDER BY discovered_at DESC
LIMIT ? OFFSET ?
`

type ListTaskArtifactsParams struct {
	TaskID         string         `json:"task_id"`
	Column2        interface{}    `json:"column_2"`
	AgentSessionID sql.NullString `json:"agent_session_id"`
	Column4        interface{}    `json:"column_4"`
	ArtifactType   string         `json:"artifact_type"`
	Column6        interface{}    `json:"column_6"`
	Repo           string         `json:"repo"`
	Column8        interface{}    `json:"column_8"`
	Limit          int32          `json:"limit"`
	Offset         int32          `json:"offset"`
}

type ListTaskArtifactsRow struct {
	ID              string         `json:"id"`
	TaskID          string         `json:"task_id"`
	AgentSessionID  sql.NullString `json:"agent_session_id"`
	SessionRunID    sql.NullString `json:"session_run_id"`
	ArtifactType    string         `json:"artifact_type"`
	Repo            string         `json:"repo"`
	Number          sql.NullInt32  `json:"number"`
	Url             sql.NullString `json:"url"`
	Ref             sql.NullString `json:"ref"`
	Sha             sql.NullString `json:"sha"`
	CreatedAt       time.Time      `json:"created_at"`
	DiscoveredAt    time.Time      `json:"discovered_at"`
	DiscoverySource string         `json:"discovery_source"`
}

func (q *Queries) ListTaskArtifacts(ctx context.Context, arg ListTaskArtifactsParams) ([]ListTaskArtifactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskArtifacts,
		arg.TaskID,
		arg.Column2,
		arg.AgentSessionID,
		arg.Column4,
		arg.ArtifactType,
		arg.Column6,
		arg.Repo,
		arg.Column8,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskArtifactsRow{}
	for rows.Next() {
		var i ListTaskArtifactsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AgentSessionID,
			&i.SessionRunID,
			&i.ArtifactType,
			&i.Repo,
			&i.Number,
			&i.Url,
			&i.Ref,
			&i.Sha,
			&i.CreatedAt,
			&i.DiscoveredAt,
			&i.DiscoverySource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
