// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package repository

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const cancelTask = `-- name: CancelTask :execrows
UPDATE tasks
SET status = 'cancelled',
    error = ?,
    error_category = 'cancelled',
    failure_category = 'user_cancelled',
    failure_message = ?,
    ended_at = COALESCE(ended_at, ?),
    updated_at = ?
WHERE id = ? AND status IN ('pending', 'running')
`

type CancelTaskParams struct {
	Error          sql.NullString `json:"error"`
	FailureMessage sql.NullString `json:"failure_message"`
	EndedAt        sql.NullTime   `json:"ended_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ID             string         `json:"id"`
}

func (q *Queries) CancelTask(ctx context.Context, arg CancelTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelTask,
		arg.Error,
		arg.FailureMessage,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearPendingTasks = `-- name: ClearPendingTasks :execrows
UPDATE tasks
SET status = 'cancelled',
    error = ?,
    error_category = 'cancelled',
    failure_category = 'user_cancelled',
    failure_message = ?,
    ended_at = COALESCE(ended_at, ?),
    updated_at = ?
WHERE status = 'pending'
`

type ClearPendingTasksParams struct {
	Error          sql.NullString `json:"error"`
	FailureMessage sql.NullString `json:"failure_message"`
	EndedAt        sql.NullTime   `json:"ended_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) ClearPendingTasks(ctx context.Context, arg ClearPendingTasksParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearPendingTasks,
		arg.Error,
		arg.FailureMessage,
		arg.EndedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failExpiredLeases = `-- name: FailExpiredLeases :execrows
UPDATE tasks task
JOIN user_prompts prompt ON prompt.task_id = task.id
JOIN execution_attempts attempt ON attempt.user_prompt_id = prompt.id
SET task.status = 'error',
    task.error = attempt.error,
    task.error_category = 'timeout',
    task.failure_category = 'timeout',
    task.failure_message = CONCAT('Task timed out after ', COALESCE(attempt.error, 'lease expiry')),
    task.ended_at = ?,
    task.updated_at = ?
WHERE task.status = 'running'
  AND attempt.status = 'error'
  AND attempt.error_category = 'timeout'
  AND attempt.lease_expires_at IS NOT NULL
  AND attempt.lease_expires_at < ?
`

type FailExpiredLeasesParams struct {
	EndedAt        sql.NullTime `json:"ended_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	LeaseExpiresAt sql.NullTime `json:"lease_expires_at"`
}

func (q *Queries) FailExpiredLeases(ctx context.Context, arg FailExpiredLeasesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failExpiredLeases, arg.EndedAt, arg.UpdatedAt, arg.LeaseExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failPendingIsolationTasks = `-- name: FailPendingIsolationTasks :execrows
UPDATE tasks task
JOIN user_prompts prompt ON prompt.task_id = task.id
JOIN execution_attempts attempt ON attempt.user_prompt_id = prompt.id
SET task.status = 'error',
    task.error = 'no active runner enforces isolation (gVisor) for this task',
    task.error_category = 'isolation_unavailable',
    task.failure_category = 'harness_error',
    task.failure_message = 'No active runner enforces isolation (gVisor) for this task; it cannot run unsandboxed.',
    task.ended_at = ?,
    task.updated_at = ?
WHERE task.status = 'pending'
  AND attempt.status = 'error'
  AND attempt.error_category = 'isolation_unavailable'
`

type FailPendingIsolationTasksParams struct {
	EndedAt   sql.NullTime `json:"ended_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

// Marks pending tasks whose execution attempts failed with
// isolation_unavailable as terminal errors. Companion to
// FailPendingIsolationAttemptsWithoutCapableRunner (issue #291).
func (q *Queries) FailPendingIsolationTasks(ctx context.Context, arg FailPendingIsolationTasksParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failPendingIsolationTasks, arg.EndedAt, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLatestTaskEvent = `-- name: GetLatestTaskEvent :one
SELECT id, task_id, subject, status, payload, created_at, agent_session_id, user_prompt_id, execution_attempt_id, event_type FROM task_events
WHERE task_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestTaskEvent(ctx context.Context, taskID string) (TaskEvent, error) {
	row := q.db.QueryRowContext(ctx, getLatestTaskEvent, taskID)
	var i TaskEvent
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Subject,
		&i.Status,
		&i.Payload,
		&i.CreatedAt,
		&i.AgentSessionID,
		&i.UserPromptID,
		&i.ExecutionAttemptID,
		&i.EventType,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, status, prompt, git_url, git_ref, summary, error, created_at, updated_at, ended_at, team_id, trigger_name, trigger_type, max_attempts, search_text, error_category, submission_source, failure_category, failure_message, github_repo, github_installation_id, self_test_run_id, self_test_profile, self_test_check, self_test_nonce FROM tasks
WHERE id = ?
`

func (q *Queries) GetTaskByID(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Prompt,
		&i.GitUrl,
		&i.GitRef,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.TeamID,
		&i.TriggerName,
		&i.TriggerType,
		&i.MaxAttempts,
		&i.SearchText,
		&i.ErrorCategory,
		&i.SubmissionSource,
		&i.FailureCategory,
		&i.FailureMessage,
		&i.GithubRepo,
		&i.GithubInstallationID,
		&i.SelfTestRunID,
		&i.SelfTestProfile,
		&i.SelfTestCheck,
		&i.SelfTestNonce,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :exec
INSERT INTO tasks
    (id, team_id, status, prompt, git_url, git_ref, github_repo, github_installation_id, trigger_name, trigger_type, submission_source, self_test_run_id, self_test_profile, self_test_check, self_test_nonce, search_text, created_at, updated_at)
VALUES (?, ?, 'pending', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTaskParams struct {
	ID                   string         `json:"id"`
	TeamID               sql.NullString `json:"team_id"`
	Prompt               string         `json:"prompt"`
	GitUrl               sql.NullString `json:"git_url"`
	GitRef               sql.NullString `json:"git_ref"`
	GithubRepo           sql.NullString `json:"github_repo"`
	GithubInstallationID sql.NullInt64  `json:"github_installation_id"`
	TriggerName          sql.NullString `json:"trigger_name"`
	TriggerType          sql.NullString `json:"trigger_type"`
	SubmissionSource     string         `json:"submission_source"`
	SelfTestRunID        sql.NullString `json:"self_test_run_id"`
	SelfTestProfile      sql.NullString `json:"self_test_profile"`
	SelfTestCheck        sql.NullString `json:"self_test_check"`
	SelfTestNonce        sql.NullString `json:"self_test_nonce"`
	SearchText           sql.NullString `json:"search_text"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) error {
	_, err := q.db.ExecContext(ctx, insertTask,
		arg.ID,
		arg.TeamID,
		arg.Prompt,
		arg.GitUrl,
		arg.GitRef,
		arg.GithubRepo,
		arg.GithubInstallationID,
		arg.TriggerName,
		arg.TriggerType,
		arg.SubmissionSource,
		arg.SelfTestRunID,
		arg.SelfTestProfile,
		arg.SelfTestCheck,
		arg.SelfTestNonce,
		arg.SearchText,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listTasksBySelfTestRun = `-- name: ListTasksBySelfTestRun :many
SELECT id, status, prompt, git_url, git_ref, summary, error, created_at, updated_at, ended_at, team_id, trigger_name, trigger_type, max_attempts, search_text, error_category, submission_source, failure_category, failure_message, github_repo, github_installation_id, self_test_run_id, self_test_profile, self_test_check, self_test_nonce FROM tasks
WHERE self_test_run_id = ?
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListTasksBySelfTestRun(ctx context.Context, selfTestRunID sql.NullString) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksBySelfTestRun, selfTestRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedAt,
			&i.TeamID,
			&i.TriggerName,
			&i.TriggerType,
			&i.MaxAttempts,
			&i.SearchText,
			&i.ErrorCategory,
			&i.SubmissionSource,
			&i.FailureCategory,
			&i.FailureMessage,
			&i.GithubRepo,
			&i.GithubInstallationID,
			&i.SelfTestRunID,
			&i.SelfTestProfile,
			&i.SelfTestCheck,
			&i.SelfTestNonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, status, prompt, git_url, git_ref, summary, error, created_at, updated_at, ended_at, team_id, trigger_name, trigger_type, max_attempts, search_text, error_category, submission_source, failure_category, failure_message, github_repo, github_installation_id, self_test_run_id, self_test_profile, self_test_check, self_test_nonce FROM tasks
WHERE (? = '' OR tasks.status = ?)
  AND (COALESCE(?, '') = '' OR tasks.trigger_name = ?)
  AND (COALESCE(?, '') = '' OR EXISTS (
      SELECT 1 FROM agent_sessions session
      WHERE session.task_id = tasks.id AND session.agent = ?
  ))
ORDER BY tasks.created_at DESC
LIMIT ? OFFSET ?
`

type ListTasksByStatusParams struct {
	StatusFilter      string         `json:"status_filter"`
	TriggerNameFilter sql.NullString `json:"trigger_name_filter"`
	AgentFilter       sql.NullString `json:"agent_filter"`
	Limit             int32          `json:"limit"`
	Offset            int32          `json:"offset"`
}

func (q *Queries) ListTasksByStatus(ctx context.Context, arg ListTasksByStatusParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatus,
		arg.StatusFilter,
		arg.StatusFilter,
		arg.TriggerNameFilter,
		arg.TriggerNameFilter,
		arg.AgentFilter,
		arg.AgentFilter,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedAt,
			&i.TeamID,
			&i.TriggerName,
			&i.TriggerType,
			&i.MaxAttempts,
			&i.SearchText,
			&i.ErrorCategory,
			&i.SubmissionSource,
			&i.FailureCategory,
			&i.FailureMessage,
			&i.GithubRepo,
			&i.GithubInstallationID,
			&i.SelfTestRunID,
			&i.SelfTestProfile,
			&i.SelfTestCheck,
			&i.SelfTestNonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatusAndTeam = `-- name: ListTasksByStatusAndTeam :many
SELECT id, status, prompt, git_url, git_ref, summary, error, created_at, updated_at, ended_at, team_id, trigger_name, trigger_type, max_attempts, search_text, error_category, submission_source, failure_category, failure_message, github_repo, github_installation_id, self_test_run_id, self_test_profile, self_test_check, self_test_nonce FROM tasks
WHERE tasks.team_id = ?
  AND (? = '' OR tasks.status = ?)
  AND (COALESCE(?, '') = '' OR tasks.trigger_name = ?)
  AND (COALESCE(?, '') = '' OR EXISTS (
      SELECT 1 FROM agent_sessions session
      WHERE session.task_id = tasks.id AND session.agent = ?
  ))
ORDER BY tasks.created_at DESC
LIMIT ? OFFSET ?
`

type ListTasksByStatusAndTeamParams struct {
	TeamID            sql.NullString `json:"team_id"`
	StatusFilter      string         `json:"status_filter"`
	TriggerNameFilter sql.NullString `json:"trigger_name_filter"`
	AgentFilter       sql.NullString `json:"agent_filter"`
	Limit             int32          `json:"limit"`
	Offset            int32          `json:"offset"`
}

func (q *Queries) ListTasksByStatusAndTeam(ctx context.Context, arg ListTasksByStatusAndTeamParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatusAndTeam,
		arg.TeamID,
		arg.StatusFilter,
		arg.StatusFilter,
		arg.TriggerNameFilter,
		arg.TriggerNameFilter,
		arg.AgentFilter,
		arg.AgentFilter,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedAt,
			&i.TeamID,
			&i.TriggerName,
			&i.TriggerType,
			&i.MaxAttempts,
			&i.SearchText,
			&i.ErrorCategory,
			&i.SubmissionSource,
			&i.FailureCategory,
			&i.FailureMessage,
			&i.GithubRepo,
			&i.GithubInstallationID,
			&i.SelfTestRunID,
			&i.SelfTestProfile,
			&i.SelfTestCheck,
			&i.SelfTestNonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatusAndTeams = `-- name: ListTasksByStatusAndTeams :many
SELECT id, status, prompt, git_url, git_ref, summary, error, created_at, updated_at, ended_at, team_id, trigger_name, trigger_type, max_attempts, search_text, error_category, submission_source, failure_category, failure_message, github_repo, github_installation_id, self_test_run_id, self_test_profile, self_test_check, self_test_nonce FROM tasks
WHERE tasks.team_id IN (/*SLICE:team_ids*/?)
  AND (? = '' OR tasks.status = ?)
  AND (COALESCE(?, '') = '' OR tasks.trigger_name = ?)
  AND (COALESCE(?, '') = '' OR EXISTS (
      SELECT 1 FROM agent_sessions session
      WHERE session.task_id = tasks.id AND session.agent = ?
  ))
ORDER BY tasks.created_at DESC
LIMIT ? OFFSET ?
`

type ListTasksByStatusAndTeamsParams struct {
	TeamIds           []sql.NullString `json:"team_ids"`
	StatusFilter      string           `json:"status_filter"`
	TriggerNameFilter sql.NullString   `json:"trigger_name_filter"`
	AgentFilter       sql.NullString   `json:"agent_filter"`
	Limit             int32            `json:"limit"`
	Offset            int32            `json:"offset"`
}

func (q *Queries) ListTasksByStatusAndTeams(ctx context.Context, arg ListTasksByStatusAndTeamsParams) ([]Task, error) {
	query := listTasksByStatusAndTeams
	var queryParams []interface{}
	if len(arg.TeamIds) > 0 {
		for _, v := range arg.TeamIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:team_ids*/?", strings.Repeat(",?", len(arg.TeamIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:team_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.StatusFilter)
	queryParams = append(queryParams, arg.StatusFilter)
	queryParams = append(queryParams, arg.TriggerNameFilter)
	queryParams = append(queryParams, arg.TriggerNameFilter)
	queryParams = append(queryParams, arg.AgentFilter)
	queryParams = append(queryParams, arg.AgentFilter)
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedAt,
			&i.TeamID,
			&i.TriggerName,
			&i.TriggerType,
			&i.MaxAttempts,
			&i.SearchText,
			&i.ErrorCategory,
			&i.SubmissionSource,
			&i.FailureCategory,
			&i.FailureMessage,
			&i.GithubRepo,
			&i.GithubInstallationID,
			&i.SelfTestRunID,
			&i.SelfTestProfile,
			&i.SelfTestCheck,
			&i.SelfTestNonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskRunning = `-- name: MarkTaskRunning :execrows
UPDATE tasks
SET status = 'running',
    updated_at = ?
WHERE id = ? AND status = 'pending'
`

type MarkTaskRunningParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) MarkTaskRunning(ctx context.Context, arg MarkTaskRunningParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markTaskRunning, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pinTaskGitHubInstallation = `-- name: PinTaskGitHubInstallation :execrows
UPDATE tasks
SET github_installation_id = ?,
    updated_at = ?
WHERE id = ?
  AND github_installation_id IS NULL
`

type PinTaskGitHubInstallationParams struct {
	GithubInstallationID sql.NullInt64 `json:"github_installation_id"`
	UpdatedAt            time.Time     `json:"updated_at"`
	ID                   string        `json:"id"`
}

func (q *Queries) PinTaskGitHubInstallation(ctx context.Context, arg PinTaskGitHubInstallationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pinTaskGitHubInstallation, arg.GithubInstallationID, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueTaskForPrompt = `-- name: RequeueTaskForPrompt :execrows
UPDATE tasks
SET status = 'pending',
    summary = NULL,
    error = NULL,
    error_category = NULL,
    failure_category = NULL,
    failure_message = NULL,
    ended_at = NULL,
    updated_at = ?
WHERE id = ?
  AND status IN ('done', 'error', 'cancelled')
`

type RequeueTaskForPromptParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) RequeueTaskForPrompt(ctx context.Context, arg RequeueTaskForPromptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueTaskForPrompt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const searchTasks = `-- name: SearchTasks :many
SELECT id, status, prompt, git_url, git_ref, summary, error, created_at, updated_at, ended_at, team_id, trigger_name, trigger_type, max_attempts, search_text, error_category, submission_source, failure_category, failure_message, github_repo, github_installation_id, self_test_run_id, self_test_profile, self_test_check, self_test_nonce FROM tasks
WHERE (? = '' OR tasks.team_id = ?)
  AND (? = '' OR tasks.status = ?)
  AND (COALESCE(?, '') = '' OR tasks.trigger_name = ?)
  AND (COALESCE(?, '') = '' OR EXISTS (
      SELECT 1 FROM agent_sessions session
      WHERE session.task_id = tasks.id AND session.agent = ?
  ))
  AND (tasks.search_text LIKE CONCAT('%', ?, '%'))
ORDER BY tasks.created_at DESC
LIMIT ? OFFSET ?
`

type SearchTasksParams struct {
	TeamFilter        sql.NullString `json:"team_filter"`
	StatusFilter      string         `json:"status_filter"`
	TriggerNameFilter sql.NullString `json:"trigger_name_filter"`
	AgentFilter       sql.NullString `json:"agent_filter"`
	Search            interface{}    `json:"search"`
	Limit             int32          `json:"limit"`
	Offset            int32          `json:"offset"`
}

func (q *Queries) SearchTasks(ctx context.Context, arg SearchTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, searchTasks,
		arg.TeamFilter,
		arg.TeamFilter,
		arg.StatusFilter,
		arg.StatusFilter,
		arg.TriggerNameFilter,
		arg.TriggerNameFilter,
		arg.AgentFilter,
		arg.AgentFilter,
		arg.Search,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedAt,
			&i.TeamID,
			&i.TriggerName,
			&i.TriggerType,
			&i.MaxAttempts,
			&i.SearchText,
			&i.ErrorCategory,
			&i.SubmissionSource,
			&i.FailureCategory,
			&i.FailureMessage,
			&i.GithubRepo,
			&i.GithubInstallationID,
			&i.SelfTestRunID,
			&i.SelfTestProfile,
			&i.SelfTestCheck,
			&i.SelfTestNonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTasksByTeams = `-- name: SearchTasksByTeams :many
SELECT id, status, prompt, git_url, git_ref, summary, error, created_at, updated_at, ended_at, team_id, trigger_name, trigger_type, max_attempts, search_text, error_category, submission_source, failure_category, failure_message, github_repo, github_installation_id, self_test_run_id, self_test_profile, self_test_check, self_test_nonce FROM tasks
WHERE tasks.team_id IN (/*SLICE:team_ids*/?)
  AND (? = '' OR tasks.status = ?)
  AND (COALESCE(?, '') = '' OR tasks.trigger_name = ?)
  AND (COALESCE(?, '') = '' OR EXISTS (
      SELECT 1 FROM agent_sessions session
      WHERE session.task_id = tasks.id AND session.agent = ?
  ))
  AND (tasks.search_text LIKE CONCAT('%', ?, '%'))
ORDER BY tasks.created_at DESC
LIMIT ? OFFSET ?
`

type SearchTasksByTeamsParams struct {
	TeamIds           []sql.NullString `json:"team_ids"`
	StatusFilter      string           `json:"status_filter"`
	TriggerNameFilter sql.NullString   `json:"trigger_name_filter"`
	AgentFilter       sql.NullString   `json:"agent_filter"`
	Search            interface{}      `json:"search"`
	Limit             int32            `json:"limit"`
	Offset            int32            `json:"offset"`
}

func (q *Queries) SearchTasksByTeams(ctx context.Context, arg SearchTasksByTeamsParams) ([]Task, error) {
	query := searchTasksByTeams
	var queryParams []interface{}
	if len(arg.TeamIds) > 0 {
		for _, v := range arg.TeamIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:team_ids*/?", strings.Repeat(",?", len(arg.TeamIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:team_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.StatusFilter)
	queryParams = append(queryParams, arg.StatusFilter)
	queryParams = append(queryParams, arg.TriggerNameFilter)
	queryParams = append(queryParams, arg.TriggerNameFilter)
	queryParams = append(queryParams, arg.AgentFilter)
	queryParams = append(queryParams, arg.AgentFilter)
	queryParams = append(queryParams, arg.Search)
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedAt,
			&i.TeamID,
			&i.TriggerName,
			&i.TriggerType,
			&i.MaxAttempts,
			&i.SearchText,
			&i.ErrorCategory,
			&i.SubmissionSource,
			&i.FailureCategory,
			&i.FailureMessage,
			&i.GithubRepo,
			&i.GithubInstallationID,
			&i.SelfTestRunID,
			&i.SelfTestProfile,
			&i.SelfTestCheck,
			&i.SelfTestNonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskAggregateFromRunnerEvent = `-- name: UpdateTaskAggregateFromRunnerEvent :execrows
UPDATE tasks
SET status = ?,
    summary = ?,
    error = ?,
    error_category = COALESCE(NULLIF(?, ''), error_category),
    failure_category = COALESCE(NULLIF(?, ''), failure_category),
    failure_message = COALESCE(?, failure_message),
    ended_at = COALESCE(?, ended_at),
    updated_at = ?
WHERE id = ?
  AND (status = 'running' OR status = ?)
`

type UpdateTaskAggregateFromRunnerEventParams struct {
	Status          string         `json:"status"`
	Summary         sql.NullString `json:"summary"`
	Error           sql.NullString `json:"error"`
	ErrorCategory   interface{}    `json:"error_category"`
	FailureCategory interface{}    `json:"failure_category"`
	FailureMessage  sql.NullString `json:"failure_message"`
	EndedAt         sql.NullTime   `json:"ended_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateTaskAggregateFromRunnerEvent(ctx context.Context, arg UpdateTaskAggregateFromRunnerEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTaskAggregateFromRunnerEvent,
		arg.Status,
		arg.Summary,
		arg.Error,
		arg.ErrorCategory,
		arg.FailureCategory,
		arg.FailureMessage,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTaskSearchText = `-- name: UpdateTaskSearchText :exec
UPDATE tasks
SET search_text = CONCAT_WS(' ',
	COALESCE(prompt, ''), COALESCE(summary, ''), COALESCE(error, ''),
	COALESCE((SELECT agent FROM agent_sessions WHERE task_id = tasks.id ORDER BY sequence DESC LIMIT 1), ''),
	COALESCE((SELECT model_id FROM agent_sessions WHERE task_id = tasks.id ORDER BY sequence DESC LIMIT 1), ''),
	COALESCE(trigger_name, ''), COALESCE(git_url, ''), COALESCE(github_repo, '')
)
WHERE tasks.id = ?
`

func (q *Queries) UpdateTaskSearchText(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateTaskSearchText, id)
	return err
}
