// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package repository

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const cancelTask = `-- name: CancelTask :execrows
UPDATE chetter_tasks
SET status = 'cancelled',
    error = ?,
    error_category = 'cancelled',
    ended_at = COALESCE(ended_at, ?),
    updated_at = ?
WHERE id = ? AND status IN ('pending', 'running')
`

type CancelTaskParams struct {
	Error     sql.NullString `json:"error"`
	EndedAt   sql.NullTime   `json:"ended_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) CancelTask(ctx context.Context, arg CancelTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelTask,
		arg.Error,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearPendingTasks = `-- name: ClearPendingTasks :execrows
UPDATE chetter_tasks
SET status = 'cancelled',
    error = ?,
    error_category = 'cancelled',
    ended_at = COALESCE(ended_at, ?),
    updated_at = ?
WHERE status = 'pending'
`

type ClearPendingTasksParams struct {
	Error     sql.NullString `json:"error"`
	EndedAt   sql.NullTime   `json:"ended_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) ClearPendingTasks(ctx context.Context, arg ClearPendingTasksParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearPendingTasks, arg.Error, arg.EndedAt, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failExpiredLeases = `-- name: FailExpiredLeases :execrows
UPDATE chetter_tasks task
JOIN chetter_user_prompts prompt ON prompt.task_id = task.id
JOIN chetter_execution_attempts attempt ON attempt.user_prompt_id = prompt.id
SET task.status = 'error',
    task.error = attempt.error,
    task.error_category = 'timeout',
    task.ended_at = ?,
    task.updated_at = ?
WHERE task.status = 'running'
  AND attempt.status = 'error'
  AND attempt.error_category = 'timeout'
  AND attempt.lease_expires_at IS NOT NULL
  AND attempt.lease_expires_at < ?
`

type FailExpiredLeasesParams struct {
	EndedAt        sql.NullTime `json:"ended_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	LeaseExpiresAt sql.NullTime `json:"lease_expires_at"`
}

func (q *Queries) FailExpiredLeases(ctx context.Context, arg FailExpiredLeasesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failExpiredLeases, arg.EndedAt, arg.UpdatedAt, arg.LeaseExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLatestTaskEvent = `-- name: GetLatestTaskEvent :one
SELECT id, task_id, subject, status, payload, created_at, event_type, agent_session_id, user_prompt_id, execution_attempt_id FROM chetter_task_events
WHERE task_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestTaskEvent(ctx context.Context, taskID string) (ChetterTaskEvent, error) {
	row := q.db.QueryRowContext(ctx, getLatestTaskEvent, taskID)
	var i ChetterTaskEvent
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Subject,
		&i.Status,
		&i.Payload,
		&i.CreatedAt,
		&i.EventType,
		&i.AgentSessionID,
		&i.UserPromptID,
		&i.ExecutionAttemptID,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, status, prompt, git_url, git_ref, summary, error, created_at, updated_at, ended_at, team_id, trigger_name, trigger_type, max_attempts, checkpoint_after_success, error_category, submission_source, search_text FROM chetter_tasks
WHERE id = ?
`

func (q *Queries) GetTaskByID(ctx context.Context, id string) (ChetterTask, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i ChetterTask
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Prompt,
		&i.GitUrl,
		&i.GitRef,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.TeamID,
		&i.TriggerName,
		&i.TriggerType,
		&i.MaxAttempts,
		&i.CheckpointAfterSuccess,
		&i.ErrorCategory,
		&i.SubmissionSource,
		&i.SearchText,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :exec
INSERT INTO chetter_tasks
    (id, team_id, status, prompt, git_url, git_ref, trigger_name, trigger_type, submission_source, checkpoint_after_success, search_text, created_at, updated_at)
VALUES (?, ?, 'pending', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTaskParams struct {
	ID                     string         `json:"id"`
	TeamID                 sql.NullString `json:"team_id"`
	Prompt                 string         `json:"prompt"`
	GitUrl                 sql.NullString `json:"git_url"`
	GitRef                 sql.NullString `json:"git_ref"`
	TriggerName            sql.NullString `json:"trigger_name"`
	TriggerType            sql.NullString `json:"trigger_type"`
	SubmissionSource       string         `json:"submission_source"`
	CheckpointAfterSuccess bool           `json:"checkpoint_after_success"`
	SearchText             sql.NullString `json:"search_text"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) error {
	_, err := q.db.ExecContext(ctx, insertTask,
		arg.ID,
		arg.TeamID,
		arg.Prompt,
		arg.GitUrl,
		arg.GitRef,
		arg.TriggerName,
		arg.TriggerType,
		arg.SubmissionSource,
		arg.CheckpointAfterSuccess,
		arg.SearchText,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, status, prompt, git_url, git_ref, summary, error, created_at, updated_at, ended_at, team_id, trigger_name, trigger_type, max_attempts, checkpoint_after_success, error_category, submission_source, search_text FROM chetter_tasks
WHERE (? = '' OR status = ?)
  AND (COALESCE(?, '') = '' OR trigger_name = ?)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListTasksByStatusParams struct {
	StatusFilter      string         `json:"status_filter"`
	TriggerNameFilter sql.NullString `json:"trigger_name_filter"`
	Limit             int32          `json:"limit"`
	Offset            int32          `json:"offset"`
}

func (q *Queries) ListTasksByStatus(ctx context.Context, arg ListTasksByStatusParams) ([]ChetterTask, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatus,
		arg.StatusFilter,
		arg.StatusFilter,
		arg.TriggerNameFilter,
		arg.TriggerNameFilter,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterTask{}
	for rows.Next() {
		var i ChetterTask
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedAt,
			&i.TeamID,
			&i.TriggerName,
			&i.TriggerType,
			&i.MaxAttempts,
			&i.CheckpointAfterSuccess,
			&i.ErrorCategory,
			&i.SubmissionSource,
			&i.SearchText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatusAndTeam = `-- name: ListTasksByStatusAndTeam :many
SELECT id, status, prompt, git_url, git_ref, summary, error, created_at, updated_at, ended_at, team_id, trigger_name, trigger_type, max_attempts, checkpoint_after_success, error_category, submission_source, search_text FROM chetter_tasks
WHERE team_id = ?
  AND (? = '' OR status = ?)
  AND (COALESCE(?, '') = '' OR trigger_name = ?)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListTasksByStatusAndTeamParams struct {
	TeamID            sql.NullString `json:"team_id"`
	StatusFilter      string         `json:"status_filter"`
	TriggerNameFilter sql.NullString `json:"trigger_name_filter"`
	Limit             int32          `json:"limit"`
	Offset            int32          `json:"offset"`
}

func (q *Queries) ListTasksByStatusAndTeam(ctx context.Context, arg ListTasksByStatusAndTeamParams) ([]ChetterTask, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatusAndTeam,
		arg.TeamID,
		arg.StatusFilter,
		arg.StatusFilter,
		arg.TriggerNameFilter,
		arg.TriggerNameFilter,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterTask{}
	for rows.Next() {
		var i ChetterTask
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedAt,
			&i.TeamID,
			&i.TriggerName,
			&i.TriggerType,
			&i.MaxAttempts,
			&i.CheckpointAfterSuccess,
			&i.ErrorCategory,
			&i.SubmissionSource,
			&i.SearchText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatusAndTeams = `-- name: ListTasksByStatusAndTeams :many
SELECT id, status, prompt, git_url, git_ref, summary, error, created_at, updated_at, ended_at, team_id, trigger_name, trigger_type, max_attempts, checkpoint_after_success, error_category, submission_source, search_text FROM chetter_tasks
WHERE team_id IN (/*SLICE:team_ids*/?)
  AND (? = '' OR status = ?)
  AND (COALESCE(?, '') = '' OR trigger_name = ?)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListTasksByStatusAndTeamsParams struct {
	TeamIds           []sql.NullString `json:"team_ids"`
	StatusFilter      string           `json:"status_filter"`
	TriggerNameFilter sql.NullString   `json:"trigger_name_filter"`
	Limit             int32            `json:"limit"`
	Offset            int32            `json:"offset"`
}

func (q *Queries) ListTasksByStatusAndTeams(ctx context.Context, arg ListTasksByStatusAndTeamsParams) ([]ChetterTask, error) {
	query := listTasksByStatusAndTeams
	var queryParams []interface{}
	if len(arg.TeamIds) > 0 {
		for _, v := range arg.TeamIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:team_ids*/?", strings.Repeat(",?", len(arg.TeamIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:team_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.StatusFilter)
	queryParams = append(queryParams, arg.StatusFilter)
	queryParams = append(queryParams, arg.TriggerNameFilter)
	queryParams = append(queryParams, arg.TriggerNameFilter)
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterTask{}
	for rows.Next() {
		var i ChetterTask
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedAt,
			&i.TeamID,
			&i.TriggerName,
			&i.TriggerType,
			&i.MaxAttempts,
			&i.CheckpointAfterSuccess,
			&i.ErrorCategory,
			&i.SubmissionSource,
			&i.SearchText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskRunning = `-- name: MarkTaskRunning :execrows
UPDATE chetter_tasks
SET status = 'running',
    updated_at = ?
WHERE id = ? AND status = 'pending'
`

type MarkTaskRunningParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) MarkTaskRunning(ctx context.Context, arg MarkTaskRunningParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markTaskRunning, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueTaskForPrompt = `-- name: RequeueTaskForPrompt :execrows
UPDATE chetter_tasks
SET status = 'pending',
    summary = NULL,
    error = NULL,
    error_category = NULL,
    ended_at = NULL,
    updated_at = ?
WHERE id = ?
  AND status IN ('done', 'error', 'cancelled')
`

type RequeueTaskForPromptParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) RequeueTaskForPrompt(ctx context.Context, arg RequeueTaskForPromptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueTaskForPrompt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const searchTasks = `-- name: SearchTasks :many
SELECT id, status, prompt, git_url, git_ref, summary, error, created_at, updated_at, ended_at, team_id, trigger_name, trigger_type, max_attempts, checkpoint_after_success, error_category, submission_source, search_text FROM chetter_tasks
WHERE (? = '' OR team_id = ?)
  AND (? = '' OR status = ?)
  AND (COALESCE(?, '') = '' OR trigger_name = ?)
  AND (search_text LIKE CONCAT('%', ?, '%'))
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type SearchTasksParams struct {
	TeamFilter        sql.NullString `json:"team_filter"`
	StatusFilter      string         `json:"status_filter"`
	TriggerNameFilter sql.NullString `json:"trigger_name_filter"`
	Search            interface{}    `json:"search"`
	Limit             int32          `json:"limit"`
	Offset            int32          `json:"offset"`
}

func (q *Queries) SearchTasks(ctx context.Context, arg SearchTasksParams) ([]ChetterTask, error) {
	rows, err := q.db.QueryContext(ctx, searchTasks,
		arg.TeamFilter,
		arg.TeamFilter,
		arg.StatusFilter,
		arg.StatusFilter,
		arg.TriggerNameFilter,
		arg.TriggerNameFilter,
		arg.Search,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterTask{}
	for rows.Next() {
		var i ChetterTask
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedAt,
			&i.TeamID,
			&i.TriggerName,
			&i.TriggerType,
			&i.MaxAttempts,
			&i.CheckpointAfterSuccess,
			&i.ErrorCategory,
			&i.SubmissionSource,
			&i.SearchText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTasksByTeams = `-- name: SearchTasksByTeams :many
SELECT id, status, prompt, git_url, git_ref, summary, error, created_at, updated_at, ended_at, team_id, trigger_name, trigger_type, max_attempts, checkpoint_after_success, error_category, submission_source, search_text FROM chetter_tasks
WHERE team_id IN (/*SLICE:team_ids*/?)
  AND (? = '' OR status = ?)
  AND (COALESCE(?, '') = '' OR trigger_name = ?)
  AND (search_text LIKE CONCAT('%', ?, '%'))
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type SearchTasksByTeamsParams struct {
	TeamIds           []sql.NullString `json:"team_ids"`
	StatusFilter      string           `json:"status_filter"`
	TriggerNameFilter sql.NullString   `json:"trigger_name_filter"`
	Search            interface{}      `json:"search"`
	Limit             int32            `json:"limit"`
	Offset            int32            `json:"offset"`
}

func (q *Queries) SearchTasksByTeams(ctx context.Context, arg SearchTasksByTeamsParams) ([]ChetterTask, error) {
	query := searchTasksByTeams
	var queryParams []interface{}
	if len(arg.TeamIds) > 0 {
		for _, v := range arg.TeamIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:team_ids*/?", strings.Repeat(",?", len(arg.TeamIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:team_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.StatusFilter)
	queryParams = append(queryParams, arg.StatusFilter)
	queryParams = append(queryParams, arg.TriggerNameFilter)
	queryParams = append(queryParams, arg.TriggerNameFilter)
	queryParams = append(queryParams, arg.Search)
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterTask{}
	for rows.Next() {
		var i ChetterTask
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedAt,
			&i.TeamID,
			&i.TriggerName,
			&i.TriggerType,
			&i.MaxAttempts,
			&i.CheckpointAfterSuccess,
			&i.ErrorCategory,
			&i.SubmissionSource,
			&i.SearchText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskAggregateFromRunnerEvent = `-- name: UpdateTaskAggregateFromRunnerEvent :execrows
UPDATE chetter_tasks
SET status = ?,
    summary = ?,
    error = ?,
    error_category = COALESCE(NULLIF(?, ''), error_category),
    ended_at = COALESCE(?, ended_at),
    updated_at = ?
WHERE id = ?
  AND (status = 'running' OR status = ?)
`

type UpdateTaskAggregateFromRunnerEventParams struct {
	Status        string         `json:"status"`
	Summary       sql.NullString `json:"summary"`
	Error         sql.NullString `json:"error"`
	ErrorCategory interface{}    `json:"error_category"`
	EndedAt       sql.NullTime   `json:"ended_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateTaskAggregateFromRunnerEvent(ctx context.Context, arg UpdateTaskAggregateFromRunnerEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTaskAggregateFromRunnerEvent,
		arg.Status,
		arg.Summary,
		arg.Error,
		arg.ErrorCategory,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTaskSearchText = `-- name: UpdateTaskSearchText :exec
UPDATE chetter_tasks
SET search_text = CONCAT_WS(' ',
	COALESCE(prompt, ''), COALESCE(summary, ''), COALESCE(error, ''),
	COALESCE((SELECT agent FROM chetter_agent_sessions WHERE task_id = chetter_tasks.id ORDER BY sequence DESC LIMIT 1), ''),
	COALESCE((SELECT model_id FROM chetter_agent_sessions WHERE task_id = chetter_tasks.id ORDER BY sequence DESC LIMIT 1), ''),
	COALESCE(trigger_name, ''), COALESCE(git_url, '')
)
WHERE chetter_tasks.id = ?
`

func (q *Queries) UpdateTaskSearchText(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateTaskSearchText, id)
	return err
}
