// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: triggers.sql

package repository

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createTrigger = `-- name: CreateTrigger :exec
INSERT INTO chetter_triggers
    (id, team_id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, source_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, TRUE, ?, ?, ?)
`

type CreateTriggerParams struct {
	ID            string          `json:"id"`
	TeamID        sql.NullString  `json:"team_id"`
	Name          string          `json:"name"`
	TriggerType   string          `json:"trigger_type"`
	TriggerConfig json.RawMessage `json:"trigger_config"`
	CronExpr      string          `json:"cron_expr"`
	Prompt        string          `json:"prompt"`
	GitUrl        sql.NullString  `json:"git_url"`
	GitRef        sql.NullString  `json:"git_ref"`
	AgentImage    sql.NullString  `json:"agent_image"`
	Agent         sql.NullString  `json:"agent"`
	ProviderID    sql.NullString  `json:"provider_id"`
	ModelID       sql.NullString  `json:"model_id"`
	VariantID     sql.NullString  `json:"variant_id"`
	Harness       sql.NullString  `json:"harness"`
	Skills        json.RawMessage `json:"skills"`
	TimeoutSec    int32           `json:"timeout_sec"`
	SourceID      sql.NullString  `json:"source_id"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

func (q *Queries) CreateTrigger(ctx context.Context, arg CreateTriggerParams) error {
	_, err := q.db.ExecContext(ctx, createTrigger,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.TriggerType,
		arg.TriggerConfig,
		arg.CronExpr,
		arg.Prompt,
		arg.GitUrl,
		arg.GitRef,
		arg.AgentImage,
		arg.Agent,
		arg.ProviderID,
		arg.ModelID,
		arg.VariantID,
		arg.Harness,
		arg.Skills,
		arg.TimeoutSec,
		arg.SourceID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTrigger = `-- name: DeleteTrigger :exec
DELETE FROM chetter_triggers
WHERE name = ?
`

func (q *Queries) DeleteTrigger(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteTrigger, name)
	return err
}

const getTriggerByID = `-- name: GetTriggerByID :one
SELECT id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at, last_run_at, next_run_at, team_id, source_id FROM chetter_triggers
WHERE id = ?
`

func (q *Queries) GetTriggerByID(ctx context.Context, id string) (ChetterTrigger, error) {
	row := q.db.QueryRowContext(ctx, getTriggerByID, id)
	var i ChetterTrigger
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.CronExpr,
		&i.Prompt,
		&i.GitUrl,
		&i.GitRef,
		&i.AgentImage,
		&i.Agent,
		&i.ProviderID,
		&i.ModelID,
		&i.VariantID,
		&i.Harness,
		&i.Skills,
		&i.TimeoutSec,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.TeamID,
		&i.SourceID,
	)
	return i, err
}

const getTriggerByName = `-- name: GetTriggerByName :one
SELECT id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at, last_run_at, next_run_at, team_id, source_id FROM chetter_triggers
WHERE name = ?
`

func (q *Queries) GetTriggerByName(ctx context.Context, name string) (ChetterTrigger, error) {
	row := q.db.QueryRowContext(ctx, getTriggerByName, name)
	var i ChetterTrigger
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.CronExpr,
		&i.Prompt,
		&i.GitUrl,
		&i.GitRef,
		&i.AgentImage,
		&i.Agent,
		&i.ProviderID,
		&i.ModelID,
		&i.VariantID,
		&i.Harness,
		&i.Skills,
		&i.TimeoutSec,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.TeamID,
		&i.SourceID,
	)
	return i, err
}

const insertTriggerRun = `-- name: InsertTriggerRun :exec
INSERT INTO chetter_trigger_runs (id, trigger_id, team_id, task_id, status, triggered_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertTriggerRunParams struct {
	ID          string         `json:"id"`
	TriggerID   string         `json:"trigger_id"`
	TeamID      sql.NullString `json:"team_id"`
	TaskID      string         `json:"task_id"`
	Status      string         `json:"status"`
	TriggeredAt time.Time      `json:"triggered_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) InsertTriggerRun(ctx context.Context, arg InsertTriggerRunParams) error {
	_, err := q.db.ExecContext(ctx, insertTriggerRun,
		arg.ID,
		arg.TriggerID,
		arg.TeamID,
		arg.TaskID,
		arg.Status,
		arg.TriggeredAt,
		arg.CreatedAt,
	)
	return err
}

const listEnabledIssueTriggersByRepo = `-- name: ListEnabledIssueTriggersByRepo :many
SELECT id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at, last_run_at, next_run_at, team_id, source_id FROM chetter_triggers
WHERE enabled = TRUE
  AND trigger_type = 'issue'
  AND trigger_config->>'$.repo' = ?
ORDER BY created_at DESC
`

func (q *Queries) ListEnabledIssueTriggersByRepo(ctx context.Context, repo json.RawMessage) ([]ChetterTrigger, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledIssueTriggersByRepo, repo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterTrigger{}
	for rows.Next() {
		var i ChetterTrigger
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.CronExpr,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.Harness,
			&i.Skills,
			&i.TimeoutSec,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.TeamID,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledPRReviewTriggersByRepo = `-- name: ListEnabledPRReviewTriggersByRepo :many
SELECT id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at, last_run_at, next_run_at, team_id, source_id FROM chetter_triggers
WHERE enabled = TRUE
  AND trigger_type = 'pr_review'
  AND trigger_config->>'$.repo' = ?
ORDER BY created_at DESC
`

func (q *Queries) ListEnabledPRReviewTriggersByRepo(ctx context.Context, repo json.RawMessage) ([]ChetterTrigger, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledPRReviewTriggersByRepo, repo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterTrigger{}
	for rows.Next() {
		var i ChetterTrigger
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.CronExpr,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.Harness,
			&i.Skills,
			&i.TimeoutSec,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.TeamID,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledTriggers = `-- name: ListEnabledTriggers :many
SELECT id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at, last_run_at, next_run_at, team_id, source_id FROM chetter_triggers
WHERE enabled = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListEnabledTriggers(ctx context.Context) ([]ChetterTrigger, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledTriggers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterTrigger{}
	for rows.Next() {
		var i ChetterTrigger
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.CronExpr,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.Harness,
			&i.Skills,
			&i.TimeoutSec,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.TeamID,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledTriggersByTeam = `-- name: ListEnabledTriggersByTeam :many
SELECT id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at, last_run_at, next_run_at, team_id, source_id FROM chetter_triggers
WHERE team_id = ?
  AND enabled = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListEnabledTriggersByTeam(ctx context.Context, teamID sql.NullString) ([]ChetterTrigger, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledTriggersByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterTrigger{}
	for rows.Next() {
		var i ChetterTrigger
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.CronExpr,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.Harness,
			&i.Skills,
			&i.TimeoutSec,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.TeamID,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledTriggersByType = `-- name: ListEnabledTriggersByType :many
SELECT id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at, last_run_at, next_run_at, team_id, source_id FROM chetter_triggers
WHERE enabled = TRUE
  AND trigger_type = ?
ORDER BY created_at DESC
`

func (q *Queries) ListEnabledTriggersByType(ctx context.Context, triggerType string) ([]ChetterTrigger, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledTriggersByType, triggerType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterTrigger{}
	for rows.Next() {
		var i ChetterTrigger
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.CronExpr,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.Harness,
			&i.Skills,
			&i.TimeoutSec,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.TeamID,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTriggerRunsByTeam = `-- name: ListTriggerRunsByTeam :many
SELECT sr.id, sr.trigger_id, s.name AS trigger_name, sr.task_id, sr.status, sr.triggered_at, sr.created_at
FROM chetter_trigger_runs sr
JOIN chetter_triggers s ON s.id = sr.trigger_id
WHERE s.team_id = ?
ORDER BY sr.created_at DESC
LIMIT ? OFFSET ?
`

type ListTriggerRunsByTeamParams struct {
	TeamID sql.NullString `json:"team_id"`
	Limit  int32          `json:"limit"`
	Offset int32          `json:"offset"`
}

type ListTriggerRunsByTeamRow struct {
	ID          string    `json:"id"`
	TriggerID   string    `json:"trigger_id"`
	TriggerName string    `json:"trigger_name"`
	TaskID      string    `json:"task_id"`
	Status      string    `json:"status"`
	TriggeredAt time.Time `json:"triggered_at"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListTriggerRunsByTeam(ctx context.Context, arg ListTriggerRunsByTeamParams) ([]ListTriggerRunsByTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, listTriggerRunsByTeam, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTriggerRunsByTeamRow{}
	for rows.Next() {
		var i ListTriggerRunsByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TriggerID,
			&i.TriggerName,
			&i.TaskID,
			&i.Status,
			&i.TriggeredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTriggerRunsByTrigger = `-- name: ListTriggerRunsByTrigger :many
SELECT sr.id, sr.trigger_id, s.name AS trigger_name, sr.task_id, sr.status, sr.triggered_at, sr.created_at
FROM chetter_trigger_runs sr
JOIN chetter_triggers s ON s.id = sr.trigger_id
WHERE sr.trigger_id = ?
ORDER BY sr.created_at DESC
LIMIT ? OFFSET ?
`

type ListTriggerRunsByTriggerParams struct {
	TriggerID string `json:"trigger_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type ListTriggerRunsByTriggerRow struct {
	ID          string    `json:"id"`
	TriggerID   string    `json:"trigger_id"`
	TriggerName string    `json:"trigger_name"`
	TaskID      string    `json:"task_id"`
	Status      string    `json:"status"`
	TriggeredAt time.Time `json:"triggered_at"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListTriggerRunsByTrigger(ctx context.Context, arg ListTriggerRunsByTriggerParams) ([]ListTriggerRunsByTriggerRow, error) {
	rows, err := q.db.QueryContext(ctx, listTriggerRunsByTrigger, arg.TriggerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTriggerRunsByTriggerRow{}
	for rows.Next() {
		var i ListTriggerRunsByTriggerRow
		if err := rows.Scan(
			&i.ID,
			&i.TriggerID,
			&i.TriggerName,
			&i.TaskID,
			&i.Status,
			&i.TriggeredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTriggers = `-- name: ListTriggers :many
SELECT id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at, last_run_at, next_run_at, team_id, source_id FROM chetter_triggers
ORDER BY created_at DESC
`

func (q *Queries) ListTriggers(ctx context.Context) ([]ChetterTrigger, error) {
	rows, err := q.db.QueryContext(ctx, listTriggers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterTrigger{}
	for rows.Next() {
		var i ChetterTrigger
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.CronExpr,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.Harness,
			&i.Skills,
			&i.TimeoutSec,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.TeamID,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTriggersByTeam = `-- name: ListTriggersByTeam :many
SELECT id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, created_at, updated_at, last_run_at, next_run_at, team_id, source_id FROM chetter_triggers
WHERE team_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListTriggersByTeam(ctx context.Context, teamID sql.NullString) ([]ChetterTrigger, error) {
	rows, err := q.db.QueryContext(ctx, listTriggersByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChetterTrigger{}
	for rows.Next() {
		var i ChetterTrigger
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.CronExpr,
			&i.Prompt,
			&i.GitUrl,
			&i.GitRef,
			&i.AgentImage,
			&i.Agent,
			&i.ProviderID,
			&i.ModelID,
			&i.VariantID,
			&i.Harness,
			&i.Skills,
			&i.TimeoutSec,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.TeamID,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTriggerLastRun = `-- name: SetTriggerLastRun :exec
UPDATE chetter_triggers
SET last_run_at = ?, updated_at = ?
WHERE id = ?
`

type SetTriggerLastRunParams struct {
	LastRunAt sql.NullTime `json:"last_run_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) SetTriggerLastRun(ctx context.Context, arg SetTriggerLastRunParams) error {
	_, err := q.db.ExecContext(ctx, setTriggerLastRun, arg.LastRunAt, arg.UpdatedAt, arg.ID)
	return err
}

const setTriggerNextRun = `-- name: SetTriggerNextRun :exec
UPDATE chetter_triggers
SET next_run_at = ?, updated_at = ?
WHERE id = ?
`

type SetTriggerNextRunParams struct {
	NextRunAt sql.NullTime `json:"next_run_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) SetTriggerNextRun(ctx context.Context, arg SetTriggerNextRunParams) error {
	_, err := q.db.ExecContext(ctx, setTriggerNextRun, arg.NextRunAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateTrigger = `-- name: UpdateTrigger :exec
UPDATE chetter_triggers
SET name = ?, trigger_type = ?, trigger_config = ?, cron_expr = ?, prompt = ?,
    git_url = ?, git_ref = ?, agent_image = ?,
    agent = ?, provider_id = ?, model_id = ?, variant_id = ?,
    harness = ?, skills = ?, timeout_sec = ?, enabled = ?,
    updated_at = ?
WHERE name = ?
`

type UpdateTriggerParams struct {
	NewName       string          `json:"new_name"`
	TriggerType   string          `json:"trigger_type"`
	TriggerConfig json.RawMessage `json:"trigger_config"`
	CronExpr      string          `json:"cron_expr"`
	Prompt        string          `json:"prompt"`
	GitUrl        sql.NullString  `json:"git_url"`
	GitRef        sql.NullString  `json:"git_ref"`
	AgentImage    sql.NullString  `json:"agent_image"`
	Agent         sql.NullString  `json:"agent"`
	ProviderID    sql.NullString  `json:"provider_id"`
	ModelID       sql.NullString  `json:"model_id"`
	VariantID     sql.NullString  `json:"variant_id"`
	Harness       sql.NullString  `json:"harness"`
	Skills        json.RawMessage `json:"skills"`
	TimeoutSec    int32           `json:"timeout_sec"`
	Enabled       bool            `json:"enabled"`
	UpdatedAt     time.Time       `json:"updated_at"`
	OldName       string          `json:"old_name"`
}

func (q *Queries) UpdateTrigger(ctx context.Context, arg UpdateTriggerParams) error {
	_, err := q.db.ExecContext(ctx, updateTrigger,
		arg.NewName,
		arg.TriggerType,
		arg.TriggerConfig,
		arg.CronExpr,
		arg.Prompt,
		arg.GitUrl,
		arg.GitRef,
		arg.AgentImage,
		arg.Agent,
		arg.ProviderID,
		arg.ModelID,
		arg.VariantID,
		arg.Harness,
		arg.Skills,
		arg.TimeoutSec,
		arg.Enabled,
		arg.UpdatedAt,
		arg.OldName,
	)
	return err
}

const upsertTrigger = `-- name: UpsertTrigger :exec
INSERT INTO chetter_triggers
    (id, team_id, name, trigger_type, trigger_config, cron_expr, prompt, git_url, git_ref, agent_image, agent, provider_id, model_id, variant_id, harness, skills, timeout_sec, enabled, source_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    trigger_type = VALUES(trigger_type),
    trigger_config = VALUES(trigger_config),
    cron_expr = VALUES(cron_expr),
    prompt = VALUES(prompt),
    git_url = VALUES(git_url),
    git_ref = VALUES(git_ref),
    agent_image = VALUES(agent_image),
    agent = VALUES(agent),
    provider_id = VALUES(provider_id),
    model_id = VALUES(model_id),
    variant_id = VALUES(variant_id),
    harness = VALUES(harness),
    skills = VALUES(skills),
    timeout_sec = VALUES(timeout_sec),
    enabled = VALUES(enabled),
    source_id = VALUES(source_id),
    updated_at = VALUES(updated_at)
`

type UpsertTriggerParams struct {
	ID            string          `json:"id"`
	TeamID        sql.NullString  `json:"team_id"`
	Name          string          `json:"name"`
	TriggerType   string          `json:"trigger_type"`
	TriggerConfig json.RawMessage `json:"trigger_config"`
	CronExpr      string          `json:"cron_expr"`
	Prompt        string          `json:"prompt"`
	GitUrl        sql.NullString  `json:"git_url"`
	GitRef        sql.NullString  `json:"git_ref"`
	AgentImage    sql.NullString  `json:"agent_image"`
	Agent         sql.NullString  `json:"agent"`
	ProviderID    sql.NullString  `json:"provider_id"`
	ModelID       sql.NullString  `json:"model_id"`
	VariantID     sql.NullString  `json:"variant_id"`
	Harness       sql.NullString  `json:"harness"`
	Skills        json.RawMessage `json:"skills"`
	TimeoutSec    int32           `json:"timeout_sec"`
	Enabled       bool            `json:"enabled"`
	SourceID      sql.NullString  `json:"source_id"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

func (q *Queries) UpsertTrigger(ctx context.Context, arg UpsertTriggerParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrigger,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.TriggerType,
		arg.TriggerConfig,
		arg.CronExpr,
		arg.Prompt,
		arg.GitUrl,
		arg.GitRef,
		arg.AgentImage,
		arg.Agent,
		arg.ProviderID,
		arg.ModelID,
		arg.VariantID,
		arg.Harness,
		arg.Skills,
		arg.TimeoutSec,
		arg.Enabled,
		arg.SourceID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
