package webhook

import (
	"testing"
)

func TestTriggerAllowsBotComments(t *testing.T) {
	tests := []struct {
		name    string
		trigger ReviewTrigger
		want    bool
	}{
		{
			name:    "empty event does not allow bot comments",
			trigger: ReviewTrigger{Event: ""},
			want:    false,
		},
		{
			name:    "opened event does not allow bot comments",
			trigger: ReviewTrigger{Event: "opened"},
			want:    false,
		},
		{
			name:    "comment event does not allow bot comments",
			trigger: ReviewTrigger{Event: "comment"},
			want:    false,
		},
		{
			name:    "comment event with bot_comments:true allows bot comments",
			trigger: ReviewTrigger{Event: "comment bot_comments:true"},
			want:    true,
		},
		{
			name:    "opened event with bot_comments:true allows bot comments",
			trigger: ReviewTrigger{Event: "opened bot_comments:true"},
			want:    true,
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := triggerAllowsBotComments(tc.trigger); got != tc.want {
				t.Errorf("triggerAllowsBotComments = %v, want %v", got, tc.want)
			}
		})
	}
}

func TestTriggerMatchesLabels(t *testing.T) {
	tests := []struct {
		name          string
		triggerLabels []string
		issueLabels   []string
		want          bool
	}{
		{
			name:          "no trigger labels matches any issue",
			triggerLabels: nil,
			issueLabels:   []string{"bug"},
			want:          true,
		},
		{
			name:          "empty trigger labels matches any issue",
			triggerLabels: []string{},
			issueLabels:   []string{"enhancement"},
			want:          true,
		},
		{
			name:          "exact match",
			triggerLabels: []string{"bug"},
			issueLabels:   []string{"bug", "enhancement"},
			want:          true,
		},
		{
			name:          "case insensitive match",
			triggerLabels: []string{"Bug"},
			issueLabels:   []string{"bug"},
			want:          true,
		},
		{
			name:          "no match",
			triggerLabels: []string{"bug"},
			issueLabels:   []string{"enhancement"},
			want:          false,
		},
		{
			name:          "multiple trigger labels - one matches",
			triggerLabels: []string{"bug", "urgent"},
			issueLabels:   []string{"enhancement", "urgent"},
			want:          true,
		},
		{
			name:          "no issue labels",
			triggerLabels: []string{"bug"},
			issueLabels:   nil,
			want:          false,
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := triggerMatchesLabels(tc.triggerLabels, tc.issueLabels); got != tc.want {
				t.Errorf("triggerMatchesLabels = %v, want %v", got, tc.want)
			}
		})
	}
}

func TestTaskIDFooterRegex(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{
			name:  "standard footer with task ID",
			input: "Agent: build | Model: glm-5.1 | Task: task_abc123def456 | Runner: image:tag",
			want:  "task_abc123def456",
		},
		{
			name:  "footer at end of PR body",
			input: "Some PR description\n\n---\nGenerated by Chetter\nAgent: build | Model: glm | Task: task_73dffe5542dd6e65f34ee4dfd9f4ec25 | Runner: img (sha256:abc)",
			want:  "task_73dffe5542dd6e65f34ee4dfd9f4ec25",
		},
		{
			name:  "no task ID in text",
			input: "This is a regular comment with no footer",
			want:  "",
		},
		{
			name:  "task ID without prefix",
			input: "Task: abc123",
			want:  "",
		},
		{
			name:  "multiple task IDs — returns first match",
			input: "Task: task_aaa111 | Task: task_bbb222",
			want:  "task_aaa111",
		},
		{
			name:  "empty text",
			input: "",
			want:  "",
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			matches := taskIDFooterRe.FindStringSubmatch(tc.input)
			if tc.want == "" {
				if len(matches) >= 2 && matches[1] != "" {
					t.Errorf("expected no match, got %q", matches[1])
				}
				return
			}
			if len(matches) < 2 || matches[1] != tc.want {
				t.Errorf("expected %q, got %v", tc.want, matches)
			}
		})
	}
}
