// Package webhook tests for the GitHub webhook handler and helpers.
package webhook

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"runtime"
	"strings"
	"testing"
	"time"
)

type recordingTaskSubmitter struct {
	reviews []ReviewContext
	tasks   []SubmitTaskRequest
}

func (r *recordingTaskSubmitter) SubmitReviewTask(_ context.Context, review ReviewContext) error {
	r.reviews = append(r.reviews, review)
	return nil
}

func (r *recordingTaskSubmitter) SubmitTask(_ context.Context, req SubmitTaskRequest) (any, error) {
	r.tasks = append(r.tasks, req)
	return nil, nil
}

type staticTriggerResolver struct {
	pr    []ReviewTrigger
	issue []ReviewTrigger
}

type recordingDeliveryStore struct {
	failedID  string
	failedErr string
}

func (*recordingDeliveryStore) RecordDelivery(context.Context, RecordDeliveryParams) (bool, error) {
	return true, nil
}

func (*recordingDeliveryStore) MarkDeliveryProcessing(context.Context, string) error { return nil }
func (*recordingDeliveryStore) MarkDeliveryCompleted(context.Context, string) error  { return nil }

func (s *recordingDeliveryStore) MarkDeliveryFailed(_ context.Context, deliveryID, errMsg string) error {
	s.failedID = deliveryID
	s.failedErr = errMsg
	return nil
}

func (r staticTriggerResolver) ListEnabledPRReviewTriggersByRepo(context.Context, string) ([]ReviewTrigger, error) {
	return r.pr, nil
}

func (r staticTriggerResolver) ListEnabledIssueTriggersByRepo(context.Context, string) ([]ReviewTrigger, error) {
	return r.issue, nil
}

// TestVerifySignature checks the HMAC-SHA256 verification with a known
// payload/secret/signature triple. The known vector was generated by the
// GitHub webhook test suite.
func TestVerifySignature(t *testing.T) {
	secret := "It's a Secret to Everybody"
	payload := []byte("Hello, World!")
	// Known GitHub signature for the above payload/secret.
	expected := "sha256=757107ea0eb2509fc211221cce984b8a37570b6d7586c22c46f4379c8b043e17"

	if !verifySignature(secret, payload, expected) {
		t.Fatal("verifySignature returned false for known valid signature")
	}
}

func TestVerifySignature_Invalid(t *testing.T) {
	tests := []struct {
		name   string
		secret string
		header string
		body   []byte
		want   bool
	}{
		{"empty secret", "", "sha256=abc", []byte("body"), false},
		{"empty header", "secret", "", []byte("body"), false},
		{"wrong prefix", "secret", "md5=abc", []byte("body"), false},
		{"tampered body", "secret", "sha256=" + strings.Repeat("a", 64), []byte("body"), false},
		{"wrong secret", "secret", "sha256=" + strings.Repeat("b", 64), []byte("body"), false},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := verifySignature(tc.secret, tc.body, tc.header); got != tc.want {
				t.Errorf("verifySignature = %v, want %v", got, tc.want)
			}
		})
	}
}

func TestSupportedEventsParseInstallation(t *testing.T) {
	tests := []struct {
		name  string
		parse func([]byte) (int64, error)
	}{
		{"pull_request", func(body []byte) (int64, error) {
			var event PullRequestEvent
			err := json.Unmarshal(body, &event)
			return event.Installation.ID, err
		}},
		{"issues", func(body []byte) (int64, error) {
			var event IssueEvent
			err := json.Unmarshal(body, &event)
			return event.Installation.ID, err
		}},
		{"issue_comment", func(body []byte) (int64, error) {
			var event IssueCommentEvent
			err := json.Unmarshal(body, &event)
			return event.Installation.ID, err
		}},
		{"pull_request_review", func(body []byte) (int64, error) {
			var event PullRequestReviewEvent
			err := json.Unmarshal(body, &event)
			return event.Installation.ID, err
		}},
		{"pull_request_review_comment", func(body []byte) (int64, error) {
			var event PullRequestReviewCommentEvent
			err := json.Unmarshal(body, &event)
			return event.Installation.ID, err
		}},
	}
	body := []byte(`{"installation":{"id":222}}`)
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			id, err := tc.parse(body)
			if err != nil || id != 222 {
				t.Fatalf("installation = %d, err=%v", id, err)
			}
		})
	}
}

func TestSupportedEventsFailClosedWithoutInstallation(t *testing.T) {
	h := &Handler{github: newTestManager(t, "")}
	for _, event := range []string{
		EventTypePullRequest,
		EventTypeIssues,
		EventTypeIssueComment,
		EventTypePullRequestReview,
		EventTypePullRequestReviewComment,
	} {
		t.Run(event, func(t *testing.T) {
			err := h.runDelivery(event, []byte(`{"action":"ignored"}`), "delivery-missing")
			if err == nil || !strings.Contains(err.Error(), "missing installation.id") {
				t.Fatalf("runDelivery error = %v", err)
			}
		})
	}
}

func TestProcessDeliveryPersistsHandlerErrorForRetry(t *testing.T) {
	store := &recordingDeliveryStore{}
	h := &Handler{github: newTestManager(t, ""), deliveryStore: store}
	err := h.ProcessDelivery(EventTypeIssues, []byte(`{"action":"opened"}`), "delivery-retry")
	if err == nil || !strings.Contains(err.Error(), "missing installation.id") {
		t.Fatalf("ProcessDelivery error = %v", err)
	}
	if store.failedID != "delivery-retry" || !strings.Contains(store.failedErr, "missing installation.id") {
		t.Fatalf("failed delivery = %q, error=%q", store.failedID, store.failedErr)
	}
}

func TestIssueWebhookSubmitsTrustedMetadataWithoutToken(t *testing.T) {
	var tokenCalls int
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if strings.Contains(r.URL.Path, "/access_tokens") {
			tokenCalls++
		}
		http.Error(w, "unexpected GitHub request", http.StatusInternalServerError)
	}))
	defer server.Close()
	submitter := &recordingTaskSubmitter{}
	h := &Handler{
		github:    newTestManager(t, server.URL),
		submitter: submitter,
		triggers:  staticTriggerResolver{issue: []ReviewTrigger{{Name: "triage", Event: "opened"}}},
	}
	body := []byte(`{
		"action":"opened",
		"installation":{"id":222},
		"repository":{"full_name":"base/repo"},
		"issue":{"number":7,"title":"bug","body":"details","html_url":"https://github.com/base/repo/issues/7"}
	}`)
	if err := h.handleIssues(body, "delivery-issue"); err != nil {
		t.Fatal(err)
	}
	if len(submitter.tasks) != 1 {
		t.Fatalf("submitted tasks = %d, want 1", len(submitter.tasks))
	}
	req := submitter.tasks[0]
	if req.GitHubRepo != "base/repo" || req.GitHubInstallationID != 222 {
		t.Fatalf("task GitHub metadata = %q/%d", req.GitHubRepo, req.GitHubInstallationID)
	}
	if _, ok := req.Env["GITHUB_TOKEN"]; ok {
		t.Fatal("webhook task environment contains GITHUB_TOKEN")
	}
	if tokenCalls != 0 {
		t.Fatalf("installation token exchanges = %d, want 0", tokenCalls)
	}
}

func TestPullRequestWebhookRoutesAPICallsAndPinsBaseRepo(t *testing.T) {
	var tokenCalls int
	var authenticatedPaths []string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/app":
			_, _ = w.Write([]byte(`{"slug":"chetterbot"}`))
		case "/app/installations/222/access_tokens":
			tokenCalls++
			writeTokenResponse(w, "token-222")
		case "/repos/base/repo/issues/9/labels":
			if r.Header.Get("Authorization") != "Bearer token-222" {
				t.Errorf("authorization = %q", r.Header.Get("Authorization"))
			}
			authenticatedPaths = append(authenticatedPaths, r.Method+" "+r.URL.Path)
			if r.Method == http.MethodGet {
				_, _ = w.Write([]byte(`[]`))
				return
			}
			w.WriteHeader(http.StatusOK)
		default:
			http.NotFound(w, r)
		}
	}))
	defer server.Close()
	submitter := &recordingTaskSubmitter{}
	h := &Handler{
		github:    newTestManager(t, server.URL),
		submitter: submitter,
		triggers:  staticTriggerResolver{pr: []ReviewTrigger{{Name: "review", TriggerType: "pr_review"}}},
	}
	body := []byte(`{
		"action":"opened",
		"number":9,
		"installation":{"id":222},
		"repository":{"full_name":"base/repo"},
		"pull_request":{
			"number":9,
			"user":{"login":"chetterbot[bot]"},
			"base":{"ref":"main","repo":{"full_name":"base/repo"}},
			"head":{"ref":"feature","repo":{"full_name":"fork/repo","clone_url":"https://github.com/fork/repo.git"}}
		}
	}`)
	if err := h.handlePullRequest(body, "delivery-pr"); err != nil {
		t.Fatal(err)
	}
	if tokenCalls != 1 || len(authenticatedPaths) != 2 {
		t.Fatalf("token calls=%d authenticated paths=%v", tokenCalls, authenticatedPaths)
	}
	if len(submitter.reviews) != 1 {
		t.Fatalf("submitted reviews = %d, want 1", len(submitter.reviews))
	}
	review := submitter.reviews[0]
	if review.Repo != "base/repo" || review.GitHubInstallationID != 222 {
		t.Fatalf("review metadata = %q/%d", review.Repo, review.GitHubInstallationID)
	}
	if review.HeadCloneURL != "https://github.com/fork/repo.git" {
		t.Fatalf("head clone URL = %q", review.HeadCloneURL)
	}
}

// TestRecentDeliveries_SeenAndDeduplicate checks that the same delivery ID
// is only counted once within the TTL.
func TestRecentDeliveries_SeenAndDeduplicate(t *testing.T) {
	r := NewRecentDeliveries(time.Hour, 100)

	if r.Seen("delivery-1") {
		t.Fatal("first Seen should return false")
	}
	if !r.Seen("delivery-1") {
		t.Fatal("second Seen for same ID should return true")
	}
	if r.Seen("delivery-2") {
		t.Fatal("first Seen for new ID should return false")
	}
	if r.Size() != 2 {
		t.Errorf("expected 2 entries, got %d", r.Size())
	}
}

func TestRecentDeliveries_EmptyID(t *testing.T) {
	r := NewRecentDeliveries(time.Hour, 100)
	if r.Seen("") {
		t.Fatal("empty ID should never be seen")
	}
}

func TestRecentDeliveries_Expiry(t *testing.T) {
	r := NewRecentDeliveries(50*time.Millisecond, 100)
	r.Seen("delivery-1")
	// After the TTL expires, the same ID should be treated as new.
	time.Sleep(80 * time.Millisecond)
	if r.Seen("delivery-1") {
		t.Fatal("expired delivery should be treated as new")
	}
}

func TestRecentDeliveries_MaxSize(t *testing.T) {
	r := NewRecentDeliveries(time.Hour, 2)
	r.Seen("delivery-1")
	r.Seen("delivery-2")
	r.Seen("delivery-3")

	if got := r.Size(); got != 2 {
		t.Fatalf("expected 2 entries after size eviction, got %d", got)
	}
	if r.Seen("delivery-1") {
		t.Fatal("oldest delivery should have been evicted")
	}
}

// TestShouldReview_FilterLogic checks the filter that determines whether a
// PR should be reviewed, using a mocked GitHub client.
func TestShouldReview_FilterLogic(t *testing.T) {
	cases := []struct {
		name        string
		pr          PullRequest
		repo        string
		wantOK      bool
		wantTrigger string
	}{
		{
			name: "label triggers review",
			pr: PullRequest{
				Labels: []Label{{Name: "chetter-review"}},
			},
			repo:   "org/repo",
			wantOK: true, wantTrigger: "labeled",
		},
		{
			name: "fork triggers review",
			pr: PullRequest{
				Head: PRBranch{
					Ref: "feat",
					Repo: struct {
						FullName string `json:"full_name"`
						CloneURL string `json:"clone_url"`
					}{
						FullName: "fork/repo",
						CloneURL: "https://github.com/fork/repo.git",
					},
				},
			},
			repo:   "org/repo",
			wantOK: true, wantTrigger: "fork",
		},
		{
			name:   "internal PR with no label or action - no review",
			pr:     PullRequest{},
			repo:   "org/repo",
			wantOK: false, wantTrigger: "",
		},
		{
			name:   "opened triggers review",
			pr:     PullRequest{},
			repo:   "org/repo",
			wantOK: true, wantTrigger: "opened",
		},
		{
			name:   "synchronize triggers review",
			pr:     PullRequest{},
			repo:   "org/repo",
			wantOK: true, wantTrigger: "synchronize",
		},
		{
			name: "existing review label does not override synchronize",
			pr: PullRequest{
				Labels: []Label{{Name: ChetterReviewLabel}},
			},
			repo:   "org/repo",
			wantOK: true, wantTrigger: "synchronize",
		},
		{
			name:   "reopened triggers review",
			pr:     PullRequest{},
			repo:   "org/repo",
			wantOK: true, wantTrigger: "reopened",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			ev := PullRequestEvent{
				Action:      "opened",
				PullRequest: tc.pr,
			}
			if tc.name == "internal PR with no label or action - no review" {
				ev.Action = ""
			}
			if tc.name == "label triggers review" {
				ev.Action = "labeled"
			}
			if tc.name == "synchronize triggers review" {
				ev.Action = "synchronize"
			}
			if tc.name == "existing review label does not override synchronize" {
				ev.Action = "synchronize"
			}
			if tc.name == "reopened triggers review" {
				ev.Action = "reopened"
			}
			trigger := triggerActionFromPR(ev, tc.repo)
			ok := trigger != ""
			if ok != tc.wantOK {
				t.Errorf("triggerActionFromPR returned ok=%v, want %v", ok, tc.wantOK)
			}
			if trigger != tc.wantTrigger {
				t.Errorf("triggerActionFromPR returned trigger=%q, want %q", trigger, tc.wantTrigger)
			}
		})
	}
}

// TestBuildReviewTaskRequest checks that the review task request is populated
// correctly from a ReviewContext.
func TestBuildReviewTaskRequest(t *testing.T) {
	review := ReviewContext{
		Trigger:              "file-pattern",
		Repo:                 "chetter/chetter",
		PRNumber:             42,
		BaseRef:              "main",
		HeadRef:              "feat/some-thing",
		HeadCloneURL:         "https://github.com/someone/myapp.git",
		CommentAuthor:        "",
		GitHubInstallationID: 321,
		Agent:                "pr-reviewer",
		ProviderID:           "opencode",
		ModelID:              "minimax-m3",
		TimeoutSec:           3600,
		SessionMode:          "resumable",
		PauseReason:          "waiting_for_pr_feedback",
		TTLHours:             48,
	}
	req := buildReviewTaskRequest(review)

	if req.Prompt == "" {
		t.Fatal("Prompt should be non-empty")
	}
	if req.GitURL != review.HeadCloneURL {
		t.Errorf("GitURL = %q, want %q", req.GitURL, review.HeadCloneURL)
	}
	if req.GitRef != review.HeadRef {
		t.Errorf("GitRef = %q, want %q", req.GitRef, review.HeadRef)
	}
	if req.GitHubRepo != review.Repo {
		t.Errorf("GitHubRepo = %q, want base repository %q", req.GitHubRepo, review.Repo)
	}
	if req.GitHubInstallationID != 321 {
		t.Errorf("GitHubInstallationID = %d, want 321", req.GitHubInstallationID)
	}
	if req.Agent != "pr-reviewer" {
		t.Errorf("Agent = %q, want pr-reviewer", req.Agent)
	}
	if req.ProviderID != "opencode" {
		t.Errorf("ProviderID = %q, want opencode", req.ProviderID)
	}
	if req.ModelID != "minimax-m3" {
		t.Errorf("ModelID = %q, want minimax-m3", req.ModelID)
	}
	if req.TimeoutSec != 3600 {
		t.Errorf("TimeoutSec = %d, want 3600", req.TimeoutSec)
	}
	if req.SessionMode != "resumable" {
		t.Errorf("SessionMode = %q, want resumable", req.SessionMode)
	}
	if req.PauseReason != "waiting_for_pr_feedback" {
		t.Errorf("PauseReason = %q, want waiting_for_pr_feedback", req.PauseReason)
	}
	if req.TTLHours != 48 {
		t.Errorf("TTLHours = %d, want 48", req.TTLHours)
	}
	if req.AgentImage == "" {
		t.Error("AgentImage should be set so service.SubmitTask does not reject the request")
	}
	if got := req.Env["PR_NUMBER"]; got != "42" {
		t.Errorf("Env[PR_NUMBER] = %q, want 42", got)
	}
	if _, ok := req.Env["GITHUB_TOKEN"]; ok {
		t.Error("GITHUB_TOKEN must not be persisted in webhook task environment")
	}
	if got := req.Env["GITHUB_REPO"]; got != "chetter/chetter" {
		t.Errorf("Env[GITHUB_REPO] = %q, want my-org/my-repo", got)
	}
	for _, key := range []string{"CHETTER_AGENT_NAME", "CHETTER_MODEL_ID"} {
		if _, ok := req.Env[key]; ok {
			t.Errorf("Env[%s] must not be supplied by the webhook request", key)
		}
	}
	if _, ok := req.Env["COMMENT_AUTHOR"]; ok {
		t.Error("COMMENT_AUTHOR should not be set when CommentAuthor is empty")
	}
}

func TestBuildReviewTaskRequest_WithComment(t *testing.T) {
	review := ReviewContext{
		Trigger:              "comment",
		CommentAuthor:        "someuser",
		Repo:                 "chetter/chetter",
		PRNumber:             7,
		BaseRef:              "main",
		HeadRef:              "fix/x",
		HeadCloneURL:         "https://github.com/x.git",
		GitHubInstallationID: 321,
		Agent:                "pr-reviewer",
		ProviderID:           "opencode",
		ModelID:              "minimax-m3",
		TimeoutSec:           3600,
	}
	req := buildReviewTaskRequest(review)
	if got := req.Env["COMMENT_AUTHOR"]; got != "someuser" {
		t.Errorf("Env[COMMENT_AUTHOR] = %q, want someuser", got)
	}
}

type recordingSessionResumer struct {
	repo     string
	prNumber int
	calls    int
}

func (r *recordingSessionResumer) ResumeSessionForPR(_ context.Context, repo string, prNumber int) error {
	r.repo = repo
	r.prNumber = prNumber
	r.calls++
	return nil
}

func TestHandlePullRequestReviewResumesSession(t *testing.T) {
	resumer := &recordingSessionResumer{}
	h := &Handler{resumer: resumer, github: newTestManager(t, "")}
	body := []byte(`{
		"action":"submitted",
		"repository":{"full_name":"flatout-works/chetter"},
		"pull_request":{"number":42},
		"review":{}
		,"installation":{"id":321}
	}`)

	if err := h.handlePullRequestReview(body, "delivery-1"); err != nil {
		t.Fatal(err)
	}

	if resumer.calls != 1 {
		t.Fatalf("resume calls = %d, want 1", resumer.calls)
	}
	if resumer.repo != "flatout-works/chetter" || resumer.prNumber != 42 {
		t.Fatalf("resume target = %s#%d", resumer.repo, resumer.prNumber)
	}
}

func TestHandlePullRequestReviewCommentResumesSession(t *testing.T) {
	resumer := &recordingSessionResumer{}
	h := &Handler{resumer: resumer, github: newTestManager(t, "")}
	body := []byte(`{
		"action":"created",
		"repository":{"full_name":"flatout-works/chetter"},
		"pull_request":{"number":7},
		"comment":{}
		,"installation":{"id":321}
	}`)

	if err := h.handlePullRequestReviewComment(body, "delivery-2"); err != nil {
		t.Fatal(err)
	}

	if resumer.calls != 1 {
		t.Fatalf("resume calls = %d, want 1", resumer.calls)
	}
	if resumer.repo != "flatout-works/chetter" || resumer.prNumber != 7 {
		t.Fatalf("resume target = %s#%d", resumer.repo, resumer.prNumber)
	}
}

// TestBuildReviewTaskRequest_TriggerOverridesPromptAndImage checks that when
// the trigger supplies a custom prompt and agent image, those are used in
// preference to the built-in template and the default image.
func TestBuildReviewTaskRequest_TriggerOverridesPromptAndImage(t *testing.T) {
	review := ReviewContext{
		Trigger:              "label",
		Repo:                 "flatout-works/chetter",
		PRNumber:             9,
		BaseRef:              "main",
		HeadRef:              "feat/x",
		HeadCloneURL:         "https://github.com/owner/repo.git",
		GitHubInstallationID: 321,
		Prompt:               "Custom trigger-supplied prompt",
		AgentImage:           "ghcr.io/custom/runner:v1",
		Agent:                "security-reviewer",
		ProviderID:           "custom-provider",
		ModelID:              "custom-model",
		TimeoutSec:           600,
		Skills:               []string{"secretscan"},
	}
	req := buildReviewTaskRequest(review)

	if !strings.HasPrefix(req.Prompt, "Custom trigger-supplied prompt") {
		t.Errorf("Prompt = %q, want trigger-supplied prompt as prefix", req.Prompt)
	}
	// Custom prompts now get the PR context block appended.
	if !strings.Contains(req.Prompt, "PR number: 9") {
		t.Errorf("Prompt should contain PR context block with PR number 9, got: %q", req.Prompt)
	}
	if !strings.Contains(req.Prompt, "flatout-works/chetter") {
		t.Errorf("Prompt should contain repo name, got: %q", req.Prompt)
	}
	if !strings.Contains(req.Prompt, "gh pr diff") {
		t.Errorf("Prompt should contain review procedure with gh pr diff, got: %q", req.Prompt)
	}
	if req.AgentImage != "ghcr.io/custom/runner:v1" {
		t.Errorf("AgentImage = %q, want trigger-supplied image", req.AgentImage)
	}
	if req.Agent != "security-reviewer" {
		t.Errorf("Agent = %q, want security-reviewer", req.Agent)
	}
	if req.ProviderID != "custom-provider" {
		t.Errorf("ProviderID = %q, want custom-provider", req.ProviderID)
	}
	if req.ModelID != "custom-model" {
		t.Errorf("ModelID = %q, want custom-model", req.ModelID)
	}
	if req.TimeoutSec != 600 {
		t.Errorf("TimeoutSec = %d, want 600", req.TimeoutSec)
	}
	if len(req.Skills) != 1 || req.Skills[0] != "secretscan" {
		t.Errorf("Skills = %v, want [secretscan]", req.Skills)
	}
}

// TestBuildReviewTaskRequest_FallsBackToTemplateWhenNoPrompt checks that the
// built-in prompt template is used when the trigger did not supply a prompt.
func TestBuildReviewTaskRequest_FallsBackToTemplateWhenNoPrompt(t *testing.T) {
	review := ReviewContext{
		Trigger:              "label",
		Repo:                 "flatout-works/chetter",
		PRNumber:             1,
		BaseRef:              "main",
		HeadRef:              "feat/x",
		HeadCloneURL:         "https://github.com/o/r.git",
		GitHubInstallationID: 321,
		Agent:                "pr-reviewer",
		ProviderID:           "opencode",
		ModelID:              "minimax-m3",
		TimeoutSec:           3600,
		// Prompt and AgentImage are intentionally left empty
	}
	req := buildReviewTaskRequest(review)
	if req.Prompt == "" {
		t.Fatal("Prompt should fall back to the built-in template")
	}
	if req.Prompt == "Custom trigger-supplied prompt" {
		t.Error("Prompt should be the built-in template, not a trigger value")
	}
	if req.AgentImage == "" {
		t.Error("AgentImage should fall back to the default runner image")
	}
}

// TestBuildReviewTaskRequest_CustomPromptGetsContextBlock verifies that a
// custom trigger prompt still receives the PR context and review procedure,
// so the agent knows which PR to review and how to post the review.
func TestBuildReviewTaskRequest_CustomPromptGetsContextBlock(t *testing.T) {
	review := ReviewContext{
		Trigger:              "opened",
		Repo:                 "flatout-works/chetter",
		PRNumber:             190,
		BaseRef:              "main",
		HeadRef:              "fix/runner-completion-detection",
		HeadCloneURL:         "https://github.com/flatout-works/chetter.git",
		GitHubInstallationID: 321,
		Prompt:               "You are doing a PR review for an opened PR.",
		Agent:                "pr-reviewer",
		ProviderID:           "opencode",
		ModelID:              "deepseek-v4-flash-free",
		TimeoutSec:           3600,
	}
	req := buildReviewTaskRequest(review)

	if !strings.HasPrefix(req.Prompt, "You are doing a PR review for an opened PR.") {
		t.Fatalf("Prompt should start with the custom trigger prompt, got: %q", req.Prompt[:80])
	}
	for _, want := range []string{
		"PR number: 190",
		"flatout-works/chetter",
		"fix/runner-completion-detection",
		"gh pr diff $PR_NUMBER",
		"chetter_pr_review",
	} {
		if !strings.Contains(req.Prompt, want) {
			t.Errorf("Prompt should contain %q, got prompt with %d chars", want, len(req.Prompt))
		}
	}
}

// TestAsyncCtxDoesNotLeakGoroutine is a regression test for issue #52. The old
// asyncCtx spawned a goroutine per call that blocked for the full timeout
// duration before calling cancel (a no-op). A burst of webhook events would
// therefore accumulate one idle goroutine per event. After the fix, asyncCtx
// allocates only a deadline context (with an internal timer, no goroutine), so
// the goroutine count must not grow with the number of calls.
func TestAsyncCtxDoesNotLeakGoroutine(t *testing.T) {
	// Force any prior GC/runtime noise to settle and snapshot a baseline.
	runtime.GC()
	before := runtime.NumGoroutine()

	const calls = 200
	for i := 0; i < calls; i++ {
		_ = asyncCtx(500 * time.Millisecond)
	}

	after := runtime.NumGoroutine()
	// The old implementation would have added ~200 idle goroutines here. Allow a
	// small margin for unrelated runtime/test scheduler goroutines.
	if after > before+8 {
		t.Fatalf("asyncCtx leaked goroutines: before=%d after=%d (expected ~%d)", before, after, before)
	}

	// The returned contexts must still be valid, deadline-bounded contexts.
	ctx := asyncCtx(50 * time.Millisecond)
	select {
	case <-ctx.Done():
	case <-time.After(time.Second):
		t.Fatal("asyncCtx context did not expire by its deadline")
	}
	if err := ctx.Err(); err != context.DeadlineExceeded {
		t.Fatalf("ctx.Err() = %v, want DeadlineExceeded", err)
	}
}

// TestHandlerShutdownWaitsForInflightGoroutines is a regression test for issue
// #57. Shutdown must block until all in-flight handle() goroutines finish, so
// the server does not close the database while webhook events are still being
// processed.
func TestHandlerShutdownWaitsForInflightGoroutines(t *testing.T) {
	h := &Handler{}

	// Simulate an in-flight goroutine that takes 50ms.
	h.wg.Add(1)
	start := time.Now()
	go func() {
		defer h.wg.Done()
		time.Sleep(50 * time.Millisecond)
	}()

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	if err := h.Shutdown(ctx); err != nil {
		t.Fatalf("Shutdown returned error: %v", err)
	}
	elapsed := time.Since(start)
	if elapsed < 40*time.Millisecond {
		t.Fatalf("Shutdown returned before goroutine finished, elapsed=%v", elapsed)
	}
}

// TestHandlerShutdownTimesOut verifies that Shutdown returns ctx.Err() when
// in-flight goroutines exceed the deadline, rather than blocking forever. See
// issue #57 acceptance criteria.
func TestHandlerShutdownTimesOut(t *testing.T) {
	h := &Handler{}

	// Simulate a long-running goroutine that never finishes within the drain.
	h.wg.Add(1)
	go func() {
		defer h.wg.Done()
		time.Sleep(10 * time.Second)
	}()

	ctx, cancel := context.WithTimeout(context.Background(), 50*time.Millisecond)
	defer cancel()
	err := h.Shutdown(ctx)
	if err == nil {
		t.Fatal("Shutdown should have timed out, but returned nil")
	}
}
