// Package webhook tests for the GitHub webhook handler and helpers.
package webhook

import (
	"context"
	"io"
	"net/http"
	"strings"
	"testing"
	"time"
)

// TestVerifySignature checks the HMAC-SHA256 verification with a known
// payload/secret/signature triple. The known vector was generated by the
// GitHub webhook test suite.
func TestVerifySignature(t *testing.T) {
	secret := "It's a Secret to Everybody"
	payload := []byte("Hello, World!")
	// Known GitHub signature for the above payload/secret.
	expected := "sha256=757107ea0eb2509fc211221cce984b8a37570b6d7586c22c46f4379c8b043e17"

	if !verifySignature(secret, payload, expected) {
		t.Fatal("verifySignature returned false for known valid signature")
	}
}

func TestVerifySignature_Invalid(t *testing.T) {
	tests := []struct {
		name   string
		secret string
		header string
		body   []byte
		want   bool
	}{
		{"empty secret", "", "sha256=abc", []byte("body"), false},
		{"empty header", "secret", "", []byte("body"), false},
		{"wrong prefix", "secret", "md5=abc", []byte("body"), false},
		{"tampered body", "secret", "sha256=" + strings.Repeat("a", 64), []byte("body"), false},
		{"wrong secret", "secret", "sha256=" + strings.Repeat("b", 64), []byte("body"), false},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := verifySignature(tc.secret, tc.body, tc.header); got != tc.want {
				t.Errorf("verifySignature = %v, want %v", got, tc.want)
			}
		})
	}
}

// TestRecentDeliveries_SeenAndDeduplicate checks that the same delivery ID
// is only counted once within the TTL.
func TestRecentDeliveries_SeenAndDeduplicate(t *testing.T) {
	r := NewRecentDeliveries(time.Hour, 100)

	if r.Seen("delivery-1") {
		t.Fatal("first Seen should return false")
	}
	if !r.Seen("delivery-1") {
		t.Fatal("second Seen for same ID should return true")
	}
	if r.Seen("delivery-2") {
		t.Fatal("first Seen for new ID should return false")
	}
	if r.Size() != 2 {
		t.Errorf("expected 2 entries, got %d", r.Size())
	}
}

func TestRecentDeliveries_EmptyID(t *testing.T) {
	r := NewRecentDeliveries(time.Hour, 100)
	if r.Seen("") {
		t.Fatal("empty ID should never be seen")
	}
}

func TestRecentDeliveries_Expiry(t *testing.T) {
	r := NewRecentDeliveries(50*time.Millisecond, 100)
	r.Seen("delivery-1")
	// After the TTL expires, the same ID should be treated as new.
	time.Sleep(80 * time.Millisecond)
	if r.Seen("delivery-1") {
		t.Fatal("expired delivery should be treated as new")
	}
}

// TestShouldReview_FilterLogic checks the filter that determines whether a
// PR should be reviewed, using a mocked GitHub client.
func TestShouldReview_FilterLogic(t *testing.T) {
	cases := []struct {
		name        string
		pr          PullRequest
		repo        string
		wantOK      bool
		wantTrigger string
	}{
		{
			name: "label triggers review",
			pr: PullRequest{
				Labels: []Label{{Name: "chetter-review"}},
			},
			repo:   "org/repo",
			wantOK: true, wantTrigger: "labeled",
		},
		{
			name: "labeled fork synchronize triggers fork gate",
			pr: PullRequest{
				Labels: []Label{{Name: "chetter-review"}},
				Head: PRBranch{
					Ref: "feat",
					Repo: struct {
						FullName string `json:"full_name"`
						CloneURL string `json:"clone_url"`
					}{
						FullName: "fork/repo",
						CloneURL: "https://github.com/fork/repo.git",
					},
				},
			},
			repo:   "org/repo",
			wantOK: true, wantTrigger: "fork",
		},
		{
			name: "fork triggers review",
			pr: PullRequest{
				Head: PRBranch{
					Ref: "feat",
					Repo: struct {
						FullName string `json:"full_name"`
						CloneURL string `json:"clone_url"`
					}{
						FullName: "fork/repo",
						CloneURL: "https://github.com/fork/repo.git",
					},
				},
			},
			repo:   "org/repo",
			wantOK: true, wantTrigger: "fork",
		},
		{
			name:   "internal PR with no label or action - no review",
			pr:     PullRequest{},
			repo:   "org/repo",
			wantOK: false, wantTrigger: "",
		},
		{
			name:   "opened triggers review",
			pr:     PullRequest{},
			repo:   "org/repo",
			wantOK: true, wantTrigger: "opened",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			ev := PullRequestEvent{
				Action:      "opened",
				PullRequest: tc.pr,
			}
			if tc.name == "internal PR with no label or action - no review" {
				ev.Action = ""
			}
			if tc.name == "label triggers review" {
				ev.Action = "labeled"
			}
			if tc.name == "labeled fork synchronize triggers fork gate" {
				ev.Action = "synchronize"
			}
			trigger := triggerActionFromPR(ev, tc.repo)
			ok := trigger != ""
			if ok != tc.wantOK {
				t.Errorf("triggerActionFromPR returned ok=%v, want %v", ok, tc.wantOK)
			}
			if trigger != tc.wantTrigger {
				t.Errorf("triggerActionFromPR returned trigger=%q, want %q", trigger, tc.wantTrigger)
			}
		})
	}
}

// TestBuildReviewTaskRequest checks that the review task request is populated
// correctly from a ReviewContext.
func TestBuildReviewTaskRequest(t *testing.T) {
	review := ReviewContext{
		Trigger:       "file-pattern",
		Repo:          "chetter/chetter",
		PRNumber:      42,
		BaseRef:       "main",
		HeadRef:       "feat/some-thing",
		HeadSHA:       "abc123",
		HeadCloneURL:  "https://github.com/someone/myapp.git",
		PRURL:         "https://github.com/chetter/chetter/pull/42",
		CommentAuthor: "",
		GitHubToken:   "ghs_test_token",
		Agent:         "pr-reviewer",
		ProviderID:    "opencode",
		ModelID:       "minimax-m3",
		TimeoutSec:    3600,
		SessionMode:   "resumable",
		PauseReason:   "waiting_for_pr_feedback",
		TTLHours:      48,
	}
	req := buildReviewTaskRequest(review)

	if req.Prompt == "" {
		t.Fatal("Prompt should be non-empty")
	}
	if req.GitURL != review.HeadCloneURL {
		t.Errorf("GitURL = %q, want %q", req.GitURL, review.HeadCloneURL)
	}
	if req.DefinitionRepo != review.Repo {
		t.Errorf("DefinitionRepo = %q, want %q", req.DefinitionRepo, review.Repo)
	}
	if req.GitRef != review.HeadRef {
		t.Errorf("GitRef = %q, want %q", req.GitRef, review.HeadRef)
	}
	if req.Agent != "pr-reviewer" {
		t.Errorf("Agent = %q, want pr-reviewer", req.Agent)
	}
	if req.ProviderID != "opencode" {
		t.Errorf("ProviderID = %q, want opencode", req.ProviderID)
	}
	if req.ModelID != "minimax-m3" {
		t.Errorf("ModelID = %q, want minimax-m3", req.ModelID)
	}
	if req.TimeoutSec != 3600 {
		t.Errorf("TimeoutSec = %d, want 3600", req.TimeoutSec)
	}
	if req.SessionMode != "resumable" {
		t.Errorf("SessionMode = %q, want resumable", req.SessionMode)
	}
	if req.PauseReason != "waiting_for_pr_feedback" {
		t.Errorf("PauseReason = %q, want waiting_for_pr_feedback", req.PauseReason)
	}
	if req.TTLHours != 48 {
		t.Errorf("TTLHours = %d, want 48", req.TTLHours)
	}
	if req.AgentImage == "" {
		t.Error("AgentImage should be set so service.SubmitTask does not reject the request")
	}
	if got := req.Env["PR_NUMBER"]; got != "42" {
		t.Errorf("Env[PR_NUMBER] = %q, want 42", got)
	}
	if got := req.Env["GITHUB_TOKEN"]; got != "ghs_test_token" {
		t.Errorf("Env[GITHUB_TOKEN] = %q, want ghs_test_token", got)
	}
	if got := req.Env["GITHUB_REPO"]; got != "chetter/chetter" {
		t.Errorf("Env[GITHUB_REPO] = %q, want my-org/my-repo", got)
	}
	if got := req.Env["PR_URL"]; got != "https://github.com/chetter/chetter/pull/42" {
		t.Errorf("Env[PR_URL] = %q, want PR URL", got)
	}
	if got := req.Env["PR_HEAD_SHA"]; got != "abc123" {
		t.Errorf("Env[PR_HEAD_SHA] = %q, want abc123", got)
	}
	if got := req.Env["PR_BASE_REF"]; got != "main" {
		t.Errorf("Env[PR_BASE_REF] = %q, want main", got)
	}
	if got := req.Env["PR_HEAD_REF"]; got != "feat/some-thing" {
		t.Errorf("Env[PR_HEAD_REF] = %q, want feat/some-thing", got)
	}
	if got := req.Env["PR_HEAD_CLONE_URL"]; got != "https://github.com/someone/myapp.git" {
		t.Errorf("Env[PR_HEAD_CLONE_URL] = %q, want clone URL", got)
	}
	if _, ok := req.Env["COMMENT_AUTHOR"]; ok {
		t.Error("COMMENT_AUTHOR should not be set when CommentAuthor is empty")
	}
}

func TestBuildReviewTaskRequest_PRURLFallback(t *testing.T) {
	req := buildReviewTaskRequest(ReviewContext{
		Trigger:      "label",
		Repo:         "flatout-works/chetter",
		PRNumber:     123,
		BaseRef:      "main",
		HeadRef:      "feat/x",
		HeadCloneURL: "https://github.com/fork/chetter.git",
		GitHubToken:  "t",
		Agent:        "review-orchestrator",
	})
	if got := req.Env["PR_URL"]; got != "https://github.com/flatout-works/chetter/pull/123" {
		t.Fatalf("PR_URL fallback = %q", got)
	}
}

func TestBuildReviewTaskRequest_WithComment(t *testing.T) {
	review := ReviewContext{
		Trigger:       "comment",
		CommentAuthor: "someuser",
		Repo:          "chetter/chetter",
		PRNumber:      7,
		BaseRef:       "main",
		HeadRef:       "fix/x",
		HeadCloneURL:  "https://github.com/x.git",
		GitHubToken:   "t",
		Agent:         "pr-reviewer",
		ProviderID:    "opencode",
		ModelID:       "minimax-m3",
		TimeoutSec:    3600,
	}
	req := buildReviewTaskRequest(review)
	if got := req.Env["COMMENT_AUTHOR"]; got != "someuser" {
		t.Errorf("Env[COMMENT_AUTHOR] = %q, want someuser", got)
	}
}

type recordingSessionResumer struct {
	repo     string
	prNumber int
	calls    int
}

func (r *recordingSessionResumer) ResumeSessionForPR(_ context.Context, repo string, prNumber int) error {
	r.repo = repo
	r.prNumber = prNumber
	r.calls++
	return nil
}

type recordingTriggerResolver struct {
	prTriggers    []ReviewTrigger
	issueTriggers []ReviewTrigger
}

func (r recordingTriggerResolver) ListEnabledPRReviewTriggersByRepo(context.Context, string) ([]ReviewTrigger, error) {
	return r.prTriggers, nil
}

func (r recordingTriggerResolver) ListEnabledIssueTriggersByRepo(context.Context, string) ([]ReviewTrigger, error) {
	return r.issueTriggers, nil
}

type recordingTaskSubmitter struct {
	reviews []ReviewContext
	tasks   []SubmitTaskRequest
}

func (r *recordingTaskSubmitter) SubmitReviewTask(_ context.Context, review ReviewContext) error {
	r.reviews = append(r.reviews, review)
	return nil
}

func (r *recordingTaskSubmitter) SubmitTask(_ context.Context, req SubmitTaskRequest) (any, error) {
	r.tasks = append(r.tasks, req)
	return nil, nil
}

type roundTripFunc func(*http.Request) (*http.Response, error)

func (f roundTripFunc) RoundTrip(req *http.Request) (*http.Response, error) {
	return f(req)
}

func fakePermissionGitHub(writeUsers ...string) *Client {
	allowed := map[string]struct{}{}
	for _, user := range writeUsers {
		allowed[user] = struct{}{}
	}
	return &Client{
		HTTPClient: &http.Client{Transport: roundTripFunc(func(req *http.Request) (*http.Response, error) {
			status := http.StatusOK
			body := `{}`
			switch {
			case req.URL.Path == "/app":
				body = `{"slug":"chetter"}`
			case strings.Contains(req.URL.Path, "/collaborators/") && strings.HasSuffix(req.URL.Path, "/permission"):
				parts := strings.Split(req.URL.Path, "/")
				user := ""
				for i, part := range parts {
					if part == "collaborators" && i+1 < len(parts) {
						user = parts[i+1]
						break
					}
				}
				if _, ok := allowed[user]; ok {
					body = `{"permission":"write","user":{"login":"` + user + `"}}`
				} else {
					body = `{"permission":"read","user":{"login":"` + user + `"}}`
				}
			default:
				status = http.StatusNotFound
				body = `{"message":"not found"}`
			}
			return &http.Response{
				StatusCode: status,
				Header:     make(http.Header),
				Body:       io.NopCloser(strings.NewReader(body)),
			}, nil
		})},
		tokenCache: &tokenCache{token: "ghs_test", expiry: time.Now().Add(time.Hour)},
	}
}

func TestHandlePullRequestReviewResumesSession(t *testing.T) {
	resumer := &recordingSessionResumer{}
	h := &Handler{resumer: resumer, gh: fakePermissionGitHub("writer")}
	body := []byte(`{
		"action":"submitted",
		"repository":{"full_name":"flatout-works/chetter"},
		"pull_request":{"number":42},
		"review":{"user":{"login":"writer"}}
	}`)

	h.handlePullRequestReview(body, "delivery-1")

	if resumer.calls != 1 {
		t.Fatalf("resume calls = %d, want 1", resumer.calls)
	}
	if resumer.repo != "flatout-works/chetter" || resumer.prNumber != 42 {
		t.Fatalf("resume target = %s#%d", resumer.repo, resumer.prNumber)
	}
}

func TestHandlePullRequestReviewCommentResumesSession(t *testing.T) {
	resumer := &recordingSessionResumer{}
	h := &Handler{resumer: resumer, gh: fakePermissionGitHub("writer")}
	body := []byte(`{
		"action":"created",
		"repository":{"full_name":"flatout-works/chetter"},
		"pull_request":{"number":7},
		"comment":{"user":{"login":"writer"}}
	}`)

	h.handlePullRequestReviewComment(body, "delivery-2")

	if resumer.calls != 1 {
		t.Fatalf("resume calls = %d, want 1", resumer.calls)
	}
	if resumer.repo != "flatout-works/chetter" || resumer.prNumber != 7 {
		t.Fatalf("resume target = %s#%d", resumer.repo, resumer.prNumber)
	}
}

func TestHandlePullRequestReviewCommentDoesNotResumeForNonWriter(t *testing.T) {
	resumer := &recordingSessionResumer{}
	h := &Handler{resumer: resumer, gh: fakePermissionGitHub("writer")}
	body := []byte(`{
		"action":"created",
		"repository":{"full_name":"flatout-works/chetter"},
		"pull_request":{"number":7},
		"comment":{"user":{"login":"reader"}}
	}`)

	h.handlePullRequestReviewComment(body, "delivery-3")

	if resumer.calls != 0 {
		t.Fatalf("resume calls = %d, want 0", resumer.calls)
	}
}

func TestHandleIssueCommentDoesNotResumePRForNonWriter(t *testing.T) {
	resumer := &recordingSessionResumer{}
	h := &Handler{resumer: resumer, gh: fakePermissionGitHub("writer")}
	body := []byte(`{
		"action":"created",
		"repository":{"full_name":"flatout-works/chetter"},
		"issue":{"number":7,"html_url":"https://github.com/flatout-works/chetter/pull/7","pull_request":{"url":"https://api.github.com/repos/flatout-works/chetter/pulls/7"}},
		"comment":{"body":"please take another look","user":{"login":"reader"}}
	}`)

	h.handleIssueComment(body, "delivery-4")

	if resumer.calls != 0 {
		t.Fatalf("resume calls = %d, want 0", resumer.calls)
	}
}

func TestHandleIssueCommentDoesNotResumePRForAppBot(t *testing.T) {
	resumer := &recordingSessionResumer{}
	h := &Handler{resumer: resumer, gh: fakePermissionGitHub("chetter[bot]")}
	body := []byte(`{
		"action":"created",
		"repository":{"full_name":"flatout-works/chetter"},
		"issue":{"number":7,"html_url":"https://github.com/flatout-works/chetter/pull/7","pull_request":{"url":"https://api.github.com/repos/flatout-works/chetter/pulls/7"}},
		"comment":{"body":"Task: task_abc123","user":{"login":"chetter[bot]"}}
	}`)

	h.handleIssueComment(body, "delivery-5")

	if resumer.calls != 0 {
		t.Fatalf("resume calls = %d, want 0", resumer.calls)
	}
}

func TestHandleIssueCommentAllowsConfiguredBotComments(t *testing.T) {
	submitter := &recordingTaskSubmitter{}
	h := &Handler{
		gh:        fakePermissionGitHub("chetter[bot]"),
		submitter: submitter,
		triggers: recordingTriggerResolver{issueTriggers: []ReviewTrigger{
			{Name: "ordinary-comment", TriggerType: "issue", Event: "comment"},
			{Name: "bot-comment", TriggerType: "issue", Event: "comment bot_comments:true"},
		}},
	}
	body := []byte(`{
		"action":"created",
		"repository":{"full_name":"flatout-works/chetter"},
		"issue":{
			"number":7,
			"title":"please help",
			"body":"issue body",
			"html_url":"https://github.com/flatout-works/chetter/issues/7",
			"labels":[]
		},
		"comment":{"body":"Task: task_abc123","user":{"login":"chetter[bot]"}}
	}`)

	h.handleIssueComment(body, "delivery-6")

	if len(submitter.tasks) != 1 {
		t.Fatalf("submitted tasks = %d, want 1", len(submitter.tasks))
	}
	if submitter.tasks[0].TriggerName != "bot-comment" {
		t.Fatalf("trigger name = %q, want bot-comment", submitter.tasks[0].TriggerName)
	}
}

func TestHandleIssuesOpenedSubmitsReadOnlyTask(t *testing.T) {
	submitter := &recordingTaskSubmitter{}
	h := &Handler{
		gh:        fakePermissionGitHub("writer"),
		submitter: submitter,
		triggers: recordingTriggerResolver{issueTriggers: []ReviewTrigger{{
			Name:        "issue-triage",
			TriggerType: "issue",
			AgentImage:  "runner:latest",
			MCPProfiles: []string{"chetter-orchestration"},
			Event:       "opened",
		}}},
	}
	body := []byte(`{
		"action":"opened",
		"repository":{"full_name":"flatout-works/chetter"},
		"issue":{
			"number":12,
			"title":"please help",
			"body":"untrusted issue text",
			"html_url":"https://github.com/flatout-works/chetter/issues/12",
			"labels":[]
		}
	}`)

	h.handleIssues(body, "delivery-5")

	if len(submitter.tasks) != 1 {
		t.Fatalf("submitted tasks = %d, want 1", len(submitter.tasks))
	}
	req := submitter.tasks[0]
	if req.AllowGitHubToken {
		t.Fatal("opened issue task should not be GitHub write-authorized")
	}
	if req.AllowPrivilegedMCPProfiles {
		t.Fatal("opened issue task should not allow privileged mcp profiles")
	}
	if _, ok := req.Env["GITHUB_TOKEN"]; ok {
		t.Fatalf("opened issue task received GITHUB_TOKEN: %#v", req.Env)
	}
	if len(req.MCPProfiles) != 0 {
		t.Fatalf("opened issue task kept mcp profiles: %#v", req.MCPProfiles)
	}
	if req.Env["GITHUB_REPO"] != "flatout-works/chetter" || req.Env["ISSUE_NUMBER"] != "12" {
		t.Fatalf("issue context env not preserved: %#v", req.Env)
	}
}

func TestHandleIssuesLabeledRequiresWriterActor(t *testing.T) {
	submitter := &recordingTaskSubmitter{}
	h := &Handler{
		gh:        fakePermissionGitHub("writer"),
		submitter: submitter,
		triggers: recordingTriggerResolver{issueTriggers: []ReviewTrigger{{
			Name:        "issue-label",
			TriggerType: "issue",
			Event:       "labeled",
			MatchLabels: []string{"needs-triage"},
		}}},
	}
	body := []byte(`{
		"action":"labeled",
		"repository":{"full_name":"flatout-works/chetter"},
		"sender":{"login":"reader"},
		"label":{"name":"needs-triage"},
		"issue":{
			"number":12,
			"title":"please help",
			"body":"untrusted issue text",
			"html_url":"https://github.com/flatout-works/chetter/issues/12",
			"labels":[{"name":"needs-triage"}]
		}
	}`)

	h.handleIssues(body, "delivery-6")

	if len(submitter.tasks) != 0 {
		t.Fatalf("submitted tasks = %d, want 0", len(submitter.tasks))
	}
}

func TestHandleIssuesLabeledAllowsWriterActor(t *testing.T) {
	submitter := &recordingTaskSubmitter{}
	h := &Handler{
		gh:        fakePermissionGitHub("writer"),
		submitter: submitter,
		triggers: recordingTriggerResolver{issueTriggers: []ReviewTrigger{{
			Name:        "issue-label",
			TriggerType: "issue",
			AgentImage:  "runner:latest",
			MCPProfiles: []string{"chetter-orchestration"},
			Event:       "labeled",
			MatchLabels: []string{"needs-triage"},
		}}},
	}
	body := []byte(`{
		"action":"labeled",
		"repository":{"full_name":"flatout-works/chetter"},
		"sender":{"login":"writer"},
		"label":{"name":"needs-triage"},
		"issue":{
			"number":12,
			"title":"please help",
			"body":"issue text",
			"html_url":"https://github.com/flatout-works/chetter/issues/12",
			"labels":[{"name":"needs-triage"}]
		}
	}`)

	h.handleIssues(body, "delivery-7")

	if len(submitter.tasks) != 1 {
		t.Fatalf("submitted tasks = %d, want 1", len(submitter.tasks))
	}
	req := submitter.tasks[0]
	if !req.AllowGitHubToken {
		t.Fatal("labeled issue task should be GitHub write-authorized for writer actor")
	}
	if !req.AllowPrivilegedMCPProfiles {
		t.Fatal("labeled issue task should allow privileged mcp profiles for global trigger")
	}
	if req.Env["GITHUB_TOKEN"] != "ghs_test" {
		t.Fatalf("labeled issue task token = %q, want test token", req.Env["GITHUB_TOKEN"])
	}
	if len(req.MCPProfiles) != 1 || req.MCPProfiles[0] != "chetter-orchestration" {
		t.Fatalf("labeled issue task mcp profiles = %#v", req.MCPProfiles)
	}
}

func TestHandlePullRequestLabeledRequiresWriterActor(t *testing.T) {
	submitter := &recordingTaskSubmitter{}
	h := &Handler{
		gh:        fakePermissionGitHub("writer"),
		submitter: submitter,
		triggers:  recordingTriggerResolver{prTriggers: []ReviewTrigger{{Name: "review", TriggerType: "pr_review", Event: "labeled"}}},
	}
	body := []byte(`{
		"action":"labeled",
		"number":7,
		"repository":{"full_name":"flatout-works/chetter"},
		"label":{"name":"chetter-review"},
		"sender":{"login":"reader"},
		"pull_request":{
			"number":7,
			"html_url":"https://github.com/flatout-works/chetter/pull/7",
			"user":{"login":"contributor"},
			"head":{"ref":"feature","sha":"abc","repo":{"full_name":"flatout-works/chetter","clone_url":"https://github.com/flatout-works/chetter.git"}},
			"base":{"ref":"main","repo":{"full_name":"flatout-works/chetter","clone_url":"https://github.com/flatout-works/chetter.git"}},
			"labels":[{"name":"chetter-review"}]
		}
	}`)

	h.handlePullRequest(body, "delivery-6")

	if len(submitter.reviews) != 0 {
		t.Fatalf("submitted reviews = %d, want 0", len(submitter.reviews))
	}
}

func TestHandlePullRequestLabeledAllowsWriterActor(t *testing.T) {
	submitter := &recordingTaskSubmitter{}
	h := &Handler{
		gh:        fakePermissionGitHub("writer"),
		submitter: submitter,
		triggers:  recordingTriggerResolver{prTriggers: []ReviewTrigger{{Name: "review", TriggerType: "pr_review", Event: "labeled"}}},
	}
	body := []byte(`{
		"action":"labeled",
		"number":7,
		"repository":{"full_name":"flatout-works/chetter"},
		"label":{"name":"chetter-review"},
		"sender":{"login":"writer"},
		"pull_request":{
			"number":7,
			"html_url":"https://github.com/flatout-works/chetter/pull/7",
			"user":{"login":"contributor"},
			"head":{"ref":"feature","sha":"abc","repo":{"full_name":"flatout-works/chetter","clone_url":"https://github.com/flatout-works/chetter.git"}},
			"base":{"ref":"main","repo":{"full_name":"flatout-works/chetter","clone_url":"https://github.com/flatout-works/chetter.git"}},
			"labels":[{"name":"chetter-review"}]
		}
	}`)

	h.handlePullRequest(body, "delivery-7")

	if len(submitter.reviews) != 1 {
		t.Fatalf("submitted reviews = %d, want 1", len(submitter.reviews))
	}
	if submitter.reviews[0].Trigger != "labeled" {
		t.Fatalf("review trigger = %q, want labeled", submitter.reviews[0].Trigger)
	}
}

// TestBuildReviewTaskRequest_TriggerOverridesPromptAndImage checks that when
// the trigger supplies a custom prompt and agent image, those are used in
// preference to the built-in template and the default image.
func TestBuildReviewTaskRequest_TriggerOverridesPromptAndImage(t *testing.T) {
	review := ReviewContext{
		Trigger:      "label",
		Repo:         "flatout-works/chetter",
		PRNumber:     9,
		BaseRef:      "main",
		HeadRef:      "feat/x",
		HeadCloneURL: "https://github.com/owner/repo.git",
		GitHubToken:  "t",
		Prompt:       "Custom trigger-supplied prompt",
		AgentImage:   "ghcr.io/custom/runner:v1",
		Agent:        "security-reviewer",
		ProviderID:   "custom-provider",
		ModelID:      "custom-model",
		TimeoutSec:   600,
		Skills:       []string{"secretscan"},
	}
	req := buildReviewTaskRequest(review)

	if req.Prompt != "Custom trigger-supplied prompt" {
		t.Errorf("Prompt = %q, want trigger-supplied prompt", req.Prompt)
	}
	if req.AgentImage != "ghcr.io/custom/runner:v1" {
		t.Errorf("AgentImage = %q, want trigger-supplied image", req.AgentImage)
	}
	if req.Agent != "security-reviewer" {
		t.Errorf("Agent = %q, want security-reviewer", req.Agent)
	}
	if req.ProviderID != "custom-provider" {
		t.Errorf("ProviderID = %q, want custom-provider", req.ProviderID)
	}
	if req.ModelID != "custom-model" {
		t.Errorf("ModelID = %q, want custom-model", req.ModelID)
	}
	if req.TimeoutSec != 600 {
		t.Errorf("TimeoutSec = %d, want 600", req.TimeoutSec)
	}
	if len(req.Skills) != 1 || req.Skills[0] != "secretscan" {
		t.Errorf("Skills = %v, want [secretscan]", req.Skills)
	}
}

// TestBuildReviewTaskRequest_FallsBackToTemplateWhenNoPrompt checks that the
// built-in prompt template is used when the trigger did not supply a prompt.
func TestBuildReviewTaskRequest_FallsBackToTemplateWhenNoPrompt(t *testing.T) {
	review := ReviewContext{
		Trigger:      "label",
		Repo:         "flatout-works/chetter",
		PRNumber:     1,
		BaseRef:      "main",
		HeadRef:      "feat/x",
		HeadCloneURL: "https://github.com/o/r.git",
		GitHubToken:  "t",
		Agent:        "pr-reviewer",
		ProviderID:   "opencode",
		ModelID:      "minimax-m3",
		TimeoutSec:   3600,
		// Prompt and AgentImage are intentionally left empty
	}
	req := buildReviewTaskRequest(review)
	if req.Prompt == "" {
		t.Fatal("Prompt should fall back to the built-in template")
	}
	if req.Prompt == "Custom trigger-supplied prompt" {
		t.Error("Prompt should be the built-in template, not a trigger value")
	}
	if req.AgentImage == "" {
		t.Error("AgentImage should fall back to the default runner image")
	}
}
