package service

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/flatout-works/chetter/internal/auth"
	"github.com/flatout-works/chetter/internal/repository"
	"github.com/flatout-works/chetter/internal/webhook"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

type GitHubArtifactOutput struct {
	TaskID             string `json:"task_id"`
	ExecutionAttemptID string `json:"execution_attempt_id"`
	Repo               string `json:"repo"`
	ArtifactType       string `json:"artifact_type"`
	Number             int    `json:"number,omitempty"`
	URL                string `json:"url,omitempty"`
	Body               string `json:"body,omitempty"`
}

func (s *Service) githubManager() *webhook.Manager { return s.github }

func (s *Service) githubToolTaskContext(ctx context.Context, taskID, executionAttemptID string) (repository.Task, repository.UserPrompt, error) {
	if s.githubManager() == nil {
		return repository.Task{}, repository.UserPrompt{}, fmt.Errorf("GitHub App client is not configured")
	}
	ownership, err := s.repo.GetExecutionAttemptContext(ctx, executionAttemptID)
	if err != nil {
		return repository.Task{}, repository.UserPrompt{}, fmt.Errorf("get execution attempt context: %w", err)
	}
	if ownership.TaskID != taskID {
		return repository.Task{}, repository.UserPrompt{}, fmt.Errorf("execution attempt %q does not belong to task %q", executionAttemptID, taskID)
	}
	task, err := s.repo.GetTaskByID(ctx, taskID)
	if err != nil {
		if err == sql.ErrNoRows {
			return repository.Task{}, repository.UserPrompt{}, fmt.Errorf("task %q not found", taskID)
		}
		return repository.Task{}, repository.UserPrompt{}, fmt.Errorf("get task: %w", err)
	}
	if scope, ok := auth.GetScope(ctx); ok && !scope.Admin && (!task.TeamID.Valid || !scope.HasTeam(task.TeamID.String)) {
		return repository.Task{}, repository.UserPrompt{}, fmt.Errorf("task %q not found", taskID)
	}
	userPrompt, err := s.repo.GetUserPromptByID(ctx, ownership.UserPromptID)
	if err != nil {
		return repository.Task{}, repository.UserPrompt{}, fmt.Errorf("get user prompt: %w", err)
	}
	return task, userPrompt, nil
}

func (s *Service) githubToolSignature(ctx context.Context, task repository.Task, userPrompt repository.UserPrompt, executionAttemptID string) string {
	return s.githubToolSignatureForContext(ctx, task.ID, userPrompt.AgentSessionID, userPrompt.ID, executionAttemptID)
}

func (s *Service) githubToolSignatureForContext(ctx context.Context, taskID, agentSessionID, userPromptID, executionAttemptID string) string {
	taskLink := taskID
	if s.cfg.WebURL != "" {
		taskLink = fmt.Sprintf("[%s](%s/tasks/%s)", taskID, strings.TrimRight(s.cfg.WebURL, "/"), taskID)
	}
	parts := []string{fmt.Sprintf("Task: %s", taskLink)}
	if agentSessionID != "" {
		parts = append(parts, "Session: "+agentSessionID)
	}
	if userPromptID != "" {
		parts = append(parts, "Prompt: "+userPromptID)
	}
	parts = append(parts, "Attempt: "+executionAttemptID)
	if session, err := s.repo.GetAgentSessionByID(ctx, agentSessionID); err == nil {
		if agent := strings.TrimSpace(session.Agent.String); agent != "" {
			parts = append(parts, "Agent: "+agent)
		}
		if model := strings.TrimSpace(session.ModelID.String); model != "" {
			parts = append(parts, "Model: "+model)
		}
	}
	return "---\n" + strings.Join(parts, " | ")
}

func appendChetterSignature(body, signature string) string {
	body = strings.TrimSpace(stripExistingChetterSignature(body))
	if body == "" {
		return signature
	}
	return body + "\n\n" + signature
}

func stripExistingChetterSignature(body string) string {
	idx := strings.LastIndex(body, "---\nTask:")
	if idx >= 0 {
		return strings.TrimSpace(body[:idx])
	}
	idx = strings.Index(body, "---\nGenerated by [Chetter]")
	if idx >= 0 {
		return strings.TrimSpace(body[:idx])
	}
	return body
}

func nonEmpty(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}

func (s *Service) recordGitHubToolArtifact(ctx context.Context, task repository.Task, userPrompt repository.UserPrompt, executionAttemptID, artifactType, repo string, number int, url, ref, body string, detail map[string]any) (*mcp.CallToolResult, GitHubArtifactOutput, error) {
	if err := s.RecordArtifact(ctx, RecordArtifactParams{
		TaskID:             task.ID,
		AgentSessionID:     userPrompt.AgentSessionID,
		UserPromptID:       userPrompt.ID,
		ExecutionAttemptID: executionAttemptID,
		ArtifactType:       artifactType,
		Repo:               repo,
		Number:             number,
		URL:                url,
		Ref:                ref,
		DiscoverySource:    "mcp_tool",
	}); err != nil {
		return nil, GitHubArtifactOutput{}, fmt.Errorf("record GitHub artifact: %w", err)
	}
	payload, err := json.Marshal(detail)
	if err != nil {
		return nil, GitHubArtifactOutput{}, fmt.Errorf("marshal payload: %w", err)
	}
	if err := s.LogAuditEvent(ctx, AuditEventParams{
		EventType:  "github_artifact_created",
		SourceType: "task",
		SourceID:   task.ID,
		TargetType: artifactType,
		TargetID:   fmt.Sprintf("%s#%d", repo, number),
		Repo:       repo,
		Detail:     fmt.Sprintf("created %s %s#%d via Chetter MCP tool", artifactType, repo, number),
		Payload:    payload,
	}); err != nil {
		return nil, GitHubArtifactOutput{}, fmt.Errorf("log GitHub artifact audit event: %w", err)
	}
	return nil, GitHubArtifactOutput{TaskID: task.ID, ExecutionAttemptID: executionAttemptID, Repo: repo, ArtifactType: artifactType, Number: number, URL: url, Body: body}, nil
}
