package service

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/flatout-works/chetter/internal/auth"
	"github.com/flatout-works/chetter/internal/repository"
	"github.com/flatout-works/chetter/internal/webhook"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

type GitHubArtifactOutput struct {
	TaskID       string `json:"task_id"`
	Repo         string `json:"repo"`
	ArtifactType string `json:"artifact_type"`
	Number       int    `json:"number,omitempty"`
	URL          string `json:"url,omitempty"`
	Body         string `json:"body,omitempty"`
}

func (s *Service) githubClient() *webhook.Client {
	return s.github
}

func (s *Service) GitHubClient() *webhook.Client {
	return s.githubClient()
}

func (s *Service) GetTaskSignature(ctx context.Context, taskID string) (string, error) {
	task, sessionRun, err := s.githubToolTaskContext(ctx, taskID)
	if err != nil {
		return "", err
	}
	return githubToolSignature(task, sessionRun, s.cfg.WebURL), nil
}

func (s *Service) githubToolTaskContext(ctx context.Context, taskID string) (repository.ChetterTask, repository.ChetterSessionRun, error) {
	if s.githubClient() == nil {
		return repository.ChetterTask{}, repository.ChetterSessionRun{}, fmt.Errorf("GitHub App client is not configured")
	}
	task, err := s.repo.GetTaskByID(ctx, taskID)
	if err != nil {
		if err == sql.ErrNoRows {
			return repository.ChetterTask{}, repository.ChetterSessionRun{}, fmt.Errorf("task %q not found", taskID)
		}
		return repository.ChetterTask{}, repository.ChetterSessionRun{}, fmt.Errorf("get task: %w", err)
	}
	if scope, ok := auth.GetScope(ctx); ok && !scope.Admin && (!task.TeamID.Valid || !scope.HasTeam(task.TeamID.String)) {
		return repository.ChetterTask{}, repository.ChetterSessionRun{}, fmt.Errorf("task %q not found", taskID)
	}
	sessionRun, err := s.repo.GetSessionRunByTaskID(ctx, taskID)
	if err != nil && err != sql.ErrNoRows {
		return repository.ChetterTask{}, repository.ChetterSessionRun{}, fmt.Errorf("get session run: %w", err)
	}
	return task, sessionRun, nil
}

func githubToolSignature(task repository.ChetterTask, sessionRun repository.ChetterSessionRun, webURL string) string {
	taskLink := task.ID
	if webURL != "" {
		taskLink = fmt.Sprintf("[%s](%s/tasks/%s)", task.ID, strings.TrimRight(webURL, "/"), task.ID)
	}
	parts := []string{fmt.Sprintf("Task: %s", taskLink)}
	if agent := strings.TrimSpace(task.Agent.String); agent != "" {
		parts = append(parts, "Agent: "+agent)
	}
	if model := strings.TrimSpace(task.ModelID.String); model != "" {
		parts = append(parts, "Model: "+model)
	}
	return "---\n" + strings.Join(parts, " | ")
}

func appendChetterSignature(body, signature string) string {
	body = strings.TrimSpace(stripExistingChetterSignature(body))
	if body == "" {
		return signature
	}
	return body + "\n\n" + signature
}

func stripExistingChetterSignature(body string) string {
	idx := strings.LastIndex(body, "---\nTask:")
	if idx >= 0 {
		return strings.TrimSpace(body[:idx])
	}
	idx = strings.Index(body, "---\nGenerated by [Chetter]")
	if idx >= 0 {
		return strings.TrimSpace(body[:idx])
	}
	return body
}

func nonEmpty(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}

func (s *Service) recordGitHubToolArtifact(ctx context.Context, task repository.ChetterTask, sessionRun repository.ChetterSessionRun, artifactType, repo string, number int, url, ref, body string, detail map[string]any) (*mcp.CallToolResult, GitHubArtifactOutput, error) {
	if err := s.RecordArtifact(ctx, RecordArtifactParams{
		TaskID:          task.ID,
		AgentSessionID:  sessionRun.AgentSessionID,
		SessionRunID:    sessionRun.ID,
		ArtifactType:    artifactType,
		Repo:            repo,
		Number:          number,
		URL:             url,
		Ref:             ref,
		DiscoverySource: "mcp_tool",
	}); err != nil {
		return nil, GitHubArtifactOutput{}, fmt.Errorf("record GitHub artifact: %w", err)
	}
	payload, err := json.Marshal(detail)
	if err != nil {
		return nil, GitHubArtifactOutput{}, fmt.Errorf("marshal payload: %w", err)
	}
	if err := s.LogAuditEvent(ctx, AuditEventParams{
		EventType:  "github_artifact_created",
		SourceType: "task",
		SourceID:   task.ID,
		TargetType: artifactType,
		TargetID:   fmt.Sprintf("%s#%d", repo, number),
		Repo:       repo,
		Detail:     fmt.Sprintf("created %s %s#%d via Chetter MCP tool", artifactType, repo, number),
		Payload:    payload,
	}); err != nil {
		return nil, GitHubArtifactOutput{}, fmt.Errorf("log GitHub artifact audit event: %w", err)
	}
	return nil, GitHubArtifactOutput{TaskID: task.ID, Repo: repo, ArtifactType: artifactType, Number: number, URL: url, Body: body}, nil
}
