package store

var schemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS chetter_tasks (
		id VARCHAR(64) NOT NULL,
		status VARCHAR(32) NOT NULL,
		prompt TEXT NOT NULL,
		git_url TEXT NULL,
		git_ref VARCHAR(255) NULL,
		agent_image VARCHAR(512) NULL,
		agent VARCHAR(128) NULL,
		provider_id VARCHAR(128) NULL,
		model_id VARCHAR(255) NULL,
		variant_id VARCHAR(128) NULL,
		opencode_session_id VARCHAR(128) NULL,
		runner_image_digest VARCHAR(255) NULL,
		commit_author_name VARCHAR(128) NULL,
		commit_author_email VARCHAR(255) NULL,
		git_identity_id VARCHAR(64) NULL,
		runner_id VARCHAR(64) NULL,
		required_runner_id VARCHAR(64) NULL,
		checkpoint_after_success BOOL NOT NULL DEFAULT false,
		trigger_name VARCHAR(128) NULL,
		trigger_type VARCHAR(32) NULL,
		submission_source VARCHAR(32) NOT NULL DEFAULT 'manual',
		claimed_at DATETIME(6) NULL,
		lease_expires_at DATETIME(6) NULL,
		attempt INT NOT NULL DEFAULT 0,
		execution_id VARCHAR(64) NOT NULL DEFAULT '',
		max_attempts INT NOT NULL DEFAULT 3,
		skills JSON NOT NULL,
		mcp_endpoints JSON NULL,
		env JSON NOT NULL,
		timeout_sec INT NOT NULL,
		summary TEXT NULL,
		error TEXT NULL,
		error_category VARCHAR(32) NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		last_event_at DATETIME(6) NULL,
		started_at DATETIME(6) NULL,
		ended_at DATETIME(6) NULL,
		session_export MEDIUMTEXT NULL,
		search_text TEXT NULL,
		total_input_tokens BIGINT NOT NULL DEFAULT 0,
		total_output_tokens BIGINT NOT NULL DEFAULT 0,
		total_cache_read_tokens BIGINT NOT NULL DEFAULT 0,
		total_cache_write_tokens BIGINT NOT NULL DEFAULT 0,
		total_reasoning_tokens BIGINT NOT NULL DEFAULT 0,
		cost_cents BIGINT NOT NULL DEFAULT 0,
		PRIMARY KEY (id),
		KEY idx_chetter_tasks_status_created (status, created_at),
		KEY idx_chetter_tasks_created (created_at),
		KEY idx_chetter_tasks_claim (status, lease_expires_at, created_at),
		KEY idx_chetter_tasks_runner (runner_id, status),
		KEY idx_chetter_tasks_trigger_created (trigger_name, created_at),
		KEY idx_chetter_tasks_required_runner (required_runner_id, status, created_at),
		FULLTEXT INDEX idx_tasks_search (search_text)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_agent_sessions (
		id VARCHAR(64) NOT NULL,
		task_id VARCHAR(64) NOT NULL,
		sequence INT NOT NULL DEFAULT 1,
		team_id VARCHAR(64) NULL,
		status VARCHAR(32) NOT NULL,
		resume_mode VARCHAR(32) NOT NULL DEFAULT 'none',
		pinned_runner_id VARCHAR(64) NULL,
		pinned_runner_name VARCHAR(128) NULL,
		checkpoint_id VARCHAR(64) NULL,
		workspace_path TEXT NULL,
		container_name VARCHAR(128) NULL,
		harness_session_id VARCHAR(128) NULL,
		git_url TEXT NULL,
		git_ref VARCHAR(255) NULL,
		agent_image VARCHAR(512) NULL,
		agent VARCHAR(128) NULL,
		provider_id VARCHAR(128) NULL,
		model_id VARCHAR(255) NULL,
		variant_id VARCHAR(128) NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		paused_at DATETIME(6) NULL,
		expires_at DATETIME(6) NULL,
		pause_reason VARCHAR(64) NULL,
		error TEXT NULL,
		search_text TEXT NULL,
		PRIMARY KEY (id),
		UNIQUE KEY uq_agent_sessions_task_sequence (task_id, sequence),
		KEY idx_agent_sessions_task (task_id, sequence),
		KEY idx_agent_sessions_team_status (team_id, status, updated_at),
		KEY idx_agent_sessions_runner_status (pinned_runner_id, status),
		KEY idx_agent_sessions_expires (expires_at),
		FULLTEXT INDEX idx_sessions_search (search_text)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_user_prompts (
		id VARCHAR(64) NOT NULL,
		agent_session_id VARCHAR(64) NOT NULL,
		task_id VARCHAR(64) NOT NULL,
		sequence INT NOT NULL DEFAULT 1,
		status VARCHAR(32) NOT NULL,
		prompt TEXT NOT NULL,
		required_runner_id VARCHAR(64) NULL,
		summary TEXT NULL,
		error TEXT NULL,
		session_export MEDIUMTEXT NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		started_at DATETIME(6) NULL,
		ended_at DATETIME(6) NULL,
		PRIMARY KEY (id),
		UNIQUE KEY uq_user_prompts_session_sequence (agent_session_id, sequence),
		KEY idx_user_prompts_task_sequence (task_id, sequence),
		KEY idx_user_prompts_session_created (agent_session_id, created_at),
		KEY idx_user_prompts_status_created (status, created_at),
		KEY idx_user_prompts_required_runner (required_runner_id, status)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_execution_attempts (
		id VARCHAR(64) NOT NULL,
		user_prompt_id VARCHAR(64) NOT NULL,
		sequence INT NOT NULL,
		status VARCHAR(32) NOT NULL,
		runner_id VARCHAR(64) NULL,
		required_runner_id VARCHAR(64) NULL,
		claimed_at DATETIME(6) NULL,
		lease_expires_at DATETIME(6) NULL,
		started_at DATETIME(6) NULL,
		ended_at DATETIME(6) NULL,
		workspace_path TEXT NULL,
		container_name VARCHAR(128) NULL,
		harness_execution_id VARCHAR(128) NULL,
		summary TEXT NULL,
		error TEXT NULL,
		error_category VARCHAR(32) NULL,
		session_export MEDIUMTEXT NULL,
		total_input_tokens BIGINT NOT NULL DEFAULT 0,
		total_output_tokens BIGINT NOT NULL DEFAULT 0,
		total_cache_read_tokens BIGINT NOT NULL DEFAULT 0,
		total_cache_write_tokens BIGINT NOT NULL DEFAULT 0,
		total_reasoning_tokens BIGINT NOT NULL DEFAULT 0,
		cost_cents BIGINT NOT NULL DEFAULT 0,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		UNIQUE KEY uq_execution_attempts_prompt_sequence (user_prompt_id, sequence),
		KEY idx_execution_attempts_status_lease (status, lease_expires_at),
		KEY idx_execution_attempts_runner_status (runner_id, status)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_agent_session_checkpoints (
		id VARCHAR(64) NOT NULL,
		agent_session_id VARCHAR(64) NOT NULL,
		user_prompt_id VARCHAR(64) NULL,
		runner_id VARCHAR(64) NOT NULL,
		checkpoint_path TEXT NOT NULL,
		workspace_path TEXT NOT NULL,
		container_name VARCHAR(128) NULL,
		runsc_version VARCHAR(128) NULL,
		agent_image VARCHAR(512) NULL,
		size_bytes BIGINT NOT NULL DEFAULT 0,
		status VARCHAR(32) NOT NULL,
		error TEXT NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		expires_at DATETIME(6) NULL,
		PRIMARY KEY (id),
		KEY idx_session_checkpoints_session_created (agent_session_id, created_at),
		KEY idx_session_checkpoints_runner_status (runner_id, status),
		KEY idx_session_checkpoints_expires (expires_at)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_task_events (
		id VARCHAR(64) NOT NULL,
		task_id VARCHAR(64) NOT NULL,
		subject VARCHAR(255) NOT NULL,
		status VARCHAR(32) NOT NULL,
		event_type VARCHAR(64) NOT NULL DEFAULT 'task.progress',
		payload JSON NOT NULL,
		created_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		KEY idx_chetter_task_events_task_created (task_id, created_at),
		KEY idx_chetter_task_events_type_created (event_type, created_at),
		KEY idx_chetter_task_events_created (created_at)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_event_callbacks (
		id VARCHAR(64) NOT NULL,
		team_id VARCHAR(64) NULL,
		name VARCHAR(255) NOT NULL,
		event_type VARCHAR(64) NOT NULL,
		action_type VARCHAR(32) NOT NULL,
		action_config JSON NOT NULL,
		enabled BOOL NOT NULL DEFAULT true,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		UNIQUE KEY uq_event_callbacks_team_name (team_id, name),
		KEY idx_event_callbacks_team_enabled (team_id, enabled),
		KEY idx_event_callbacks_event_type (event_type, enabled)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_runners (
		id VARCHAR(64) NOT NULL,
		status VARCHAR(32) NOT NULL,
		image_ref VARCHAR(512) NULL,
		image_digest VARCHAR(255) NULL,
		version VARCHAR(128) NULL,
		max_concurrent INT NOT NULL DEFAULT 0,
		running_tasks INT NOT NULL DEFAULT 0,
		available_slots INT NOT NULL DEFAULT 0,
		total_started BIGINT NOT NULL DEFAULT 0,
		total_completed BIGINT NOT NULL DEFAULT 0,
		total_errors BIGINT NOT NULL DEFAULT 0,
		started_at DATETIME(6) NULL,
		first_seen_at DATETIME(6) NOT NULL,
		last_seen_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		metadata JSON NOT NULL,
		PRIMARY KEY (id),
		KEY idx_chetter_runners_status_seen (status, last_seen_at),
		KEY idx_chetter_runners_digest_seen (image_digest, last_seen_at)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_triggers (
		id VARCHAR(64) NOT NULL,
		name VARCHAR(128) NOT NULL,
		trigger_type VARCHAR(32) NOT NULL DEFAULT 'cron',
		trigger_config JSON NOT NULL,
		cron_expr VARCHAR(128) NOT NULL,
		prompt TEXT NOT NULL,
		git_url TEXT NULL,
		git_ref VARCHAR(255) NULL,
		agent_image VARCHAR(512) NULL,
		agent VARCHAR(128) NULL,
		provider_id VARCHAR(128) NULL,
		model_id VARCHAR(255) NULL,
		variant_id VARCHAR(128) NULL,
		harness VARCHAR(64) NULL,
		skills JSON NOT NULL,
		timeout_sec INT NOT NULL,
		enabled BOOL NOT NULL,
		source_id VARCHAR(64) NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		last_run_at DATETIME(6) NULL,
		next_run_at DATETIME(6) NULL,
		PRIMARY KEY (id),
		UNIQUE KEY uq_chetter_triggers_name (name),
		KEY idx_chetter_triggers_enabled_next (enabled, next_run_at)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_trigger_runs (
		id VARCHAR(64) NOT NULL,
		trigger_id VARCHAR(64) NOT NULL,
		team_id VARCHAR(64) NULL,
		task_id VARCHAR(64) NOT NULL,
		status VARCHAR(32) NOT NULL,
		triggered_at DATETIME(6) NOT NULL,
		created_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		UNIQUE KEY idx_trigger_runs_dedup (trigger_id, task_id),
		KEY idx_chetter_trigger_runs_trigger_created (trigger_id, created_at),
		KEY idx_chetter_trigger_runs_task (task_id)
	)`,
	`CREATE TABLE IF NOT EXISTS teams (
		id VARCHAR(64) NOT NULL,
		name VARCHAR(128) NOT NULL,
		okta_group_id VARCHAR(255) NULL,
		okta_group_name VARCHAR(255) NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		UNIQUE KEY uq_teams_name (name),
		UNIQUE KEY uq_teams_okta_group_id (okta_group_id)
	)`,
	`CREATE TABLE IF NOT EXISTS git_identities (
		id VARCHAR(64) NOT NULL,
		team_id VARCHAR(64) NOT NULL DEFAULT '',
		name VARCHAR(128) NOT NULL,
		git_author_name VARCHAR(128) NOT NULL,
		git_author_email VARCHAR(255) NOT NULL,
		credential_type VARCHAR(32) NOT NULL DEFAULT 'github_app',
		is_default BOOL NOT NULL DEFAULT false,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		UNIQUE KEY uq_git_identities_team_name (team_id, name),
		KEY idx_git_identities_team (team_id)
	)`,
	`CREATE TABLE IF NOT EXISTS users (
		id VARCHAR(64) NOT NULL,
		name VARCHAR(128) NOT NULL,
		team_id VARCHAR(64) NOT NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		KEY idx_users_team (team_id)
	)`,
	`CREATE TABLE IF NOT EXISTS api_tokens (
		id VARCHAR(64) NOT NULL,
		name VARCHAR(128) NOT NULL,
		token_hash CHAR(64) NOT NULL,
		user_id VARCHAR(64) NOT NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		UNIQUE KEY uq_api_tokens_hash (token_hash),
		KEY idx_api_tokens_user (user_id)
	)`,
	`CREATE TABLE IF NOT EXISTS user_team_memberships (
		user_id VARCHAR(64) NOT NULL,
		team_id VARCHAR(64) NOT NULL,
		source VARCHAR(32) NOT NULL DEFAULT 'manual',
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		PRIMARY KEY (user_id, team_id),
		KEY idx_user_team_memberships_team (team_id)
	)`,
	`CREATE TABLE IF NOT EXISTS api_token_teams (
		token_id VARCHAR(64) NOT NULL,
		team_id VARCHAR(64) NOT NULL,
		created_at DATETIME(6) NOT NULL,
		PRIMARY KEY (token_id, team_id),
		KEY idx_api_token_teams_team (team_id)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_audit_log (
		id VARCHAR(64) NOT NULL,
		event_type VARCHAR(64) NOT NULL,
		created_at DATETIME(6) NOT NULL,
		source_type VARCHAR(32) NULL,
		source_id VARCHAR(255) NULL,
		target_type VARCHAR(32) NULL,
		target_id VARCHAR(255) NULL,
		repo VARCHAR(255) NULL,
		github_event VARCHAR(64) NULL,
		github_action VARCHAR(64) NULL,
		github_delivery_id VARCHAR(64) NULL,
		parent_event_id VARCHAR(64) NULL,
		detail TEXT NULL,
		search_text TEXT NULL,
		payload JSON NULL,
		token_id VARCHAR(64) NULL,
		token_name VARCHAR(128) NULL,
		PRIMARY KEY (id),
		KEY idx_audit_event_type (event_type, created_at),
		KEY idx_audit_source (source_type, source_id),
		KEY idx_audit_target (target_type, target_id),
		KEY idx_audit_created (created_at),
		KEY idx_audit_token (token_id),
		FULLTEXT INDEX idx_audit_search (search_text)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_task_artifacts (
		id VARCHAR(64) NOT NULL,
		task_id VARCHAR(64) NOT NULL,
		agent_session_id VARCHAR(64) NULL,
		user_prompt_id VARCHAR(64) NULL,
		artifact_type VARCHAR(32) NOT NULL,
		repo VARCHAR(255) NOT NULL,
		number INT NULL,
		url TEXT NULL,
		ref VARCHAR(255) NULL,
		sha VARCHAR(64) NULL,
		created_at DATETIME(6) NOT NULL,
		discovered_at DATETIME(6) NOT NULL,
		discovery_source VARCHAR(32) NOT NULL,
		search_text TEXT NULL,
		PRIMARY KEY (id),
		UNIQUE KEY idx_task_artifacts_dedup (task_id, artifact_type, repo, number),
		KEY idx_task_artifacts_task (task_id),
		KEY idx_task_artifacts_agent_session (agent_session_id),
		KEY idx_task_artifacts_user_prompt (user_prompt_id),
		KEY idx_task_artifacts_type_repo (artifact_type, repo),
		KEY idx_task_artifacts_number (repo, number),
		FULLTEXT INDEX idx_artifacts_search (search_text)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_model_catalogs (
		id VARCHAR(64) NOT NULL,
		name VARCHAR(128) NOT NULL,
		active BOOL NOT NULL DEFAULT false,
		source VARCHAR(255) NULL,
		checksum CHAR(64) NOT NULL,
		yaml MEDIUMTEXT NOT NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		UNIQUE KEY uq_model_catalogs_name (name),
		KEY idx_model_catalogs_active_updated (active, updated_at)
	)`,
	`CREATE TABLE IF NOT EXISTS definition_sources (
		id VARCHAR(64) NOT NULL,
		name VARCHAR(128) NOT NULL,
		scope VARCHAR(32) NOT NULL,
		team_id VARCHAR(64) NULL,
		repo VARCHAR(255) NULL,
		repo_url TEXT NOT NULL,
		branch VARCHAR(255) NOT NULL,
		path VARCHAR(512) NOT NULL DEFAULT '',
		enabled BOOL NOT NULL DEFAULT true,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		last_sync_at DATETIME(6) NULL,
		PRIMARY KEY (id),
		UNIQUE KEY uq_definition_sources_name (name),
		KEY idx_definition_sources_scope (scope, team_id, repo),
		KEY idx_definition_sources_enabled_updated (enabled, updated_at)
	)`,
	`CREATE TABLE IF NOT EXISTS definitions (
		id VARCHAR(64) NOT NULL,
		source_id VARCHAR(64) NOT NULL,
		definition_type VARCHAR(32) NOT NULL,
		name VARCHAR(128) NOT NULL,
		scope VARCHAR(32) NOT NULL,
		team_id VARCHAR(64) NULL,
		repo VARCHAR(255) NULL,
		path VARCHAR(512) NOT NULL,
		source_commit VARCHAR(64) NOT NULL,
		content_hash CHAR(64) NOT NULL,
		content MEDIUMTEXT NOT NULL,
		metadata JSON NULL,
		active BOOL NOT NULL DEFAULT true,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		UNIQUE KEY uq_definitions_source_type_name_path (source_id, definition_type, name, path),
		KEY idx_definitions_lookup (definition_type, name, active, scope),
		KEY idx_definitions_source_active (source_id, active, updated_at),
		KEY idx_definitions_hash (content_hash)
	)`,
	`CREATE TABLE IF NOT EXISTS definition_sync_runs (
		id VARCHAR(64) NOT NULL,
		source_id VARCHAR(64) NOT NULL,
		status VARCHAR(32) NOT NULL,
		source_commit VARCHAR(64) NULL,
		definitions_count INT NOT NULL DEFAULT 0,
		error TEXT NULL,
		started_at DATETIME(6) NOT NULL,
		ended_at DATETIME(6) NOT NULL,
		created_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		KEY idx_definition_sync_runs_source_created (source_id, created_at),
		KEY idx_definition_sync_runs_status_created (status, created_at)
	)`,
	`CREATE TABLE IF NOT EXISTS definition_change_proposals (
		id VARCHAR(64) NOT NULL,
		source_id VARCHAR(64) NOT NULL,
		task_id VARCHAR(64) NULL,
		repo VARCHAR(255) NOT NULL,
		branch VARCHAR(255) NOT NULL,
		base_branch VARCHAR(255) NOT NULL,
		pr_number INT NOT NULL,
		pr_url TEXT NOT NULL,
		title VARCHAR(255) NOT NULL,
		body MEDIUMTEXT NOT NULL,
		files JSON NOT NULL,
		status VARCHAR(32) NOT NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		UNIQUE KEY uq_definition_proposals_repo_pr (repo, pr_number),
		KEY idx_definition_proposals_source_created (source_id, created_at),
		KEY idx_definition_proposals_status_created (status, created_at),
		KEY idx_definition_proposals_task (task_id)
	)`,
}
