package store

var schemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS chetter_tasks (
		id VARCHAR(64) NOT NULL,
		status VARCHAR(32) NOT NULL,
		prompt TEXT NOT NULL,
		git_url TEXT NULL,
		git_ref VARCHAR(255) NULL,
		agent_image VARCHAR(512) NULL,
		agent VARCHAR(128) NULL,
		provider_id VARCHAR(128) NULL,
		model_id VARCHAR(255) NULL,
		variant_id VARCHAR(128) NULL,
		opencode_session_id VARCHAR(128) NULL,
		runner_image_digest VARCHAR(255) NULL,
		commit_author_name VARCHAR(128) NULL,
		commit_author_email VARCHAR(255) NULL,
		runner_id VARCHAR(64) NULL,
		required_runner_id VARCHAR(64) NULL,
		checkpoint_after_success BOOL NOT NULL DEFAULT false,
		trigger_name VARCHAR(128) NULL,
		trigger_type VARCHAR(32) NULL,
		claimed_at DATETIME(6) NULL,
		lease_expires_at DATETIME(6) NULL,
		attempt INT NOT NULL DEFAULT 0,
		max_attempts INT NOT NULL DEFAULT 3,
		skills JSON NOT NULL,
		env JSON NOT NULL,
		timeout_sec INT NOT NULL,
		summary TEXT NULL,
		error TEXT NULL,
		error_category VARCHAR(32) NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		last_event_at DATETIME(6) NULL,
		started_at DATETIME(6) NULL,
		ended_at DATETIME(6) NULL,
		session_export MEDIUMTEXT NULL,
		PRIMARY KEY (id),
		KEY idx_chetter_tasks_status_created (status, created_at),
		KEY idx_chetter_tasks_created (created_at),
		KEY idx_chetter_tasks_claim (status, lease_expires_at, created_at),
		KEY idx_chetter_tasks_runner (runner_id, status),
		KEY idx_chetter_tasks_trigger_created (trigger_name, created_at),
		KEY idx_chetter_tasks_required_runner (required_runner_id, status, created_at)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_agent_sessions (
		id VARCHAR(64) NOT NULL,
		team_id VARCHAR(64) NULL,
		status VARCHAR(32) NOT NULL,
		resume_mode VARCHAR(32) NOT NULL DEFAULT 'none',
		pinned_runner_id VARCHAR(64) NULL,
		pinned_runner_name VARCHAR(128) NULL,
		checkpoint_id VARCHAR(64) NULL,
		workspace_path TEXT NULL,
		container_name VARCHAR(128) NULL,
		harness_session_id VARCHAR(128) NULL,
		git_url TEXT NULL,
		git_ref VARCHAR(255) NULL,
		agent_image VARCHAR(512) NULL,
		agent VARCHAR(128) NULL,
		provider_id VARCHAR(128) NULL,
		model_id VARCHAR(255) NULL,
		variant_id VARCHAR(128) NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		paused_at DATETIME(6) NULL,
		expires_at DATETIME(6) NULL,
		pause_reason VARCHAR(64) NULL,
		error TEXT NULL,
		PRIMARY KEY (id),
		KEY idx_agent_sessions_team_status (team_id, status, updated_at),
		KEY idx_agent_sessions_runner_status (pinned_runner_id, status),
		KEY idx_agent_sessions_expires (expires_at)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_session_runs (
		id VARCHAR(64) NOT NULL,
		agent_session_id VARCHAR(64) NOT NULL,
		task_id VARCHAR(64) NOT NULL,
		status VARCHAR(32) NOT NULL,
		prompt TEXT NOT NULL,
		required_runner_id VARCHAR(64) NULL,
		summary TEXT NULL,
		error TEXT NULL,
		session_export MEDIUMTEXT NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		started_at DATETIME(6) NULL,
		ended_at DATETIME(6) NULL,
		PRIMARY KEY (id),
		UNIQUE KEY uq_session_runs_task (task_id),
		KEY idx_session_runs_session_created (agent_session_id, created_at),
		KEY idx_session_runs_status_created (status, created_at),
		KEY idx_session_runs_required_runner (required_runner_id, status)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_agent_session_checkpoints (
		id VARCHAR(64) NOT NULL,
		agent_session_id VARCHAR(64) NOT NULL,
		session_run_id VARCHAR(64) NULL,
		runner_id VARCHAR(64) NOT NULL,
		checkpoint_path TEXT NOT NULL,
		workspace_path TEXT NOT NULL,
		container_name VARCHAR(128) NULL,
		runsc_version VARCHAR(128) NULL,
		agent_image VARCHAR(512) NULL,
		size_bytes BIGINT NOT NULL DEFAULT 0,
		status VARCHAR(32) NOT NULL,
		error TEXT NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		expires_at DATETIME(6) NULL,
		PRIMARY KEY (id),
		KEY idx_session_checkpoints_session_created (agent_session_id, created_at),
		KEY idx_session_checkpoints_runner_status (runner_id, status),
		KEY idx_session_checkpoints_expires (expires_at)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_task_events (
		id VARCHAR(64) NOT NULL,
		task_id VARCHAR(64) NOT NULL,
		subject VARCHAR(255) NOT NULL,
		status VARCHAR(32) NOT NULL,
		event_type VARCHAR(64) NOT NULL DEFAULT 'task.progress',
		payload JSON NOT NULL,
		created_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		KEY idx_chetter_task_events_task_created (task_id, created_at),
		KEY idx_chetter_task_events_type_created (event_type, created_at),
		KEY idx_chetter_task_events_created (created_at)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_event_callbacks (
		id VARCHAR(64) NOT NULL,
		team_id VARCHAR(64) NULL,
		name VARCHAR(255) NOT NULL,
		event_type VARCHAR(64) NOT NULL,
		action_type VARCHAR(32) NOT NULL,
		action_config JSON NOT NULL,
		enabled BOOL NOT NULL DEFAULT true,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		UNIQUE KEY uq_event_callbacks_team_name (team_id, name),
		KEY idx_event_callbacks_team_enabled (team_id, enabled),
		KEY idx_event_callbacks_event_type (event_type, enabled)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_runners (
		id VARCHAR(64) NOT NULL,
		status VARCHAR(32) NOT NULL,
		image_ref VARCHAR(512) NULL,
		image_digest VARCHAR(255) NULL,
		version VARCHAR(128) NULL,
		max_concurrent INT NOT NULL DEFAULT 0,
		running_tasks INT NOT NULL DEFAULT 0,
		available_slots INT NOT NULL DEFAULT 0,
		total_started BIGINT NOT NULL DEFAULT 0,
		total_completed BIGINT NOT NULL DEFAULT 0,
		total_errors BIGINT NOT NULL DEFAULT 0,
		started_at DATETIME(6) NULL,
		first_seen_at DATETIME(6) NOT NULL,
		last_seen_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		metadata JSON NOT NULL,
		PRIMARY KEY (id),
		KEY idx_chetter_runners_status_seen (status, last_seen_at),
		KEY idx_chetter_runners_digest_seen (image_digest, last_seen_at)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_schedules (
		id VARCHAR(64) NOT NULL,
		name VARCHAR(128) NOT NULL,
		trigger_type VARCHAR(32) NOT NULL DEFAULT 'cron',
		trigger_config JSON NOT NULL,
		cron_expr VARCHAR(128) NOT NULL,
		prompt TEXT NOT NULL,
		git_url TEXT NULL,
		git_ref VARCHAR(255) NULL,
		agent_image VARCHAR(512) NULL,
		agent VARCHAR(128) NULL,
		provider_id VARCHAR(128) NULL,
		model_id VARCHAR(255) NULL,
		variant_id VARCHAR(128) NULL,
		harness VARCHAR(64) NULL,
		skills JSON NOT NULL,
		timeout_sec INT NOT NULL,
		enabled BOOL NOT NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		last_run_at DATETIME(6) NULL,
		next_run_at DATETIME(6) NULL,
		PRIMARY KEY (id),
		UNIQUE KEY uq_chetter_schedules_name (name),
		KEY idx_chetter_schedules_enabled_next (enabled, next_run_at)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_schedule_runs (
		id VARCHAR(64) NOT NULL,
		schedule_id VARCHAR(64) NOT NULL,
		team_id VARCHAR(64) NULL,
		task_id VARCHAR(64) NOT NULL,
		status VARCHAR(32) NOT NULL,
		scheduled_for DATETIME(6) NOT NULL,
		created_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		KEY idx_chetter_schedule_runs_schedule_created (schedule_id, created_at),
		KEY idx_chetter_schedule_runs_task (task_id)
	)`,
	`CREATE TABLE IF NOT EXISTS teams (
		id VARCHAR(64) NOT NULL,
		name VARCHAR(128) NOT NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		UNIQUE KEY uq_teams_name (name)
	)`,
	`CREATE TABLE IF NOT EXISTS users (
		id VARCHAR(64) NOT NULL,
		name VARCHAR(128) NOT NULL,
		team_id VARCHAR(64) NOT NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		KEY idx_users_team (team_id)
	)`,
	`CREATE TABLE IF NOT EXISTS api_tokens (
		id VARCHAR(64) NOT NULL,
		name VARCHAR(128) NOT NULL,
		token_hash CHAR(64) NOT NULL,
		user_id VARCHAR(64) NOT NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		UNIQUE KEY uq_api_tokens_hash (token_hash),
		KEY idx_api_tokens_user (user_id)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_audit_log (
		id VARCHAR(64) NOT NULL,
		event_type VARCHAR(64) NOT NULL,
		created_at DATETIME(6) NOT NULL,
		source_type VARCHAR(32) NULL,
		source_id VARCHAR(128) NULL,
		target_type VARCHAR(32) NULL,
		target_id VARCHAR(128) NULL,
		repo VARCHAR(255) NULL,
		github_event VARCHAR(64) NULL,
		github_action VARCHAR(64) NULL,
		github_delivery_id VARCHAR(128) NULL,
		parent_event_id VARCHAR(64) NULL,
		detail TEXT NULL,
		payload JSON NULL,
		PRIMARY KEY (id),
		KEY idx_audit_log_created (created_at),
		KEY idx_audit_log_source (source_type, source_id),
		KEY idx_audit_log_target (target_type, target_id),
		KEY idx_audit_log_repo (repo, created_at),
		KEY idx_audit_log_parent (parent_event_id)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_task_artifacts (
		id VARCHAR(64) NOT NULL,
		task_id VARCHAR(64) NOT NULL,
		agent_session_id VARCHAR(64) NULL,
		session_run_id VARCHAR(64) NULL,
		artifact_type VARCHAR(32) NOT NULL,
		repo VARCHAR(255) NOT NULL,
		number INT NULL,
		url TEXT NULL,
		ref VARCHAR(255) NULL,
		sha VARCHAR(64) NULL,
		created_at DATETIME(6) NOT NULL,
		discovered_at DATETIME(6) NOT NULL,
		discovery_source VARCHAR(32) NOT NULL,
		PRIMARY KEY (id),
		KEY idx_task_artifacts_task (task_id),
		KEY idx_task_artifacts_agent_session (agent_session_id),
		KEY idx_task_artifacts_session_run (session_run_id),
		KEY idx_task_artifacts_type_repo (artifact_type, repo),
		KEY idx_task_artifacts_number (repo, number)
	)`,
	`CREATE TABLE IF NOT EXISTS chetter_model_catalogs (
		id VARCHAR(64) NOT NULL,
		name VARCHAR(128) NOT NULL,
		active BOOL NOT NULL DEFAULT false,
		source VARCHAR(255) NULL,
		checksum CHAR(64) NOT NULL,
		yaml MEDIUMTEXT NOT NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		PRIMARY KEY (id),
		UNIQUE KEY uq_model_catalogs_name (name),
		KEY idx_model_catalogs_active_updated (active, updated_at)
	)`,
}
