#!/usr/bin/env bash
#
# gen-stats.sh — generate a Markdown report of code statistics for the Chetter repo.
#
# Combines cloc (lines of code per language, generated/vendored paths excluded)
# with repo-specific counts: database tables, migrations, MCP tools, protobuf
# services/RPCs, web routes, harnesses, and execution backends.
#
# Usage:
#   ./scripts/gen-stats.sh            # writes docs/STATS.md
#   ./scripts/gen-stats.sh /tmp/x.md  # write to a custom path
#
# Requirements: git, grep, find, and (optionally) cloc. When cloc is not
# installed the line-of-code table is skipped and a note is emitted instead;
# all other statistics are still generated.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="${1:-$REPO_ROOT/docs/STATS.md}"
cd "$REPO_ROOT"

# Exclusion list shared with scripts/cloc-chetter.sh (generated / vendored paths).
# STATS.md is the report this script writes, so it is excluded to keep the
# line count deterministic across runs.
CLOC_EXCLUDE_DIRS="gen,node_modules,build,.svelte-kit,bin,.git,.github,.opencode,.opentrace"
CLOC_NOT_MATCH_D="internal/repository|internal/webui/dist|web/src/gen"
CLOC_NOT_MATCH_F="\.svg$|\.png$|\.ico$|\.sum$|\.lock$|^STATS\.md$"

# --- Git ---------------------------------------------------------------
GIT_COMMIT="$(git rev-parse --short HEAD)"
GIT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
GIT_COMMITS="$(git rev-list --count HEAD)"
GENERATED_AT="$(date -u +"%Y-%m-%d %H:%M UTC")"

# --- Go ----------------------------------------------------------------
# Exclude sqlc/buf generated packages from the "hand-written" Go counts.
GO_FILES="$(git ls-files '*.go' | grep -vE '^(gen/|internal/repository|internal/repositorypostgres)' | wc -l | tr -d ' ')"
GO_PACKAGES="$(git ls-files '*.go' | grep -vE '^(gen/|internal/repository|internal/repositorypostgres)' | sed -E 's|/[^/]+\.go$||' | sort -u | wc -l | tr -d ' ')"

# --- Database -----------------------------------------------------------
TABLES="$(grep -c 'CREATE TABLE' internal/store/schema.go | tr -d ' ')"
MIGRATIONS_MYSQL="$(find db/migrations -maxdepth 1 -name '*.sql' | wc -l | tr -d ' ')"
MIGRATIONS_POSTGRES="$(find db/postgres/migrations -maxdepth 1 -name '*.sql' | wc -l | tr -d ' ')"
TABLE_NAMES_BULLETS="$(grep -oE 'CREATE TABLE IF NOT EXISTS [a-z_]+' internal/store/schema.go | awk '{print "  - `" $NF "`"}' | sort)"

# --- API surface --------------------------------------------------------
MCP_TOOLS="$(grep -c 'mcp.AddTool' internal/service/tools.go | tr -d ' ')"
PROTO_SERVICES="$(grep -hE '^service ' proto/api/v1/api.proto proto/runner/v1/runner.proto | wc -l | tr -d ' ')"
PROTO_RPCS="$(grep -hE '^[[:space:]]*rpc ' proto/api/v1/api.proto proto/runner/v1/runner.proto | wc -l | tr -d ' ')"

# --- Web UI -------------------------------------------------------------
WEB_ROUTES="$(find web/src/routes -name '+page.svelte' | wc -l | tr -d ' ')"
SVELTE_COMPONENTS="$(git ls-files '*.svelte' | wc -l | tr -d ' ')"
TS_FILES="$(git ls-files 'web/src/**/*.ts' | grep -v '/gen/' | wc -l | tr -d ' ')"

# --- Runner -------------------------------------------------------------
# Harness implementation packages live directly under runner/harness/; the
# mcp-bridge, mcpconfig, and transport directories are shared support code.
HARNESS_DIRS="$(find runner/harness -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | grep -vE '^(mcp-bridge|mcpconfig|transport)$' | sort)"
HARNESSES="$(printf '%s\n' "$HARNESS_DIRS" | sed '/^$/d' | wc -l | tr -d ' ')"
HARNESS_BULLETS="$(printf '%s\n' "$HARNESS_DIRS" | sed '/^$/d' | awk '{print "  - `" $1 "`"}')"

# --- Lines of code (cloc) ----------------------------------------------
if command -v cloc >/dev/null 2>&1; then
  LOC_MD="$(cloc --md --quiet \
    --exclude-dir="$CLOC_EXCLUDE_DIRS" \
    --not-match-d="$CLOC_NOT_MATCH_D" \
    --not-match-f="$CLOC_NOT_MATCH_F" \
    . 2>/dev/null || true)"

  # Drop cloc's banner + separator lines; keep only the Markdown table, and
  # remove cloc's trailing `-------|` divider so the table renders cleanly.
  LOC_SECTION="$(printf '%s\n' "$LOC_MD" | tail -n +4 | grep -vE '^-+\|')"
  TOTAL_CODE="$(printf '%s\n' "$LOC_MD" | awk -F'|' '/^SUM:/{print $5}' | tr -d '[:space:]')"
else
  LOC_SECTION="> _Note: \`cloc\` was not found on this machine, so the per-language line table was omitted. Install cloc and re-run to populate it._"
  TOTAL_CODE="n/a (install cloc for a line count)"
fi

mkdir -p "$(dirname "$OUT")"

cat > "$OUT" <<MD
# Chetter Code Statistics

_Generated by \`scripts/gen-stats.sh\` on ${GENERATED_AT} from commit \`${GIT_COMMIT}\` (branch \`${GIT_BRANCH}\`)._

## Summary

| Metric | Value |
|---|---|
| Total lines of code | ${TOTAL_CODE} |
| Git commits | ${GIT_COMMITS} |
| Go source files (hand-written) | ${GO_FILES} |
| Go packages | ${GO_PACKAGES} |
| Database tables | ${TABLES} |
| Migrations (MySQL/TiDB) | ${MIGRATIONS_MYSQL} |
| Migrations (PostgreSQL) | ${MIGRATIONS_POSTGRES} |
| MCP tools | ${MCP_TOOLS} |
| Protobuf services | ${PROTO_SERVICES} |
| Protobuf RPCs | ${PROTO_RPCS} |
| Web routes / pages | ${WEB_ROUTES} |
| Svelte components | ${SVELTE_COMPONENTS} |
| TypeScript source files | ${TS_FILES} |
| Runner harnesses | ${HARNESSES} |
| Execution backends | 3 (docker, kubernetes, local) |

## Lines of code by language

${LOC_SECTION}

Generated/vendored paths are excluded from the count (\`gen/\`, \`internal/repository*/\`,
\`internal/webui/dist\`, \`web/build\`, \`web/src/gen\`, \`node_modules\`, and similar).

## Database schema

The bootstrap schema (\`internal/store/schema.go\`) defines ${TABLES} tables:

${TABLE_NAMES_BULLETS}

Migrations are kept in two dialect-specific directories: \`db/migrations/\`
(${MIGRATIONS_MYSQL} files, MySQL/TiDB) and \`db/postgres/migrations/\`
(${MIGRATIONS_POSTGRES} files, PostgreSQL).

## API surface

The control plane exposes its capabilities through two schemas:

- **${MCP_TOOLS} MCP tools** registered in \`internal/service/tools.go\` (\`chetter_submit_task\`,
  \`chetter_list_tasks\`, trigger/session/token/team tools, and more).
- **${PROTO_SERVICES} protobuf services** with **${PROTO_RPCS} RPCs** across
  \`proto/api/v1/api.proto\` (web API) and \`proto/runner/v1/runner.proto\` (runner protocol).

## Runner

The runner supports ${HARNESSES} agent harnesses:

${HARNESS_BULLETS}

and three execution backends — \`docker\`, \`kubernetes\`, and \`local\` — with optional
gVisor (\`runsc\`) sandboxing for the container backends.

## Web UI

The SvelteKit frontend under \`web/\` contributes ${WEB_ROUTES} routes/pages and
${SVELTE_COMPONENTS} Svelte components, backed by ${TS_FILES} hand-written TypeScript files
(excluding generated \`web/src/gen/\`).
MD

echo "Wrote $OUT"
echo "  total code:    ${TOTAL_CODE}"
echo "  go files:      ${GO_FILES} (packages: ${GO_PACKAGES})"
echo "  tables:        ${TABLES} (migrations: ${MIGRATIONS_MYSQL} + ${MIGRATIONS_POSTGRES})"
echo "  mcp tools:     ${MCP_TOOLS}"
echo "  proto:         ${PROTO_SERVICES} services / ${PROTO_RPCS} rpcs"
echo "  web:           ${WEB_ROUTES} routes / ${SVELTE_COMPONENTS} components"
echo "  harnesses:     ${HARNESSES}"
